{
  "hash": "1816fedb6a069b774a538102b648d1c3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Day 1\"\nauthor: \"Khushi\"\n---\n\n\n## Introduction\n\nHi, this is my first time making a website.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.1     ✔ tibble    3.2.1\n✔ lubridate 1.9.3     ✔ tidyr     1.3.1\n✔ purrr     1.0.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggformula)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: scales\n\nAttaching package: 'scales'\n\nThe following object is masked from 'package:purrr':\n\n    discard\n\nThe following object is masked from 'package:readr':\n\n    col_factor\n\nLoading required package: ggridges\n\nNew to ggformula?  Try the tutorials: \n\tlearnr::run_tutorial(\"introduction\", package = \"ggformula\")\n\tlearnr::run_tutorial(\"refining\", package = \"ggformula\")\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(babynames)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbabynames\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,924,665 × 5\n    year sex   name          n   prop\n   <dbl> <chr> <chr>     <int>  <dbl>\n 1  1880 F     Mary       7065 0.0724\n 2  1880 F     Anna       2604 0.0267\n 3  1880 F     Emma       2003 0.0205\n 4  1880 F     Elizabeth  1939 0.0199\n 5  1880 F     Minnie     1746 0.0179\n 6  1880 F     Margaret   1578 0.0162\n 7  1880 F     Ida        1472 0.0151\n 8  1880 F     Alice      1414 0.0145\n 9  1880 F     Bertha     1320 0.0135\n10  1880 F     Sarah      1288 0.0132\n# ℹ 1,924,655 more rows\n```\n\n\n:::\n:::\n\n\nThe table displays baby names from 1880-2017, showing how frequently each name was given and its proportion among all births that year.\n\n### Looking up the name \"Aditi\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbabynames %>% filter(name==\"Aditi\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 40 × 5\n    year sex   name      n       prop\n   <dbl> <chr> <chr> <int>      <dbl>\n 1  1977 F     Aditi     5 0.00000304\n 2  1978 F     Aditi     9 0.00000548\n 3  1979 F     Aditi     9 0.00000522\n 4  1980 F     Aditi     6 0.00000337\n 5  1982 F     Aditi    10 0.00000551\n 6  1983 F     Aditi    12 0.00000671\n 7  1984 F     Aditi    10 0.00000555\n 8  1985 F     Aditi    17 0.00000921\n 9  1986 F     Aditi    22 0.0000119 \n10  1987 F     Aditi    21 0.0000112 \n# ℹ 30 more rows\n```\n\n\n:::\n:::\n\n\nThis table displays the usage of the name \"Aditi\" for baby girls in the United States between 1977 and 2017. The name was initially quite uncommon, with fewer than 10 occurrences annually from 1977 to 1982. Over the years, however, it steadily gained popularity. The peak was in 2008, when 203 baby girls were named Aditi, accounting for 0.0009755 of all female births that year. After 2008, the name’s popularity varied slightly but remained fairly stable, with a gradual decline in the following years. By 2017, 127 baby girls were named Aditi, representing 0.0006774 of female births.\n\n### Plotting a Line graph for the name \"Aditi\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbabynames %>% filter(name==\"Aditi\") %>% \n  gf_line(n~year)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nThe line graph shows the trend in the popularity of the name \"Aditi\" for baby girls in the United States from 1977 to 2017. The y-axis (n) represents the number of babies given the name each year, while the x-axis (year) tracks the years over time.The graph clearly illustrates a significant rise followed by a gradual decline.\n\n### Looking up my name -\"Khushi\" and another possible spelling -\"Kushi\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbabynames %>% filter(name==\"Khushi\" | name==\"Kushi\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 30 × 5\n    year sex   name       n       prop\n   <dbl> <chr> <chr>  <int>      <dbl>\n 1  1999 F     Khushi     5 0.00000257\n 2  2000 F     Khushi     6 0.00000301\n 3  2001 F     Khushi    44 0.0000222 \n 4  2002 F     Khushi    89 0.0000451 \n 5  2003 F     Khushi   178 0.0000888 \n 6  2003 F     Kushi      9 0.00000449\n 7  2004 F     Khushi   132 0.0000655 \n 8  2005 F     Khushi    86 0.0000424 \n 9  2005 F     Kushi      9 0.00000444\n10  2006 F     Khushi    69 0.0000330 \n# ℹ 20 more rows\n```\n\n\n:::\n:::\n\n\nThe comparison between the spellings \"Khushi\" and \"Kushi\" reveals notable trends. Neither name appeared in the U.S. dataset from 1880 to 1999, and both first emerged in 1999 with very low occurrences. However, \"Khushi\" quickly became more popular, while \"Kushi\" remained relatively rare. By 2003, 178 baby girls were named \"Khushi,\" compared to just 9 named \"Kushi,\" and this pattern persisted in the following years. Overall, \"Khushi\" consistently saw higher usage, demonstrating how different spellings of the same name can experience varying levels of adoption over time.\n\n### Plotting a Line graph for my name -\"Khushi\" and another possible spelling -\"Kushi\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbabynames %>% filter(name==\"Khushi\"| name==\"Kushi\") %>% \n  gf_line(n~year)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nThis line graph illustrates the trend in the popularity of the names \"Khushi\" and \"Kushi\" for baby girls in the U.S. from 1999 to 2017. The y-axis (n) represents the number of babies named each year, and the x-axis (year) tracks the timeline.\n\n### Looking up my roommate's name -\"Anousha\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbabynames %>% filter(name==\"Anousha\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n   year sex   name        n       prop\n  <dbl> <chr> <chr>   <int>      <dbl>\n1  2006 F     Anousha     6 0.00000287\n2  2007 F     Anousha     9 0.00000426\n3  2013 F     Anousha     5 0.0000026 \n```\n\n\n:::\n:::\n\n\nThe name \"Anousha\" is extremely rare in the \"babynames\" dataset, which spans from 1880 to 2017. Despite the large timeframe, the name appears only three times: in 2006, 2007, and 2013. In each of these years, the number of baby girls named Anousha was very low, with a maximum of just 9 occurrences in 2007.\n\n### Plotting a Line graph for my roommate's name -\"Anousha\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbabynames %>% filter(name==\"Anousha\") %>% \n gf_line(n~year)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nThis line graph shows the trend in the number of baby girls named \"Anousha\" in the U.S. from 2006 to 2013. The y-axis (n) represents the number of occurrences each year, while the x-axis (year) tracks the time period.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}