project:
  type: website

website:
  title: "Data-As-Material"  


navbar:
  right:  
    - text: "About"     
      link: about.qmd
    - icon: github      
      href: https://github.com/my-repo

format:
  html:
    theme: lux   
    css: styles.css   
    df_print: paged   

editor: visual




