project:
  type: website

website:
  title: "Data-As-Material"
  navbar:
   right:
    - about.qmd
    - icon: github
      href: https://github.com/

format:
  html:
    theme: lux
    css: styles.css
    df_print: paged

editor: visual





