{
  "hash": "720e2d5ce9ce03f4f67fe2c418b85d6a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 3 - Part 1\"\nauthor: \"Khushi\"\ncategories: [\"Assignments\"]\n---\n\n\n## Introduction\n\nWe are investigating spending behaviour between genders.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.1     ✔ tibble    3.2.1\n✔ lubridate 1.9.3     ✔ tidyr     1.3.1\n✔ purrr     1.0.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(mosaic)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRegistered S3 method overwritten by 'mosaic':\n  method                           from   \n  fortify.SpatialPolygonsDataFrame ggplot2\n\nThe 'mosaic' package masks several functions from core packages in order to add \nadditional features.  The original behavior of these functions should not be affected by this.\n\nAttaching package: 'mosaic'\n\nThe following object is masked from 'package:Matrix':\n\n    mean\n\nThe following objects are masked from 'package:dplyr':\n\n    count, do, tally\n\nThe following object is masked from 'package:purrr':\n\n    cross\n\nThe following object is masked from 'package:ggplot2':\n\n    stat\n\nThe following objects are masked from 'package:stats':\n\n    binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,\n    quantile, sd, t.test, var\n\nThe following objects are masked from 'package:base':\n\n    max, mean, min, prod, range, sample, sum\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggformula)\nlibrary(crosstable)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'crosstable'\n\nThe following object is masked from 'package:purrr':\n\n    compact\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(skimr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'skimr'\n\nThe following object is masked from 'package:mosaic':\n\n    n_missing\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(broom)\n```\n:::\n\n\n### **Research Experiment to Investigate Spending Behaviour Between Genders**\n\n**Objective:**\\\nThe purpose of this research experiment is to investigate whether there is a significant difference in the amount of money spent between guys and girls among students at MAHE Bengaluru. The study aims to test the hypothesis that guys tend to spend more money than girls, by collecting and analyzing spending data during a specific period.\n\n**Hypothesis:**\n\n-   Guys spend more money on average compared to girls within a given timeframe.\n\n**Experiment Design:**\\\n**Data Collection:**\n\n-   *Sample:* The dataset consists of spending data from 60 students at MAHE Bengaluru, with 30 guys and 30 girls. The participants were randomly selected through coin tosses and asked to record their spending on October 23rd, 2024.\n\n-   *Data Sources:* The data was recorded in an Excel sheet by the people conducting the experiment. Each participant reported how much money they spent on the allocated date.\n\n**Variables Measured:**\n\n-   *Target Variable:* Amount of money spent by each participant during the experiment period.\n\n-   *Predictor Variable:* Gender (guys vs. girls)\n\n**Sampling:**\n\n-   *Time Period:* The experiment was conducted on October 24th, 2024, over a period of 1.5 hours.\n\n-   *Participant Selection Criteria:* 30 guys and 30 girls were randomly selected by tossing a coin.\n\n**Analysis Plan:**\n\n-   *Data Cleaning and Transformation:* The data was checked for accuracy in the Excel sheet, ensuring that each participant's spending was properly recorded and that there were no missing or erroneous entries.\n\n-   *Exploratory Data Analysis (EDA):* Visualizations like histograms and box plots will be used to compare spending distributions between guys and girls, in order to identify any patterns or discrepancies.\n\n**Statistical Tests:**\n\n-   *Two-Sample t-Test:* A two-independent sample test for means has to be conducted to compare the average amount spent by guys and girls. This helps in determining if there is a statistically significant difference in spending behaviour between the two groups.\n\n\n```{=html}\n<!-- -->\n```\n\n-   *Permutation Test:* A permutation test has to be conducted to assess the likelihood of the observed difference in spending occurring by chance, providing a non-parametric alternative to the two-sample t-test.\n\n-   *Descriptive Statistics:* Measures like mean, median, and standard deviation have to be calculated for both groups to summarize spending behaviour.\n\n-   *Wilcoxon Rank-Sum Test:* This is a non-parametric test that has to be conducted to compare the spending behaviour between guys and girls.( if the normality assumption is not met )\n\n**Limitations:**\n\n-   *Sample Size:* With 30 participants per gender, the results may not be generalizable to a larger population. A more extensive sample would have provided greater reliability.\n\n-   *Contextual Factors:* The study did not account for reasons behind spending (e.g., necessities vs. discretionary purchases), which might have influenced spending patterns.\n\n**Outcome:**\\\nThe analysis will reveal whether a significant difference in spending exists between guys and girls at MAHE Bengaluru. If the hypothesis holds, it would suggest that guys, on average, spend more in a limited timeframe. These findings will provide insights into gender-specific spending behaviour within this student population.\n\n### Dataset - Spending\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspending_23rd <- read_csv(\"../../data/Pocketmoney.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 82 Columns: 4\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (2): Name, Gender\ndbl (2): Sr no, Money Spent\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\nspending_23rd\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 82 × 4\n   `Sr no` Name     Gender `Money Spent`\n     <dbl> <chr>    <chr>          <dbl>\n 1       1 Aagam    Male             150\n 2       2 Aakash   Male             240\n 3       3 Aarushi  Female           382\n 4       4 Abheeta  Female            60\n 5       5 Adithya  Male              68\n 6       6 Aditya   Male             300\n 7       7 Akanksha Female           270\n 8       8 Amruta   Female           190\n 9       9 Anaaya   Female           300\n10      10 Anish    Male               0\n# ℹ 72 more rows\n```\n\n\n:::\n:::\n\n\nThe table provides information on the spending behaviour of individuals on October 23rd, categorized by gender. It highlights the amount spent by 82 participants, allowing for a comparison of spending patterns between guys and girls. The data provides insight into the variability in spending amounts, as well as individual outliers, offering a basis for further analysis of gender-based financial behaviour.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspending_modified <- spending_23rd %>% \n  dplyr::mutate( Gender = as_factor(Gender)) \n```\n:::\n\n\n### Glimpse - Spending Behaviour\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(spending_modified)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 82\nColumns: 4\n$ `Sr no`       <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 1…\n$ Name          <chr> \"Aagam\", \"Aakash\", \"Aarushi\", \"Abheeta\", \"Adithya\", \"Adi…\n$ Gender        <fct> Male, Male, Female, Female, Male, Male, Female, Female, …\n$ `Money Spent` <dbl> 150, 240, 382, 60, 68, 300, 270, 190, 300, 0, 250, 85, 7…\n```\n\n\n:::\n:::\n\n\nThe columns include a unique identifier for each participant (**Sr no**), their **Name**, **Gender** (male or female), and the **Money Spent**. The dataset contains numeric data for the money spent, with a wide range of amounts from 0 to significant expenditures, allowing for analysis of spending patterns between males and females.\n\n### Inspect - Spending Behaviour\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninspect(spending_modified)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\ncategorical variables:  \n    name     class levels  n missing\n1   Name character     82 82       0\n2 Gender    factor      2 82       0\n                                   distribution\n1 Aagam (1.2%), Aakash (1.2%) ...              \n2 Male (50%), Female (50%)                     \n\nquantitative variables:  \n         name   class min     Q1 median     Q3   max     mean         sd  n\n1       Sr no numeric   1  21.25   41.5  61.75    82  41.5000   23.81526 82\n2 Money Spent numeric   0 100.00  264.5 596.25 13000 720.9634 1835.72169 82\n  missing\n1       0\n2       0\n```\n\n\n:::\n:::\n\n\nThe gender distribution is evenly split, with no missing data in the dataset. The summary statistics for the **Money Spent** variable show a wide range of spending, with a minimum value of 0 rupees and a maximum value of 13,000 rupees. The median spending is 264.5 rupees, while the mean spending is 720.9 rupees, indicating that a few individuals spent significantly more than others. The standard deviation of 1,835.3 rupees reflects a high level of variability in spending behavior. These results suggest that while most participants had moderate spending, a few high spenders significantly influenced the overall average.\n\n### Skim - Spending Behaviour\n\n\n::: {.cell}\n\n```{.r .cell-code}\nskim(spending_modified)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |                  |\n|:------------------------|:-----------------|\n|Name                     |spending_modified |\n|Number of rows           |82                |\n|Number of columns        |4                 |\n|_______________________  |                  |\n|Column type frequency:   |                  |\n|character                |1                 |\n|factor                   |1                 |\n|numeric                  |2                 |\n|________________________ |                  |\n|Group variables          |None              |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|Name          |         0|             1|   3|  12|     0|       82|          0|\n\n\n**Variable type: factor**\n\n|skim_variable | n_missing| complete_rate|ordered | n_unique|top_counts       |\n|:-------------|---------:|-------------:|:-------|--------:|:----------------|\n|Gender        |         0|             1|FALSE   |        2|Mal: 41, Fem: 41 |\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|   mean|      sd| p0|    p25|   p50|    p75|  p100|hist  |\n|:-------------|---------:|-------------:|------:|-------:|--:|------:|-----:|------:|-----:|:-----|\n|Sr no         |         0|             1|  41.50|   23.82|  1|  21.25|  41.5|  61.75|    82|▇▇▇▇▇ |\n|Money Spent   |         0|             1| 720.96| 1835.72|  0| 100.00| 264.5| 596.25| 13000|▇▁▁▁▁ |\n\n\n:::\n:::\n\n\nThe key variable of interest, **Money Spent**, shows a mean spending of 720.96 rupees, with a high variability indicated by a standard deviation of 1,835.7 rupees. The spending ranges from 0 to 13,000 rupees, with a median of 264.5 rupees. The distribution is heavily skewed, with most participants spending below the median, but a few high spenders significantly contributing to the total amount, leading to the large spread in spending behavior.\n\n### Data Dictionary\n\n#### Quantitative Data:\n\n-   **Money Spent (dbl)**: The total amount of money spent by each participant on October 23rd, recorded in Indian rupees.\n\n#### Qualitative Data:\n\n-   **Sr no (fct)**: A sequential number assigned to each participant for identification purposes (treated as a categorical factor).\n\n-   **Name (chr)**: The name of the participant.\n\n-   **Gender (chr)**: The gender of the participant, categorized as either Male or Female.\n\n### Histogram - Distribution of Money Spent by Gender\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_histogram(~ `Money Spent` | Gender, \n             data = spending_modified, \n             binwidth = 200, \n             fill = \"skyblue\", \n             color = \"black\") %>% \n  gf_labs(\n    title = \"Distribution of Money Spent by Gender\",\n    x = \"Money Spent (in rupees)\",\n    y = \"Count\"\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nThe histograms comparing money spent by gender reveal that both males and females exhibit a similar spending pattern, with the majority of participants spending relatively small amounts, primarily below 1,000 rupees. There is a notable concentration of individuals in both groups who spent minimal amounts (0 to 500 rupees), with a few significant outliers who spent as much as 13,000 rupees. The distribution is right-skewed for both genders, indicating that while most participants spent modestly, a few individuals in each group spent considerably more. Overall, the spending behaviour shows similar trends between males and females, with only slight variations in the frequency of higher spending outliers.\n\n### Bar Chart - Average Money Spent by Gender\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_bar(\n  mean(`Money Spent`) ~ Gender,\n  data = spending_modified,\n  fill = ~ Gender\n) %>% \n  gf_labs(\n    title = \"Average Money Spent by Gender\",\n    x = \"Gender\",\n    y = \"Average Money Spent (in rupees)\"\n  ) \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Ignoring unknown aesthetics: .\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nThe bar chart compares the average money spent by gender, showing that both males and females have nearly identical average spending, with only a slight difference. The mean amount spent by males and females is approximately 721 rupees, indicating that, on average, there is minimal variation in spending behaviour between the two genders in this dataset. This suggests that gender does not significantly influence the average amount of money spent on October 23rd.\n\n### Boxplot - Distribution of Money Spent by Gender\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_boxplot(`Money Spent` ~ Gender, \n           data = spending_modified, \n           fill = ~ Gender) %>% \n  gf_labs(\n    title = \"Distribution of Money Spent by Gender\",\n    x = \"Gender\",\n    y = \"Money Spent (in rupees)\"\n  ) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nThe box plot comparing the distribution of money spent between males and females shows that both genders have a similar range of spending, with most participants spending relatively low amounts. The median spending is low for both genders, as indicated by the position of the boxes. However, there are a few notable outliers in both groups, with some individuals spending significantly higher amounts, particularly around 10,000 rupees for males. These outliers create a noticeable extension in the upper range of the male box plot. Overall, the distribution suggests that while typical spending is modest, a few individuals in both groups account for much higher spending.\n\n### Scatter Plot - Individual Money Spent by Gender\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_point(`Money Spent` ~ Gender, \n         data = spending_modified,\n         color = ~ Gender) %>% \n  gf_labs(\n    title = \"Individual Money Spent by Gender\",\n    x = \"Gender\",\n    y = \"Money Spent (in rupees)\"\n  ) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nThe scatter plot displays individual spending points for both males and females, highlighting the distribution of money spent on October 23rd. Most participants, regardless of gender, spent relatively small amounts, clustering around the lower end of the plot. However, there are noticeable outliers in both groups, with a few individuals spending significantly higher amounts—one female and one male spending close to 13,000 rupees. These outliers are clearly separated from the main group, indicating that while the general spending pattern is modest, a few individuals contribute to a much higher level of spending.\n\n### Density Plot of Money Spent\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspending_modified %>%\n  gf_density(~ `Money Spent`, fill = \"gray\", alpha = 0.5) %>%\n  gf_fitdistr(~ `Money Spent`, dist = \"dnorm\") %>%\n  gf_labs(\n    title = \"Density Plot of Money Spent\",\n    subtitle = \"Compared with Normal Distribution\",\n    x = \"Money Spent (in rupees)\",\n    y = \"Density\"\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nThe actual spending data is highly right-skewed, with a majority of participants spending small amounts, as indicated by the sharp peak near zero. The density drops off quickly, with a long tail extending toward higher spending amounts, reflecting a few individuals who spent significantly more. The fitted normal distribution deviates from the actual data, confirming that the spending data does not follow a normal distribution, particularly due to the extreme outliers and the overall skewness. This suggests that parametric tests assuming normality may not be appropriate without data transformation. ( If the data is not normally distributed, the results could be unreliable.)\n\n### Log-Transformed Distribution of Money Spent\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspending_modified <- spending_modified %>%\n  mutate(log_money_spent = log(`Money Spent` + 1))\n\ngf_density(~ log_money_spent, data = spending_modified) %>% \n  gf_labs(\n    title = \"Log-Transformed Distribution of Money Spent\",\n    x = \"Log of Money Spent\",\n    y = \"Density\"\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nThe density plot of the log-transformed spending data shows a more symmetric distribution compared to the original skewed data. After applying the log transformation, the previously right-skewed data is now centered with a peak around a log value of 4 to 5, suggesting a more normalized spread of spending behavior. While the log transformation has reduced the extreme effects of outliers and compressed the range of higher values, the data still exhibits some variation but appears more suitable for parametric testing.\n\n### The t-test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt <- t.test(\n  `Money Spent` ~ Gender, \n  data = spending_modified, \n  mu = 0, \n  alternative = \"two.sided\", \n  conf.int = TRUE, \n  conf.level = 0.95\n) %>% \nbroom::tidy()\n\nt\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 10\n  estimate estimate1 estimate2 statistic p.value parameter conf.low conf.high\n     <dbl>     <dbl>     <dbl>     <dbl>   <dbl>     <dbl>    <dbl>     <dbl>\n1     55.3      749.      693.     0.136   0.893      76.5    -757.      868.\n# ℹ 2 more variables: method <chr>, alternative <chr>\n```\n\n\n:::\n:::\n\n\nThe results of the Welch Two-Sample t-test comparing the average money spent by males and females show a **t-value of 0.13555** and a **p-value of 0.8925**, which is much larger than the typical significance threshold of 0.05. This indicates that there is **no statistically significant difference** in the mean spending between the two groups. The 95% confidence interval for the difference in means ranges from **-757.07 to 867.66**, further suggesting that the difference could be zero. The mean spending for males was **748.61 rupees**, while the mean for females was **693.32 rupees**, but this difference is not statistically significant based on the t-test results.\n\n### Wilcoxon's Signed-Rank Test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox_test <- wilcox.test(\n  `Money Spent` ~ Gender, \n  data = spending_modified, \n  alternative = \"two.sided\", \n  conf.int = TRUE, \n  conf.level = 0.95\n) %>% \nbroom::tidy()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in wilcox.test.default(x = DATA[[1L]], y = DATA[[2L]], ...): cannot\ncompute exact p-value with ties\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in wilcox.test.default(x = DATA[[1L]], y = DATA[[2L]], ...): cannot\ncompute exact confidence intervals with ties\n```\n\n\n:::\n\n```{.r .cell-code}\nwilcox_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 7\n  estimate statistic p.value conf.low conf.high method               alternative\n     <dbl>     <dbl>   <dbl>    <dbl>     <dbl> <chr>                <chr>      \n1     55.0      936.   0.381    -70.0      180. Wilcoxon rank sum t… two.sided  \n```\n\n\n:::\n:::\n\n\nThe Wilcoxon Signed-Rank Test results indicate that the **p-value is 0.3806**, which is greater than the common significance threshold of 0.05. This suggests that there is **no statistically significant difference** in the median spending between males and females. The test statistic is **935.5**, with a 95% confidence interval for the difference in spending between groups ranging from **-69.99 to 180**. The estimate of the difference in ranks is **55.00**, further indicating that the observed difference in spending behavior is not large enough to be statistically significant. Therefore, based on this test, we cannot conclude that there is a significant difference in spending between males and females.\n\n### Permutation Test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nperm_test_result <- do(1000) * diffmean(\n  shuffle(`Money Spent`) ~ Gender, \n  data = spending_modified\n)\nperm_test_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         diffmean\n1    -311.3414634\n2     633.2439024\n3     671.0487805\n4      84.4146341\n5    -686.6097561\n6     145.0000000\n7    -195.9268293\n8     577.1463415\n9    -125.8292683\n10    373.0487805\n11    -56.5121951\n12   -510.1219512\n13    618.6097561\n14     98.7073171\n15    145.9756098\n16    135.8780488\n17   -660.0243902\n18   -303.5853659\n19   -821.2439024\n20    167.5853659\n21     75.1463415\n22    421.6341463\n23   -614.1219512\n24    -21.8780488\n25   -330.7073171\n26   -588.4634146\n27    745.4878049\n28   -103.0487805\n29   -114.8536585\n30     72.3658537\n31    -37.4390244\n32   -174.4146341\n33   -198.3170732\n34    637.7317073\n35     27.8292683\n36    -73.9268293\n37    128.3170732\n38    449.6341463\n39    702.2682927\n40   -470.0731707\n41   -140.4634146\n42    134.8048780\n43    466.1219512\n44   -151.0000000\n45    561.7804878\n46   -661.3414634\n47   -434.8048780\n48    170.3658537\n49   -485.0975610\n50    546.6097561\n51   -420.2195122\n52   -703.7317073\n53    526.2682927\n54    -88.3170732\n55    540.6585366\n56   -354.6585366\n57     68.2682927\n58   -168.2682927\n59   -205.4390244\n60    522.1707317\n61    547.4390244\n62    131.0975610\n63   -527.9268293\n64    346.4634146\n65    572.2195122\n66    107.7804878\n67   -419.0487805\n68    330.0731707\n69    -21.7317073\n70    348.4146341\n71    629.0975610\n72    -93.3414634\n73    601.2926829\n74    284.1707317\n75   -434.0731707\n76     -8.3170732\n77    208.1707317\n78   -122.1219512\n79   -540.5609756\n80   -718.2195122\n81   -252.4634146\n82   -541.9268293\n83   -354.6097561\n84    287.5365854\n85   -713.3902439\n86    462.3658537\n87    156.0243902\n88    434.3658537\n89     77.4878049\n90    608.7560976\n91   -128.8048780\n92    -42.3658537\n93    -37.8292683\n94   -781.8780488\n95    475.3414634\n96   -752.4634146\n97   -358.9024390\n98   -470.1707317\n99    -30.9024390\n100  -570.4146341\n101   567.4878049\n102    14.9512195\n103   721.8292683\n104   -46.8048780\n105   482.5609756\n106  -642.6585366\n107  -269.1951220\n108   487.0975610\n109   517.7317073\n110  -634.3658537\n111   266.5121951\n112   295.4390244\n113  -740.2682927\n114  -385.1951220\n115    80.5121951\n116  -669.7317073\n117   345.4878049\n118    75.6341463\n119    49.0487805\n120   343.7804878\n121    54.8048780\n122   435.5853659\n123  -653.9756098\n124  -683.7804878\n125   257.5365854\n126   645.5365854\n127  -444.2682927\n128  -749.9268293\n129   821.1951220\n130    56.5121951\n131   472.0243902\n132  -254.4634146\n133     8.2682927\n134  -761.2439024\n135  -602.1707317\n136  -174.0243902\n137  -229.3414634\n138  -593.9268293\n139   210.3658537\n140  -592.8048780\n141  -372.8048780\n142   751.7317073\n143   -34.5609756\n144   703.2926829\n145   722.7560976\n146  -378.0243902\n147  -122.3170732\n148    58.6097561\n149   -42.4146341\n150   716.2195122\n151    47.1463415\n152  -553.6341463\n153   596.4634146\n154   669.0000000\n155  -721.2926829\n156  -187.8292683\n157    39.9268293\n158   -55.7317073\n159  -341.1463415\n160   -85.0000000\n161   144.4146341\n162   395.2926829\n163   664.6097561\n164  -581.5853659\n165    27.2439024\n166   362.0731707\n167    21.1951220\n168  -314.6585366\n169    10.6097561\n170  -777.6341463\n171   217.1951220\n172   106.0731707\n173  -206.4634146\n174   288.8536585\n175  -213.0487805\n176   -24.6097561\n177   -40.0243902\n178  -263.5365854\n179   754.1219512\n180    34.3170732\n181   267.9756098\n182   124.0731707\n183   425.5853659\n184   580.4634146\n185   495.0000000\n186   518.5121951\n187   100.7073171\n188   461.4878049\n189   -15.6341463\n190   616.1219512\n191   767.3414634\n192   193.2926829\n193  -107.0000000\n194    74.9024390\n195   548.4146341\n196   344.3170732\n197   584.0731707\n198  -540.8536585\n199  -630.3170732\n200  -162.0731707\n201  -595.0487805\n202  -493.2439024\n203  -333.0487805\n204  -681.2926829\n205   456.2195122\n206  -145.7317073\n207   -88.1219512\n208   707.5853659\n209  -298.0243902\n210  -732.3658537\n211  -523.9756098\n212  -712.9024390\n213   -24.4634146\n214  -270.4146341\n215  -101.7804878\n216   368.7560976\n217  -190.5121951\n218  -177.7804878\n219    71.2439024\n220  -638.2195122\n221  -114.3170732\n222  -588.7073171\n223   716.6097561\n224   503.1951220\n225  -123.4390244\n226  -610.4634146\n227   190.5609756\n228   122.7560976\n229    27.5853659\n230   448.1219512\n231  -381.6341463\n232   114.1219512\n233  -634.7560976\n234   101.4878049\n235    82.0243902\n236   487.9756098\n237   191.1463415\n238  -709.0487805\n239  -100.9024390\n240   495.5853659\n241  -526.1219512\n242    15.0487805\n243   149.1463415\n244  -635.4878049\n245  -595.0000000\n246   170.7073171\n247  -720.5609756\n248  -110.1219512\n249   713.3414634\n250   251.5365854\n251   598.6097561\n252   -20.1707317\n253  -339.0487805\n254   -50.8048780\n255  -651.2439024\n256  -186.6585366\n257  -477.2439024\n258  -157.9756098\n259   486.7073171\n260   -93.2439024\n261    24.5609756\n262  -191.0487805\n263  -198.2195122\n264   276.2195122\n265  -254.2682927\n266   159.8780488\n267   309.2439024\n268   219.0000000\n269   294.8536585\n270   387.7317073\n271  -617.9756098\n272  -180.0731707\n273   496.4634146\n274  -182.7560976\n275   410.1707317\n276   179.8292683\n277   559.5853659\n278   606.7560976\n279   -26.1707317\n280  -485.8292683\n281     0.7073171\n282  -817.7317073\n283  -375.7804878\n284  -189.4878049\n285    77.6341463\n286    79.6341463\n287    83.8780488\n288   495.0487805\n289     9.1951220\n290   186.4634146\n291    32.1219512\n292   484.1707317\n293   165.2439024\n294  -563.2926829\n295  -301.1951220\n296   705.1951220\n297   -70.8536585\n298  -520.1219512\n299  -680.9512195\n300    97.7804878\n301  -466.6097561\n302  -194.9024390\n303   -62.1219512\n304   312.7073171\n305  -352.7560976\n306  -250.7560976\n307  -641.0975610\n308   176.0243902\n309  -101.0487805\n310  -166.4146341\n311   362.5121951\n312  -450.3170732\n313   172.6585366\n314  -465.8780488\n315  -464.0243902\n316   525.4878049\n317   666.5121951\n318   543.6829268\n319   588.5121951\n320  -107.3414634\n321    41.6341463\n322   277.6829268\n323    81.0487805\n324  -334.3658537\n325   -95.0000000\n326   -90.3658537\n327    52.4634146\n328   762.4146341\n329  -118.6097561\n330  -495.5853659\n331  -452.2195122\n332  -107.3414634\n333  -173.2439024\n334    83.4878049\n335   386.9512195\n336  -359.4390244\n337   297.4390244\n338   673.0000000\n339  -290.3170732\n340   631.1463415\n341  -137.5365854\n342   365.4390244\n343   184.0243902\n344  -194.7073171\n345  -155.3902439\n346   604.2682927\n347   526.5121951\n348   486.0243902\n349  -207.6341463\n350   713.6341463\n351  -489.9268293\n352  -177.9268293\n353   341.9756098\n354   -39.8780488\n355   153.5853659\n356   239.9756098\n357   649.6829268\n358   -73.7804878\n359  -104.4146341\n360    67.6341463\n361    39.0487805\n362    18.3170732\n363   -58.0243902\n364  -471.2439024\n365   297.0487805\n366    71.7804878\n367    -9.4390244\n368  -492.7073171\n369  -144.1707317\n370   726.9024390\n371   128.8048780\n372   509.7804878\n373  -250.6585366\n374   -78.0731707\n375  -176.4146341\n376  -301.4878049\n377  -526.8048780\n378   301.0487805\n379    20.5121951\n380   406.6097561\n381  -277.3414634\n382    99.3414634\n383  -251.4878049\n384    -7.8780488\n385   297.5365854\n386   -48.0731707\n387  -533.7317073\n388   555.2439024\n389  -106.0731707\n390   461.2439024\n391    55.4390244\n392   144.2195122\n393  -498.5609756\n394   828.7073171\n395  -117.9268293\n396    58.5121951\n397   -36.3658537\n398   755.1951220\n399  -134.5609756\n400   158.5609756\n401    -4.0731707\n402   117.7804878\n403  -114.5121951\n404  -589.4878049\n405    90.0731707\n406  -837.1951220\n407   444.7560976\n408   362.2682927\n409   152.1219512\n410  -591.1463415\n411   318.7073171\n412  -544.0731707\n413  -371.4390244\n414    26.2682927\n415   306.2682927\n416   -87.8292683\n417  -466.8536585\n418   769.0487805\n419   -84.7073171\n420    24.4634146\n421   688.5609756\n422  -174.0243902\n423    73.6829268\n424  -105.6829268\n425  -369.5365854\n426    72.1707317\n427   235.9268293\n428   622.9024390\n429   -41.6829268\n430   553.0975610\n431  -485.0000000\n432   -35.2926829\n433   -35.4878049\n434   -88.3170732\n435  -534.1707317\n436  -224.8048780\n437   509.8292683\n438  -698.3658537\n439  -716.4146341\n440   203.3902439\n441   287.6341463\n442  -630.1707317\n443   139.8780488\n444    76.4146341\n445  -358.5121951\n446   407.4390244\n447  -670.0243902\n448    81.2439024\n449  -147.8780488\n450  -168.5121951\n451  -608.7073171\n452    96.8536585\n453   659.0975610\n454  -595.3902439\n455   313.2439024\n456   144.4634146\n457  -677.2439024\n458   454.6097561\n459   502.0731707\n460  -342.0243902\n461   546.6585366\n462   -32.9024390\n463  -557.6341463\n464   -70.4146341\n465  -269.0000000\n466   761.0975610\n467  -723.8292683\n468   510.5121951\n469   231.0975610\n470   391.3902439\n471   226.1707317\n472   149.6341463\n473  -525.6341463\n474  -605.5853659\n475   679.8780488\n476   375.5365854\n477   699.5365854\n478   212.6585366\n479  -431.9756098\n480  -700.7073171\n481   -93.6341463\n482  -431.5365854\n483   -48.2195122\n484   111.3902439\n485  -681.4878049\n486  -134.4146341\n487   514.0243902\n488  -390.9024390\n489   661.7804878\n490   174.7560976\n491   -49.0975610\n492   -10.4146341\n493  -318.8048780\n494    -6.9024390\n495   112.3658537\n496   651.6341463\n497   635.7804878\n498  -186.0731707\n499   351.2439024\n500  -613.7804878\n501  -586.8536585\n502  -314.7560976\n503  -179.0975610\n504   610.3170732\n505    49.0487805\n506    94.8048780\n507   104.2195122\n508    89.4878049\n509   249.6829268\n510  -575.1951220\n511   280.4146341\n512   364.3170732\n513   118.5121951\n514  -596.1707317\n515  -681.0975610\n516  -167.1951220\n517  -788.7560976\n518   486.4146341\n519  -188.4146341\n520  -220.6585366\n521   348.4634146\n522    49.9756098\n523    -0.5121951\n524  -153.8780488\n525    76.7073171\n526  -169.4390244\n527  -234.6097561\n528   113.3902439\n529  -384.6097561\n530   236.9024390\n531   696.3170732\n532   137.0975610\n533    21.1463415\n534   445.6829268\n535   235.0487805\n536   632.2682927\n537   490.1707317\n538   541.2926829\n539   248.3658537\n540  -587.1951220\n541  -542.9512195\n542   338.8536585\n543  -161.8780488\n544  -125.8292683\n545  -487.7804878\n546   858.1707317\n547   413.5365854\n548    46.9512195\n549  -495.1463415\n550  -461.7804878\n551    93.0975610\n552   102.4634146\n553   751.1951220\n554    79.0975610\n555  -491.1463415\n556   -23.6829268\n557   122.7560976\n558   686.6585366\n559   -44.0731707\n560   201.2439024\n561    59.8780488\n562  -600.1707317\n563   128.6097561\n564   789.4390244\n565    34.9024390\n566   -20.4146341\n567   356.9024390\n568  -510.0243902\n569  -173.9268293\n570   463.5365854\n571  -738.6585366\n572   621.2926829\n573   -27.7317073\n574   199.1951220\n575    33.0487805\n576   611.0000000\n577  -138.0731707\n578  -157.0487805\n579   273.5853659\n580   267.2926829\n581  -414.4634146\n582   139.5365854\n583    58.3170732\n584   426.5121951\n585    95.4390244\n586   169.4390244\n587   367.5853659\n588   -11.2926829\n589   -45.1463415\n590  -400.8536585\n591  -559.3414634\n592   442.5609756\n593  -721.7317073\n594   672.5121951\n595    22.8048780\n596   168.4146341\n597   102.2682927\n598  -587.8292683\n599  -683.5365854\n600    39.8780488\n601   430.1707317\n602   712.5121951\n603   549.7317073\n604   454.1219512\n605   161.9756098\n606  -470.5609756\n607  -178.2195122\n608   691.1463415\n609  -524.9024390\n610   821.7317073\n611   -48.5609756\n612   -52.7560976\n613   596.9512195\n614    75.6829268\n615   714.8536585\n616  -119.7317073\n617   -70.0731707\n618   279.6341463\n619  -107.1463415\n620  -193.5853659\n621    98.1707317\n622   267.0000000\n623  -108.8048780\n624   -82.7073171\n625  -678.1707317\n626   729.0975610\n627   163.8292683\n628   334.6097561\n629   345.8780488\n630   230.8048780\n631   109.9268293\n632  -153.3414634\n633   109.8780488\n634   247.3414634\n635   516.2682927\n636   436.2195122\n637    24.9024390\n638  -649.8780488\n639   316.4634146\n640   -55.2439024\n641   138.9024390\n642  -149.9756098\n643    30.0731707\n644  -220.5121951\n645   762.9512195\n646   605.3414634\n647   156.3658537\n648  -720.4634146\n649   -10.9512195\n650   726.5121951\n651  -179.0487805\n652  -498.3658537\n653  -565.8780488\n654  -291.8292683\n655   728.5609756\n656   -61.4390244\n657  -226.3658537\n658  -487.3414634\n659   341.1951220\n660  -245.7804878\n661  -644.1219512\n662   230.7560976\n663   -90.5609756\n664   585.6829268\n665  -271.8780488\n666  -779.4390244\n667  -281.3902439\n668    73.1951220\n669   -35.4390244\n670   463.7317073\n671   468.6097561\n672  -161.9268293\n673  -559.4878049\n674  -183.3414634\n675  -248.2195122\n676   682.3170732\n677  -385.6829268\n678   -13.9756098\n679   737.2439024\n680   201.6341463\n681   437.3414634\n682  -683.3902439\n683  -313.7804878\n684  -232.7073171\n685    -3.3902439\n686   -25.9268293\n687   -42.6585366\n688   414.6585366\n689   107.5853659\n690  -444.4634146\n691   239.5365854\n692  -684.1707317\n693  -267.5365854\n694   505.6341463\n695   660.5121951\n696  -135.0000000\n697   656.2195122\n698    76.6097561\n699   558.0243902\n700  -809.1463415\n701   -64.7073171\n702   271.7804878\n703  -129.2926829\n704  -505.6829268\n705  -275.1463415\n706   -45.8292683\n707  -651.8780488\n708   186.5609756\n709   596.3170732\n710   -78.5609756\n711     1.0975610\n712   690.0243902\n713   647.6341463\n714    88.5121951\n715  -684.1219512\n716  -449.1463415\n717   -37.9756098\n718  -460.7073171\n719   423.9268293\n720   -98.9512195\n721   111.8780488\n722   453.5853659\n723   343.7317073\n724  -186.8536585\n725    71.2926829\n726   547.6829268\n727  -135.1463415\n728   397.4878049\n729   555.2926829\n730   554.7073171\n731   -80.6585366\n732   702.5609756\n733  -575.7317073\n734   -97.1951220\n735   -33.1951220\n736   561.1463415\n737  -569.4390244\n738   473.1951220\n739   -85.4878049\n740   338.2195122\n741   707.5365854\n742    81.1463415\n743   514.0243902\n744  -343.6341463\n745   616.8048780\n746   431.8780488\n747  -175.9756098\n748  -242.3658537\n749  -154.8048780\n750  -587.5853659\n751  -218.5609756\n752  -219.7804878\n753    16.3170732\n754   599.4878049\n755   250.8048780\n756  -172.4634146\n757   -69.8780488\n758   -94.3170732\n759  -348.9024390\n760   266.9024390\n761   100.8048780\n762   664.6097561\n763   121.6341463\n764  -593.9268293\n765  -168.1219512\n766   -22.8536585\n767  -158.4146341\n768  -527.0975610\n769   481.0487805\n770   556.2682927\n771   103.1951220\n772     2.5121951\n773    80.7073171\n774    61.1951220\n775   -52.5121951\n776  -287.5853659\n777    86.0243902\n778  -122.3170732\n779  -359.5853659\n780   846.1707317\n781   493.6341463\n782   304.0731707\n783   274.4634146\n784  -125.8780488\n785    55.9268293\n786   568.6097561\n787   -83.0487805\n788  -148.3658537\n789  -279.5365854\n790  -466.2682927\n791    49.4878049\n792   504.5609756\n793    30.0243902\n794   355.6341463\n795  -399.5853659\n796   230.1219512\n797  -105.3414634\n798   -77.2439024\n799   542.0243902\n800  -456.3658537\n801   449.8780488\n802   116.7073171\n803   -44.4634146\n804  -483.8292683\n805   608.9512195\n806  -430.0731707\n807  -744.5121951\n808   593.5365854\n809    35.9268293\n810   361.1951220\n811  -693.2926829\n812   151.9268293\n813  -586.5121951\n814  -582.7560976\n815   581.7317073\n816   214.4634146\n817   -70.4146341\n818   247.1463415\n819  -293.2439024\n820  -727.1463415\n821    80.8536585\n822  -239.3902439\n823   -47.5365854\n824   -78.1219512\n825  -163.5853659\n826   712.9512195\n827   451.2926829\n828   712.4634146\n829    91.0000000\n830  -267.8292683\n831   311.4878049\n832   -74.1219512\n833  -706.5121951\n834    92.7560976\n835  -719.0975610\n836   107.7317073\n837   595.3902439\n838   328.3658537\n839   129.3414634\n840    48.3658537\n841   485.1951220\n842     4.2682927\n843    14.9512195\n844  -502.5121951\n845  -310.0243902\n846   403.0000000\n847  -166.9024390\n848  -257.9268293\n849    47.4878049\n850  -674.0243902\n851   186.1219512\n852    51.4390244\n853   543.1951220\n854  -253.7804878\n855   299.8292683\n856  -325.6341463\n857   -69.8292683\n858   449.4878049\n859   816.4634146\n860   283.3902439\n861  -548.5121951\n862   133.3414634\n863  -727.6829268\n864   467.4390244\n865   388.7073171\n866   439.5853659\n867  -134.9024390\n868  -624.5609756\n869   569.3902439\n870   353.0487805\n871  -530.0731707\n872   483.7317073\n873  -441.4390244\n874  -289.0487805\n875   162.8048780\n876  -209.5853659\n877  -562.1707317\n878    79.1463415\n879   357.9756098\n880  -483.9268293\n881   154.8048780\n882  -214.4146341\n883   448.9024390\n884   104.0731707\n885   -93.4878049\n886   701.2926829\n887    -1.0487805\n888  -496.7073171\n889  -692.7560976\n890   128.9024390\n891   676.2682927\n892  -251.0975610\n893   707.3414634\n894   567.3414634\n895    35.5853659\n896   295.5365854\n897   638.0731707\n898   782.0731707\n899   -88.5121951\n900  -403.3414634\n901   463.0487805\n902  -366.3658537\n903  -681.7317073\n904  -558.3658537\n905   235.6341463\n906  -226.2195122\n907  -460.0243902\n908   418.8536585\n909   -30.6585366\n910  -508.7073171\n911    55.6341463\n912    38.8048780\n913   180.6097561\n914  -206.2682927\n915   167.4878049\n916   667.3902439\n917   149.6829268\n918  -567.6341463\n919   -73.8292683\n920  -625.8292683\n921    55.3414634\n922   484.9512195\n923  -452.4634146\n924  -271.4878049\n925  -469.1951220\n926   633.5853659\n927   -77.0000000\n928   -71.5853659\n929  -112.5121951\n930   377.5853659\n931  -272.9024390\n932  -338.6097561\n933   714.5609756\n934   394.4146341\n935   157.0487805\n936  -264.6585366\n937  -762.9512195\n938    95.1951220\n939   569.4878049\n940   563.5365854\n941   779.6341463\n942   524.4634146\n943  -581.1951220\n944   587.5853659\n945   152.9024390\n946  -757.8780488\n947    44.3658537\n948  -102.8536585\n949   -80.4146341\n950  -108.8048780\n951  -606.2195122\n952  -777.4878049\n953   674.4146341\n954   428.4634146\n955   578.9512195\n956   487.5365854\n957   132.3170732\n958  -203.3414634\n959    83.0000000\n960    84.4146341\n961  -529.6341463\n962   -71.1463415\n963   139.9756098\n964  -501.1951220\n965   551.0487805\n966   505.4390244\n967   144.6097561\n968  -124.6097561\n969  -643.4390244\n970  -683.2926829\n971   -46.5121951\n972  -265.6341463\n973  -592.1707317\n974   204.0731707\n975   -49.9756098\n976    68.3170732\n977  -135.6341463\n978  -249.6341463\n979    31.8292683\n980   449.5853659\n981   447.2439024\n982   103.9756098\n983   468.1219512\n984   664.6585366\n985   676.5121951\n986   710.3170732\n987   -78.1707317\n988  -430.8048780\n989   551.5365854\n990    79.1951220\n991    14.4634146\n992     9.4878049\n993   569.5853659\n994   151.7317073\n995     2.3658537\n996  -529.4878049\n997   397.8780488\n998   -80.9512195\n999   103.2926829\n1000  -53.4878049\n```\n\n\n:::\n:::\n\n\nThe results of the permutation test display 1,000 shuffled differences in mean spending between males and females. These differences have both positive and negative values. The negative values indicate cases where, after shuffling, the group representing females had higher average spending, while the positive values indicate that the male group had higher average spending in the shuffled data.\n\n### Plotting the results of the Permutation Test\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_histogram(~ diffmean, data = perm_test_result, fill = \"lightblue\", binwidth = 5) %>%\n  gf_labs(\n    title = \"Permutation Test for Difference in Spending\",\n    subtitle = \"Permutation Distribution of Mean Spending Differences\",\n    x = \"Difference in Mean Spending (Rupees)\",\n    y = \"Frequency\"\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nThe plot of the permutation test results shows the distribution of 1,000 differences in mean spending between males and females after randomly shuffling group labels. The differences range from approximately **-350** to **+800** rupees, with the most frequent differences clustering around zero. This suggests that, under random shuffling, the difference in mean spending is often small and distributed symmetrically around zero, indicating no strong directional bias between the two groups.\n\n### The observed difference in means\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobserved_diff <- diffmean(`Money Spent` ~ Gender, data = spending_modified)\nobserved_diff\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n diffmean \n-55.29268 \n```\n\n\n:::\n:::\n\n\nThe observed difference in mean spending between males and females is approximately **-55.29 rupees**, indicating that, on average, females spent slightly more than males. This negative value suggests a small difference in spending behaviour, but it is relatively modest.\n\n### Calculating the p-value\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_value <- prop(~ (abs(diffmean) >= abs(observed_diff)), data = perm_test_result)\np_value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nprop_TRUE \n    0.889 \n```\n\n\n:::\n:::\n\n\nThe permutation test resulted in a **p-value of 0.871**, indicating that there is an 87.1% probability that the observed difference in mean spending between males and females (approximately -55.29 rupees) could occur by random chance. Given this high p-value, we fail to reject the null hypothesis, which suggests that there is no statistically significant difference in spending behaviour between males and females in this dataset. In other words, the observed difference is not extreme enough to conclude that the two groups spend differently at a statistically significant level.\n\n### Summary of Results for the Spending Behaviour Research Experiment\n\nThe research experiment aimed to determine if there was a significant difference in spending behavior between male and female students at MAHE Bengaluru. The following statistical tests were conducted:\n\n1.  **Two-Sample t-Test (Welch’s t-test)**:\n\n    -   The two-sample t-test comparing the mean spending between males and females resulted in a **p-value of 0.8925**. This indicates no statistically significant difference in the average spending between the two groups, as the p-value is much higher than the typical threshold of 0.05.\n\n2.  **Wilcoxon Signed-Rank Test**:\n\n    -   The Wilcoxon test, a non-parametric alternative to the t-test, resulted in a **p-value of 0.3806**, which similarly suggests no significant difference between the two groups in terms of spending behavior. This result supports the findings of the t-test.\n\n3.  **Permutation Test**:\n\n    -   The permutation test, designed to assess the likelihood of observing the difference in spending due to random chance, resulted in a **p-value of 0.871**. This further confirms that the observed difference in mean spending of approximately -55.29 rupees (females spending slightly more than males on average) is likely due to random variation and not a true underlying difference in spending behaviour.\n\n### Conclusion:\n\nBased on the results of these tests, there is no evidence to suggest that males and females differ significantly in terms of spending behaviour in this dataset. The high p-values across all tests indicate that the observed differences in mean spending are likely due to chance, and we cannot conclude that gender has a significant impact on spending in this sample. Therefore, the initial hypothesis that males might spend more than females (or vice versa) is not supported by the data.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}