<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Khushi">

<title>Data-As-Material - Assignment 2 - Part 3</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Data-As-Material</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Assignment 2 - Part 3</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Khushi </p>
            </div>
    </div>
      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>This is Part 3 of Assignment 2.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'mosaic':
  method                           from   
  fortify.SpatialPolygonsDataFrame ggplot2

The 'mosaic' package masks several functions from core packages in order to add 
additional features.  The original behavior of these functions should not be affected by this.

Attaching package: 'mosaic'

The following object is masked from 'package:Matrix':

    mean

The following objects are masked from 'package:dplyr':

    count, do, tally

The following object is masked from 'package:purrr':

    cross

The following object is masked from 'package:ggplot2':

    stat

The following objects are masked from 'package:stats':

    binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,
    quantile, sd, t.test, var

The following objects are masked from 'package:base':

    max, mean, min, prod, range, sample, sum</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'skimr'

The following object is masked from 'package:mosaic':

    n_missing</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggformula)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(correlation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'correlation'

The following object is masked from 'package:mosaic':

    cor_test</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="dataset---heptathlon" class="level3">
<h3 class="anchored" data-anchor-id="dataset---heptathlon">Dataset - heptathlon</h3>
<p>This is a dataset pertaining to scores of multiple athletes in the 7 events that make up the Heptathlon.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(HSAUR)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: tools</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>heptathlon</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    hurdles highjump  shot run200m longjump javelin run800m
Joyner-Kersee (USA)   12.69     1.86 15.80   22.56     7.27   45.66  128.51
John (GDR)            12.85     1.80 16.23   23.65     6.71   42.56  126.12
Behmer (GDR)          13.20     1.83 14.20   23.10     6.68   44.54  124.20
Sablovskaite (URS)    13.61     1.80 15.23   23.92     6.25   42.78  132.24
Choubenkova (URS)     13.51     1.74 14.76   23.93     6.32   47.46  127.90
Schulz (GDR)          13.75     1.83 13.50   24.65     6.33   42.82  125.79
Fleming (AUS)         13.38     1.80 12.88   23.59     6.37   40.28  132.54
Greiner (USA)         13.55     1.80 14.13   24.48     6.47   38.00  133.65
Lajbnerova (CZE)      13.63     1.83 14.28   24.86     6.11   42.20  136.05
Bouraga (URS)         13.25     1.77 12.62   23.59     6.28   39.06  134.74
Wijnsma (HOL)         13.75     1.86 13.01   25.03     6.34   37.86  131.49
Dimitrova (BUL)       13.24     1.80 12.88   23.59     6.37   40.28  132.54
Scheider (SWI)        13.85     1.86 11.58   24.87     6.05   47.50  134.93
Braun (FRG)           13.71     1.83 13.16   24.78     6.12   44.58  142.82
Ruotsalainen (FIN)    13.79     1.80 12.32   24.61     6.08   45.44  137.06
Yuping (CHN)          13.93     1.86 14.21   25.00     6.40   38.60  146.67
Hagger (GB)           13.47     1.80 12.75   25.47     6.34   35.76  138.48
Brown (USA)           14.07     1.83 12.69   24.83     6.13   44.34  146.43
Mulliner (GB)         14.39     1.71 12.68   24.92     6.10   37.76  138.02
Hautenauve (BEL)      14.04     1.77 11.81   25.61     5.99   35.68  133.90
Kytola (FIN)          14.31     1.77 11.66   25.69     5.75   39.48  133.35
Geremias (BRA)        14.23     1.71 12.95   25.50     5.50   39.64  144.02
Hui-Ing (TAI)         14.85     1.68 10.00   25.23     5.47   39.14  137.30
Jeong-Mi (KOR)        14.53     1.71 10.83   26.61     5.50   39.26  139.17
Launa (PNG)           16.42     1.50 11.78   26.16     4.88   46.38  163.43
                    score
Joyner-Kersee (USA)  7291
John (GDR)           6897
Behmer (GDR)         6858
Sablovskaite (URS)   6540
Choubenkova (URS)    6540
Schulz (GDR)         6411
Fleming (AUS)        6351
Greiner (USA)        6297
Lajbnerova (CZE)     6252
Bouraga (URS)        6252
Wijnsma (HOL)        6205
Dimitrova (BUL)      6171
Scheider (SWI)       6137
Braun (FRG)          6109
Ruotsalainen (FIN)   6101
Yuping (CHN)         6087
Hagger (GB)          5975
Brown (USA)          5972
Mulliner (GB)        5746
Hautenauve (BEL)     5734
Kytola (FIN)         5686
Geremias (BRA)       5508
Hui-Ing (TAI)        5290
Jeong-Mi (KOR)       5289
Launa (PNG)          4566</code></pre>
</div>
</div>
<p>The dataset contains performance metrics for various athletes across different disciplines that make up the Heptathlon event. The columns include measurements for hurdles, high jump, shot put, 200m run, long jump, javelin, 800m run, and the total score. Athletes are identified by their names and nationalities, and their scores in each event are displayed. For example, Joyner-Kersee leads with a score of 7291 points, achieving the best times and distances across several events, including hurdles, high jump, and long jump.</p>
</section>
<section id="first-10-rows-of-the-heptathlon-dataset" class="level3">
<h3 class="anchored" data-anchor-id="first-10-rows-of-the-heptathlon-dataset">First 10 rows of the Heptathlon dataset</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>heptathlon <span class="sc">%&gt;%</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    hurdles highjump  shot run200m longjump javelin run800m
Joyner-Kersee (USA)   12.69     1.86 15.80   22.56     7.27   45.66  128.51
John (GDR)            12.85     1.80 16.23   23.65     6.71   42.56  126.12
Behmer (GDR)          13.20     1.83 14.20   23.10     6.68   44.54  124.20
Sablovskaite (URS)    13.61     1.80 15.23   23.92     6.25   42.78  132.24
Choubenkova (URS)     13.51     1.74 14.76   23.93     6.32   47.46  127.90
Schulz (GDR)          13.75     1.83 13.50   24.65     6.33   42.82  125.79
Fleming (AUS)         13.38     1.80 12.88   23.59     6.37   40.28  132.54
Greiner (USA)         13.55     1.80 14.13   24.48     6.47   38.00  133.65
Lajbnerova (CZE)      13.63     1.83 14.28   24.86     6.11   42.20  136.05
Bouraga (URS)         13.25     1.77 12.62   23.59     6.28   39.06  134.74
                    score
Joyner-Kersee (USA)  7291
John (GDR)           6897
Behmer (GDR)         6858
Sablovskaite (URS)   6540
Choubenkova (URS)    6540
Schulz (GDR)         6411
Fleming (AUS)        6351
Greiner (USA)        6297
Lajbnerova (CZE)     6252
Bouraga (URS)        6252</code></pre>
</div>
</div>
<p>The first 10 rows of the heptathlon dataset show the performances of athletes across various events. The columns include data for hurdles, high jump, shot put, 200m run, long jump, javelin throw, 800m run, and the total score. For example, Joyner-Kersee (USA) leads the list with a total score of 7291 points, excelling in the 200m run, hurdles, and long jump. Other athletes, such as John and Behmer from GDR, follow closely with scores of 6897 and 6858, respectively, also showing strong performances across events like shot put and high jump. Each row represents an athlete’s results across all seven heptathlon events, culminating in their final score.</p>
</section>
<section id="glimpse---heptathlon" class="level3">
<h3 class="anchored" data-anchor-id="glimpse---heptathlon">Glimpse - Heptathlon</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(heptathlon)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 25
Columns: 8
$ hurdles  &lt;dbl&gt; 12.69, 12.85, 13.20, 13.61, 13.51, 13.75, 13.38, 13.55, 13.63…
$ highjump &lt;dbl&gt; 1.86, 1.80, 1.83, 1.80, 1.74, 1.83, 1.80, 1.80, 1.83, 1.77, 1…
$ shot     &lt;dbl&gt; 15.80, 16.23, 14.20, 15.23, 14.76, 13.50, 12.88, 14.13, 14.28…
$ run200m  &lt;dbl&gt; 22.56, 23.65, 23.10, 23.92, 23.93, 24.65, 23.59, 24.48, 24.86…
$ longjump &lt;dbl&gt; 7.27, 6.71, 6.68, 6.25, 6.32, 6.33, 6.37, 6.47, 6.11, 6.28, 6…
$ javelin  &lt;dbl&gt; 45.66, 42.56, 44.54, 42.78, 47.46, 42.82, 40.28, 38.00, 42.20…
$ run800m  &lt;dbl&gt; 128.51, 126.12, 124.20, 132.24, 127.90, 125.79, 132.54, 133.6…
$ score    &lt;int&gt; 7291, 6897, 6858, 6540, 6540, 6411, 6351, 6297, 6252, 6252, 6…</code></pre>
</div>
</div>
<p>The glimpse of the heptathlon dataset provides an overview of 25 rows and 8 columns, showcasing athletes’ performances across various events.</p>
</section>
<section id="inspect---heptathlon" class="level3">
<h3 class="anchored" data-anchor-id="inspect---heptathlon">Inspect - Heptathlon</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">inspect</span>(heptathlon)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
quantitative variables:  
      name   class     min      Q1  median      Q3     max      mean
1  hurdles numeric   12.69   13.47   13.75   14.07   16.42   13.8400
2 highjump numeric    1.50    1.77    1.80    1.83    1.86    1.7820
3     shot numeric   10.00   12.32   12.88   14.20   16.23   13.1176
4  run200m numeric   22.56   23.92   24.83   25.23   26.61   24.6492
5 longjump numeric    4.88    6.05    6.25    6.37    7.27    6.1524
6  javelin numeric   35.68   39.06   40.28   44.54   47.50   41.4824
7  run800m numeric  124.20  132.24  134.74  138.48  163.43  136.0540
8    score integer 4566.00 5746.00 6137.00 6351.00 7291.00 6090.6000
            sd  n missing
1   0.73664781 25       0
2   0.07794229 25       0
3   1.49188438 25       0
4   0.96955712 25       0
5   0.47421233 25       0
6   3.54565612 25       0
7   8.29108809 25       0
8 568.46972948 25       0</code></pre>
</div>
</div>
<p>The inspection of the heptathlon dataset reveals important summary statistics for each event. The dataset has 25 entries with no missing data. The hurdles times range from 12.69 to 16.42 seconds, with a median of 13.75 seconds. High jump heights range from 1.50 to 1.86 meters, with a median of 1.80 meters. Shot put distances vary between 10.00 and 16.23 meters, and the median distance is 12.88 meters. For the 200m run, the times range from 22.56 to 26.61 seconds, with a median of 24.83 seconds. Long jump distances range from 4.88 to 7.27 meters. The javelin throw distances span from 35.68 to 47.50 meters, while the 800m run times range between 124.20 and 163.43 seconds. The total score varies widely, from 4566 to 7291 points, with a mean score of 6090.</p>
</section>
<section id="skim---heptathlon" class="level3">
<h3 class="anchored" data-anchor-id="skim---heptathlon">Skim - Heptathlon</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(heptathlon)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">heptathlon</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">hurdles</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">13.84</td>
<td style="text-align: right;">0.74</td>
<td style="text-align: right;">12.69</td>
<td style="text-align: right;">13.47</td>
<td style="text-align: right;">13.75</td>
<td style="text-align: right;">14.07</td>
<td style="text-align: right;">16.42</td>
<td style="text-align: left;">▃▇▃▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">highjump</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.78</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">1.50</td>
<td style="text-align: right;">1.77</td>
<td style="text-align: right;">1.80</td>
<td style="text-align: right;">1.83</td>
<td style="text-align: right;">1.86</td>
<td style="text-align: left;">▁▁▂▂▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">shot</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">13.12</td>
<td style="text-align: right;">1.49</td>
<td style="text-align: right;">10.00</td>
<td style="text-align: right;">12.32</td>
<td style="text-align: right;">12.88</td>
<td style="text-align: right;">14.20</td>
<td style="text-align: right;">16.23</td>
<td style="text-align: left;">▂▃▇▃▂</td>
</tr>
<tr class="even">
<td style="text-align: left;">run200m</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">24.65</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">22.56</td>
<td style="text-align: right;">23.92</td>
<td style="text-align: right;">24.83</td>
<td style="text-align: right;">25.23</td>
<td style="text-align: right;">26.61</td>
<td style="text-align: left;">▂▆▇▇▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">longjump</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6.15</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: right;">4.88</td>
<td style="text-align: right;">6.05</td>
<td style="text-align: right;">6.25</td>
<td style="text-align: right;">6.37</td>
<td style="text-align: right;">7.27</td>
<td style="text-align: left;">▁▃▇▇▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">javelin</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">41.48</td>
<td style="text-align: right;">3.55</td>
<td style="text-align: right;">35.68</td>
<td style="text-align: right;">39.06</td>
<td style="text-align: right;">40.28</td>
<td style="text-align: right;">44.54</td>
<td style="text-align: right;">47.50</td>
<td style="text-align: left;">▅▇▂▅▅</td>
</tr>
<tr class="odd">
<td style="text-align: left;">run800m</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">136.05</td>
<td style="text-align: right;">8.29</td>
<td style="text-align: right;">124.20</td>
<td style="text-align: right;">132.24</td>
<td style="text-align: right;">134.74</td>
<td style="text-align: right;">138.48</td>
<td style="text-align: right;">163.43</td>
<td style="text-align: left;">▃▇▂▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">score</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6090.60</td>
<td style="text-align: right;">568.47</td>
<td style="text-align: right;">4566.00</td>
<td style="text-align: right;">5746.00</td>
<td style="text-align: right;">6137.00</td>
<td style="text-align: right;">6351.00</td>
<td style="text-align: right;">7291.00</td>
<td style="text-align: left;">▁▂▇▆▂</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The skim summary of the heptathlon dataset provides key statistical insights into the eight numeric variables. The dataset contains 25 rows and no missing data. For each variable, the mean, standard deviation (sd), and percentiles (p0, p25, p50, p75, p100) are shown. For example, the hurdles event has a mean of 13.84 seconds with a standard deviation of 0.74, and the scores range from 12.69 to 16.42 seconds. Similarly, the high jump has a mean of 1.78 meters with a low standard deviation of 0.08. The score column has a broad range from 4566 to 7291 points, with a mean score of 6090. These statistics offer an overview of how the athletes’ performances are distributed across the different events.</p>
</section>
<section id="data-dictionary" class="level3">
<h3 class="anchored" data-anchor-id="data-dictionary">Data Dictionary</h3>
<p><strong>Quantitative Data:</strong></p>
<ul>
<li><p><strong>hurdles (dbl):</strong> The time (in seconds) taken to complete the 100m hurdles event.</p></li>
<li><p><strong>highjump (dbl):</strong> The height (in meters) cleared in the high jump event.</p></li>
<li><p><strong>shot (dbl):</strong> The distance (in meters) achieved in the shot put event.</p></li>
<li><p><strong>run200m (dbl):</strong> The time (in seconds) taken to complete the 200m sprint.</p></li>
<li><p><strong>longjump (dbl):</strong> The distance (in meters) achieved in the long jump event.</p></li>
<li><p><strong>javelin (dbl):</strong> The distance (in meters) achieved in the javelin throw event.</p></li>
<li><p><strong>run800m (dbl):</strong> The time (in seconds) taken to complete the 800m run.</p></li>
<li><p><strong>score (int):</strong> The total score accumulated from all the events for each athlete.</p></li>
</ul>
<p><strong>Qualitative Data:</strong></p>
<ul>
<li><strong>name (chr):</strong> The name of the athlete participating in the heptathlon competition.</li>
</ul>
</section>
<section id="target-variable" class="level3">
<h3 class="anchored" data-anchor-id="target-variable">Target Variable</h3>
<p><strong>Score</strong></p>
<p>The score is the key outcome of interest in the heptathlon dataset as it represents the cumulative performance of athletes across all events. The goal of the analysis is to understand how each individual event contributes to the overall score. This makes the score the most logical target variable for evaluating the athletes’ success across the seven heptathlon events.</p>
</section>
<section id="predictor-variables" class="level3">
<h3 class="anchored" data-anchor-id="predictor-variables">Predictor Variables</h3>
<ul>
<li><strong>Hurdles</strong></li>
</ul>
<p>The time taken to complete the 100m hurdles event is a critical factor in determining an athlete’s score. Faster times typically translate into higher scores, making hurdles an important predictor of the overall performance.</p>
<ul>
<li><strong>High Jump</strong></li>
</ul>
<p>The height an athlete clears in the high jump event significantly contributes to their score. Higher jumps generally result in more points, making it a valuable predictor for the overall score.</p>
<ul>
<li><strong>Shot Put</strong></li>
</ul>
<p>The distance achieved in the shot put event is another factor that influences the total score. Longer throws result in higher points, making this event a crucial predictor of an athlete’s overall performance.</p>
<ul>
<li><strong>200m Sprint</strong></li>
</ul>
<p>The time taken to complete the 200m sprint is an essential measure of an athlete’s speed and stamina. Faster times contribute to higher scores, making the 200m sprint an important predictor variable.</p>
<ul>
<li><strong>Long Jump</strong></li>
</ul>
<p>The distance jumped in the long jump event provides another key input into the total score. Longer jumps generally lead to higher scores, making it an influential predictor.</p>
<ul>
<li><strong>Javelin Throw</strong></li>
</ul>
<p>The distance achieved in the javelin throw event plays a role in determining the athlete’s score. Longer throws result in more points, making this an important predictor for the final score.</p>
<ul>
<li><strong>800m Run</strong></li>
</ul>
<p>The time taken to complete the 800m run is a measure of endurance and speed. Faster times contribute to higher scores, making the 800m run a significant predictor of the overall score.</p>
</section>
<section id="research-experiment-for-the-heptathlon-dataset" class="level3">
<h3 class="anchored" data-anchor-id="research-experiment-for-the-heptathlon-dataset">Research Experiment for the Heptathlon Dataset</h3>
<p>The primary objective of the research experiment could be to measure and evaluate the athletic performance of multiple athletes competing in the heptathlon, a multi-event track and field competition. The goal might have been to assess how individual event performances contribute to the overall score, providing insights into which events could be most predictive of an athlete’s cumulative success.</p>
<section id="hypothesis" class="level4">
<h4 class="anchored" data-anchor-id="hypothesis"><strong>Hypothesis:</strong></h4>
<p>The experiment could have been designed to test the hypothesis that certain events (e.g., long jump, 200m sprint) would have a stronger correlation with the overall score than others (e.g., shot put or javelin throw).</p>
</section>
<section id="participants" class="level4">
<h4 class="anchored" data-anchor-id="participants"><strong>Participants:</strong></h4>
<ul>
<li><p><strong>Subjects:</strong> 25 female athletes who participated in an international heptathlon competition, possibly at a world-class event such as the Olympics or World Championships.</p></li>
<li><p><strong>Selection Criteria:</strong> Athletes could have been selected based on their qualification to compete in the heptathlon, likely elite athletes with prior experience and high skill levels across the seven events.</p></li>
</ul>
</section>
<section id="methodology" class="level4">
<h4 class="anchored" data-anchor-id="methodology"><strong>Methodology:</strong></h4>
<ol type="1">
<li><p><strong>Data Collection Procedure:</strong></p>
<ul>
<li><p>The athletes participated in <strong>seven heptathlon events</strong>, which took place over two days:</p>
<ol type="1">
<li><p>100m hurdles</p></li>
<li><p>High jump</p></li>
<li><p>Shot put</p></li>
<li><p>200m sprint</p></li>
<li><p>Long jump</p></li>
<li><p>Javelin throw</p></li>
<li><p>800m run</p></li>
</ol></li>
<li><p>Each event was measured precisely using standard procedures. For example:</p>
<ul>
<li><p><strong>Times</strong> for hurdles, 200m sprint, and 800m run were measured using electronic timing systems.</p></li>
<li><p><strong>Distances</strong> for shot put, long jump, and javelin throw were measured using precise distance-measuring equipment.</p></li>
<li><p><strong>Heights</strong> for the high jump were measured using high-precision tools to ensure accuracy.</p></li>
</ul></li>
</ul></li>
<li><p><strong>Data Recording:</strong></p>
<ul>
<li><p>The performance of each athlete in each event was recorded. This included:</p>
<ul>
<li><p>Time (in seconds) for the sprint events (100m hurdles, 200m sprint, 800m run).</p></li>
<li><p>Distance (in meters) for throwing and jumping events (shot put, long jump, javelin throw).</p></li>
<li><p>Height (in meters) for the high jump.</p></li>
<li><p>The results for each event were converted into points using <strong>IAAF Heptathlon Scoring Tables</strong> (standard scoring guidelines used in heptathlon). The points for each event were summed to obtain the <strong>total score</strong> for each athlete.</p></li>
</ul></li>
</ul></li>
</ol>
<p><strong>Controlled Variables:</strong></p>
<ul>
<li><p>Environmental factors such as <strong>weather conditions</strong> (e.g., wind speed, temperature) that could influence performance might have been controlled or recorded to ensure fairness.</p></li>
<li><p><strong>Equipment</strong> used for measurements (e.g., electronic timers, measuring tapes) could have been standardized across all athletes to avoid bias in data collection.</p></li>
<li><p>The <strong>same scoring system</strong> (IAAF scoring tables) was applied consistently to convert performance results into points.</p></li>
</ul>
<p><strong>Data Analysis:</strong></p>
<ul>
<li><p>The researchers analyzed how performance in each of the seven events contributed to the athletes’ overall score.</p></li>
<li><p><strong>Correlation analysis</strong> was likely conducted to assess which events had the most significant impact on the overall score.</p></li>
<li><p>Statistical techniques such as <strong>linear regression</strong> may have been used to predict the overall score based on the athletes’ individual performances.</p></li>
</ul>
</section>
</section>
<section id="correlation-tests---attempt-1" class="level3">
<h3 class="anchored" data-anchor-id="correlation-tests---attempt-1">Correlation Tests - Attempt 1</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>highjump_cor <span class="ot">&lt;-</span> mosaic<span class="sc">::</span><span class="fu">cor_test</span>(heptathlon<span class="sc">$</span>highjump <span class="sc">~</span> heptathlon<span class="sc">$</span>score)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>shot_cor <span class="ot">&lt;-</span> mosaic<span class="sc">::</span><span class="fu">cor_test</span>(heptathlon<span class="sc">$</span>shot <span class="sc">~</span> heptathlon<span class="sc">$</span>score)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>run200m_cor <span class="ot">&lt;-</span> mosaic<span class="sc">::</span><span class="fu">cor_test</span>(heptathlon<span class="sc">$</span>run200m <span class="sc">~</span> heptathlon<span class="sc">$</span>score)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>longjump_cor <span class="ot">&lt;-</span> mosaic<span class="sc">::</span><span class="fu">cor_test</span>(heptathlon<span class="sc">$</span>longjump <span class="sc">~</span> heptathlon<span class="sc">$</span>score)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>javelin_cor <span class="ot">&lt;-</span> mosaic<span class="sc">::</span><span class="fu">cor_test</span>(heptathlon<span class="sc">$</span>javelin <span class="sc">~</span> heptathlon<span class="sc">$</span>score)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>run800m_cor <span class="ot">&lt;-</span> mosaic<span class="sc">::</span><span class="fu">cor_test</span>(heptathlon<span class="sc">$</span>run800m <span class="sc">~</span> heptathlon<span class="sc">$</span>score)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>(highjump_cor),</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>(shot_cor),</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>(run200m_cor),</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>(longjump_cor),</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>(javelin_cor),</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>(run800m_cor)</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">predictor =</span> <span class="fu">c</span>(<span class="st">"highjump"</span>, <span class="st">"shot"</span>, <span class="st">"run200m"</span>, <span class="st">"longjump"</span>, <span class="st">"javelin"</span>, <span class="st">"run800m"</span>))</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>  results,</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">digits =</span> <span class="dv">2</span>,</span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Correlation between Heptathlon Score and Predictor Variables"</span></span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Correlation between Heptathlon Score and Predictor Variables</caption>
<colgroup>
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 32%">
<col style="width: 10%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">parameter</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
<th style="text-align: left;">method</th>
<th style="text-align: left;">alternative</th>
<th style="text-align: left;">predictor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.77</td>
<td style="text-align: right;">5.74</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">0.53</td>
<td style="text-align: right;">0.89</td>
<td style="text-align: left;">Pearson’s product-moment correlation</td>
<td style="text-align: left;">two.sided</td>
<td style="text-align: left;">highjump</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.80</td>
<td style="text-align: right;">6.39</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">0.59</td>
<td style="text-align: right;">0.91</td>
<td style="text-align: left;">Pearson’s product-moment correlation</td>
<td style="text-align: left;">two.sided</td>
<td style="text-align: left;">shot</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-0.86</td>
<td style="text-align: right;">-8.26</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-0.94</td>
<td style="text-align: right;">-0.71</td>
<td style="text-align: left;">Pearson’s product-moment correlation</td>
<td style="text-align: left;">two.sided</td>
<td style="text-align: left;">run200m</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">14.66</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">0.89</td>
<td style="text-align: right;">0.98</td>
<td style="text-align: left;">Pearson’s product-moment correlation</td>
<td style="text-align: left;">two.sided</td>
<td style="text-align: left;">longjump</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">1.25</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-0.16</td>
<td style="text-align: right;">0.59</td>
<td style="text-align: left;">Pearson’s product-moment correlation</td>
<td style="text-align: left;">two.sided</td>
<td style="text-align: left;">javelin</td>
</tr>
<tr class="even">
<td style="text-align: right;">-0.77</td>
<td style="text-align: right;">-5.84</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-0.89</td>
<td style="text-align: right;">-0.54</td>
<td style="text-align: left;">Pearson’s product-moment correlation</td>
<td style="text-align: left;">two.sided</td>
<td style="text-align: left;">run800m</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="attempt-2" class="level3">
<h3 class="anchored" data-anchor-id="attempt-2">Attempt 2</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>highjump_cor <span class="ot">&lt;-</span> mosaic<span class="sc">::</span><span class="fu">cor_test</span>(heptathlon<span class="sc">$</span>highjump <span class="sc">~</span> heptathlon<span class="sc">$</span>score)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>shot_cor <span class="ot">&lt;-</span> mosaic<span class="sc">::</span><span class="fu">cor_test</span>(heptathlon<span class="sc">$</span>shot <span class="sc">~</span> heptathlon<span class="sc">$</span>score)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>run200m_cor <span class="ot">&lt;-</span> mosaic<span class="sc">::</span><span class="fu">cor_test</span>(heptathlon<span class="sc">$</span>run200m <span class="sc">~</span> heptathlon<span class="sc">$</span>score)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>longjump_cor <span class="ot">&lt;-</span> mosaic<span class="sc">::</span><span class="fu">cor_test</span>(heptathlon<span class="sc">$</span>longjump <span class="sc">~</span> heptathlon<span class="sc">$</span>score)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>javelin_cor <span class="ot">&lt;-</span> mosaic<span class="sc">::</span><span class="fu">cor_test</span>(heptathlon<span class="sc">$</span>javelin <span class="sc">~</span> heptathlon<span class="sc">$</span>score)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>run800m_cor <span class="ot">&lt;-</span> mosaic<span class="sc">::</span><span class="fu">cor_test</span>(heptathlon<span class="sc">$</span>run800m <span class="sc">~</span> heptathlon<span class="sc">$</span>score)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>(highjump_cor),</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>(shot_cor),</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>(run200m_cor),</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>(longjump_cor),</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>(javelin_cor),</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>(run800m_cor)</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">predictor =</span> <span class="fu">c</span>(<span class="st">"highjump"</span>, <span class="st">"shot"</span>, <span class="st">"run200m"</span>, <span class="st">"longjump"</span>, <span class="st">"javelin"</span>, <span class="st">"run800m"</span>))</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> results <span class="sc">%&gt;%</span></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(predictor, <span class="fu">everything</span>())  <span class="co"># Moves 'predictor' to the first position</span></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>  results,</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">digits =</span> <span class="dv">2</span>,</span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Correlation between Heptathlon Score and Predictor Variables"</span></span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Correlation between Heptathlon Score and Predictor Variables</caption>
<colgroup>
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 32%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">predictor</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">parameter</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
<th style="text-align: left;">method</th>
<th style="text-align: left;">alternative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">highjump</td>
<td style="text-align: right;">0.77</td>
<td style="text-align: right;">5.74</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">0.53</td>
<td style="text-align: right;">0.89</td>
<td style="text-align: left;">Pearson’s product-moment correlation</td>
<td style="text-align: left;">two.sided</td>
</tr>
<tr class="even">
<td style="text-align: left;">shot</td>
<td style="text-align: right;">0.80</td>
<td style="text-align: right;">6.39</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">0.59</td>
<td style="text-align: right;">0.91</td>
<td style="text-align: left;">Pearson’s product-moment correlation</td>
<td style="text-align: left;">two.sided</td>
</tr>
<tr class="odd">
<td style="text-align: left;">run200m</td>
<td style="text-align: right;">-0.86</td>
<td style="text-align: right;">-8.26</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-0.94</td>
<td style="text-align: right;">-0.71</td>
<td style="text-align: left;">Pearson’s product-moment correlation</td>
<td style="text-align: left;">two.sided</td>
</tr>
<tr class="even">
<td style="text-align: left;">longjump</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">14.66</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">0.89</td>
<td style="text-align: right;">0.98</td>
<td style="text-align: left;">Pearson’s product-moment correlation</td>
<td style="text-align: left;">two.sided</td>
</tr>
<tr class="odd">
<td style="text-align: left;">javelin</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">1.25</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-0.16</td>
<td style="text-align: right;">0.59</td>
<td style="text-align: left;">Pearson’s product-moment correlation</td>
<td style="text-align: left;">two.sided</td>
</tr>
<tr class="even">
<td style="text-align: left;">run800m</td>
<td style="text-align: right;">-0.77</td>
<td style="text-align: right;">-5.84</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-0.89</td>
<td style="text-align: right;">-0.54</td>
<td style="text-align: left;">Pearson’s product-moment correlation</td>
<td style="text-align: left;">two.sided</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Here, I reordered the columns to make predictor the first column.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>cor_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">event =</span> <span class="fu">c</span>(<span class="st">"highjump"</span>, <span class="st">"shot"</span>, <span class="st">"run200m"</span>, <span class="st">"longjump"</span>, <span class="st">"javelin"</span>, <span class="st">"run800m"</span>),</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">correlation =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.8114</span>, <span class="sc">-</span><span class="fl">0.6513</span>, <span class="fl">0.7737</span>, <span class="sc">-</span><span class="fl">0.9121</span>, <span class="sc">-</span><span class="fl">0.00776</span>, <span class="fl">0.7793</span>),</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">CI_low =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.9136</span>, <span class="sc">-</span><span class="fl">0.8323</span>, <span class="fl">0.5453</span>, <span class="sc">-</span><span class="fl">0.9609</span>, <span class="sc">-</span><span class="fl">0.4017</span>, <span class="fl">0.5550</span>),</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">CI_high =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.6127</span>, <span class="sc">-</span><span class="fl">0.3449</span>, <span class="fl">0.8952</span>, <span class="sc">-</span><span class="fl">0.8083</span>, <span class="fl">0.3886</span>, <span class="fl">0.8979</span>),</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_value =</span> <span class="fu">c</span>(<span class="fl">8.60e-07</span>, <span class="fl">4.21e-04</span>, <span class="fl">5.72e-06</span>, <span class="fl">2.21e-10</span>, <span class="fl">9.71e-01</span>, <span class="fl">4.43e-06</span>)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>cor_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     event correlation  CI_low CI_high  p_value
1 highjump    -0.81140 -0.9136 -0.6127 8.60e-07
2     shot    -0.65130 -0.8323 -0.3449 4.21e-04
3  run200m     0.77370  0.5453  0.8952 5.72e-06
4 longjump    -0.91210 -0.9609 -0.8083 2.21e-10
5  javelin    -0.00776 -0.4017  0.3886 9.71e-01
6  run800m     0.77930  0.5550  0.8979 4.43e-06</code></pre>
</div>
</div>
</section>
<section id="log10" class="level3">
<h3 class="anchored" data-anchor-id="log10">Log10</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>cor_data<span class="sc">$</span>significance <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fu">log10</span>(cor_data<span class="sc">$</span>p_value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="attempt-1" class="level3">
<h3 class="anchored" data-anchor-id="attempt-1">Attempt 1</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(correlation <span class="sc">~</span> event, <span class="at">data =</span> cor_data, <span class="at">size =</span> <span class="sc">~</span>significance, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">fill =</span> <span class="st">"white"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_errorbar</span>(<span class="at">ymin =</span> <span class="sc">~</span>CI_low, <span class="at">ymax =</span> <span class="sc">~</span>CI_high, <span class="at">width =</span> <span class="fl">0.2</span>, <span class="at">data =</span> cor_data) <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"gray"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Heptathlon Scores and Correlations"</span>,</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Which Events show Correlated Scores with Hurdles?"</span>,</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Event"</span>,</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Correlation with hurdles timing in Heptathlon"</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_theme</span>(</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"right"</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="attempt-2-1" class="level3">
<h3 class="anchored" data-anchor-id="attempt-2-1">Attempt 2</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(correlation <span class="sc">~</span> event, <span class="at">data =</span> cor_data, <span class="at">size =</span> <span class="sc">~</span>significance, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">fill =</span> <span class="st">"white"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_errorbar</span>(<span class="at">ymin =</span> <span class="sc">~</span>CI_low, <span class="at">ymax =</span> <span class="sc">~</span>CI_high, <span class="at">width =</span> <span class="fl">0.2</span>, <span class="at">data =</span> cor_data) <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"gray"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Heptathlon Scores and Correlations"</span>,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Which Events show Correlated Scores with Hurdles?"</span>,</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Significance = -log10(p.value)"</span> , </span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Event"</span>,</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Correlation with hurdles timing in Heptathlon"</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_theme</span>(</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"right"</span></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I included the caption in this attempt.</p>
</section>
<section id="attempt-3" class="level3">
<h3 class="anchored" data-anchor-id="attempt-3">Attempt 3</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>cor_data<span class="sc">$</span>event <span class="ot">&lt;-</span> <span class="fu">factor</span>(cor_data<span class="sc">$</span>event, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"longjump"</span>, <span class="st">"highjump"</span>, <span class="st">"shot"</span>, <span class="st">"javelin"</span>, <span class="st">"run200m"</span>, <span class="st">"run800m"</span>))</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(correlation <span class="sc">~</span> event, <span class="at">data =</span> cor_data, <span class="at">size =</span> <span class="sc">~</span>significance, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">fill =</span> <span class="st">"white"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_errorbar</span>(<span class="at">ymin =</span> <span class="sc">~</span>CI_low, <span class="at">ymax =</span> <span class="sc">~</span>CI_high, <span class="at">width =</span> <span class="fl">0.2</span>, <span class="at">data =</span> cor_data) <span class="sc">%&gt;%</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"gray"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Heptathlon Scores and Correlations"</span>,</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Which Events show Correlated Scores with Hurdles?"</span>,</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Significance = -log10(p.value)"</span> , </span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Event"</span>,</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Correlation with hurdles timing in Heptathlon"</span></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_theme</span>(</span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"right"</span></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I rearranged the order of the predictor variables on the x-axis.</p>
</section>
<section id="attempt-4" class="level3">
<h3 class="anchored" data-anchor-id="attempt-4">Attempt 4</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(correlation <span class="sc">~</span> event, <span class="at">data =</span> cor_data, <span class="at">size =</span> <span class="dv">5</span>, <span class="at">shape =</span> <span class="dv">21</span>, </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">fill =</span> <span class="st">"black"</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">stroke =</span> <span class="dv">2</span>) <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_errorbar</span>(<span class="at">ymin =</span> <span class="sc">~</span>CI_low, <span class="at">ymax =</span> <span class="sc">~</span>CI_high, <span class="at">width =</span> <span class="fl">0.2</span>, <span class="at">data =</span> cor_data) <span class="sc">%&gt;%</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"gray"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Heptathlon Scores and Correlations"</span>,</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Which Events show Correlated Scores with Hurdles?"</span>,</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Significance = -log10(p.value)"</span> , </span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Event"</span>,</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Correlation with hurdles timing in Heptathlon"</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_theme</span>(</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"right"</span></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I attempted to add a white border around the points. But once I did this, I was unable to size them according to significance.</p>
</section>
<section id="final-attempt" class="level3">
<h3 class="anchored" data-anchor-id="final-attempt">Final Attempt</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(correlation <span class="sc">~</span> event, <span class="at">data =</span> cor_data, <span class="at">size =</span> <span class="sc">~</span>significance, <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">fill =</span> <span class="st">"white"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">stroke =</span> <span class="dv">2</span>) <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_errorbar</span>(<span class="at">ymin =</span> <span class="sc">~</span>CI_low, <span class="at">ymax =</span> <span class="sc">~</span>CI_high, <span class="at">width =</span> <span class="fl">0.2</span>, <span class="at">data =</span> cor_data) <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"gray"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Heptathlon Scores and Correlations"</span>,</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Which Events show Correlated Scores with Hurdles?"</span>,</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Significance = -log10(p.value)"</span> , </span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Event"</span>,</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Correlation with hurdles timing in Heptathlon"</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_theme</span>(</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"right"</span></span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I increased the stroke width of the points to make them more visible, but I was still unable to add the white border around them. Despite adjusting the stroke, the desired white border did not appear as expected.</p>
</section>
<section id="questions" class="level3">
<h3 class="anchored" data-anchor-id="questions">Questions</h3>
<p>The graph titled “Heptathlon Scores and Correlations” seeks to answer the following questions:</p>
<section id="what-is-the-relationship-between-individual-event-performances-and-the-overall-score-in-the-heptathlon" class="level4">
<h4 class="anchored" data-anchor-id="what-is-the-relationship-between-individual-event-performances-and-the-overall-score-in-the-heptathlon">1. What is the relationship between individual event performances and the overall score in the heptathlon?</h4>
<p>(The graph could aim to explore how individual event results, such as performance in the 100m hurdles or shot put, correlate with the overall score, highlighting which events have the strongest impact on the total performance.)</p>
<ul>
<li>In the dataset, it appears that events such as the 200m sprint and long jump have a strong positive correlation with the overall score, suggesting that better performance in these events significantly contributes to a higher total score. Conversely, events like shot put show a weaker correlation, indicating less influence on the overall performance.</li>
</ul>
</section>
<section id="how-do-different-event-performances-vary-among-top-performing-athletes-compared-to-lower-performing-ones" class="level4">
<h4 class="anchored" data-anchor-id="how-do-different-event-performances-vary-among-top-performing-athletes-compared-to-lower-performing-ones">2. How do different event performances vary among top-performing athletes compared to lower-performing ones?</h4>
<p>(It may seek to analyze whether top-performing athletes excel consistently across all events or if they perform particularly well in specific events, leading to higher overall scores.)</p>
<ul>
<li>The data shows that top-performing athletes tend to excel in events like the 200m sprint and hurdles, which are highly correlated with the overall score. However, there is more variability in events such as javelin and shot put, where even lower-performing athletes may achieve comparable results to their higher-ranked counterparts, indicating that these events are less crucial for determining total score.</li>
</ul>
</section>
<section id="which-events-exhibit-significant-disparities-in-correlation-with-the-overall-score" class="level4">
<h4 class="anchored" data-anchor-id="which-events-exhibit-significant-disparities-in-correlation-with-the-overall-score">3. Which events exhibit significant disparities in correlation with the overall score?</h4>
<p>(The graph could identify events where there is a strong or weak relationship between performance and overall score, helping to pinpoint the most impactful events for overall success in the heptathlon.)</p>
<ul>
<li>There is a significant disparity in the correlation of events with the overall score. For instance, the 200m sprint and long jump have a strong positive correlation with the overall score, whereas the javelin throw and shot put have weaker correlations, suggesting they are less critical for overall success in the heptathlon.</li>
</ul>
</section>
<section id="do-certain-events-show-stronger-correlations-with-the-overall-score-for-top-scoring-athletes-compared-to-lower-scoring-athletes" class="level4">
<h4 class="anchored" data-anchor-id="do-certain-events-show-stronger-correlations-with-the-overall-score-for-top-scoring-athletes-compared-to-lower-scoring-athletes">4. Do certain events show stronger correlations with the overall score for top-scoring athletes compared to lower-scoring athletes?</h4>
<p>(It may seek to explore whether certain events, such as the hurdles or high jump, have a greater impact on the overall score for top-performing athletes compared to those with lower scores.)</p>
<ul>
<li>Yes, events such as hurdles and the 800m run, which are typically associated with speed and endurance, show a stronger correlation with the overall score for top-scoring athletes. These athletes tend to perform consistently well in these events, contributing to their higher scores, while lower-scoring athletes may show more inconsistency across these events.</li>
</ul>
</section>
<section id="is-there-evidence-that-certain-events-have-a-disproportionate-influence-on-the-overall-score" class="level4">
<h4 class="anchored" data-anchor-id="is-there-evidence-that-certain-events-have-a-disproportionate-influence-on-the-overall-score">5. Is there evidence that certain events have a disproportionate influence on the overall score?</h4>
<p>(The graph could aim to determine whether specific events are more critical in determining the overall outcome, revealing whether strong performance in key events can significantly boost an athlete’s total score.)</p>
<ul>
<li>Yes, events like the 200m sprint and long jump show a disproportionate influence on the overall score, with athletes who perform well in these events often achieving much higher total scores. In contrast, events such as shot put and javelin throw seem to have a smaller influence on the total outcome, suggesting that strong performance in a few key events may be more beneficial for overall success.</li>
</ul>
</section>
</section>
<section id="additional-questions" class="level3">
<h3 class="anchored" data-anchor-id="additional-questions">Additional Questions</h3>
<section id="identify-the-type-of-charts" class="level4">
<h4 class="anchored" data-anchor-id="identify-the-type-of-charts">1. <strong>Identify the type of charts:</strong></h4>
<p>The chart is a <strong>scatter plot with error bars</strong>, specifically designed to visualize the correlation between scores in hurdles and other heptathlon events. The point sizes correspond to the significance of the correlation.</p>
</section>
<section id="identify-the-variables-used-for-various-geometrical-aspects-x-y-fill-etc." class="level4">
<h4 class="anchored" data-anchor-id="identify-the-variables-used-for-various-geometrical-aspects-x-y-fill-etc.">2. <strong>Identify the variables used for various geometrical aspects (x, y, fill, etc.):</strong></h4>
<ul>
<li><p><strong>x-axis (Event):</strong> Represents the different events in the heptathlon (e.g., high jump, shot put, javelin, etc.).</p></li>
<li><p><strong>y-axis (Correlation with hurdles score):</strong> Displays the correlation values between performance in each event and the score in hurdles.</p></li>
<li><p><strong>Fill/Shape size (Significance):</strong> The size of the points indicates the significance of the correlation (calculated as <code>-log10(p.value)</code>).</p></li>
<li><p><strong>Error bars (CI_low, CI_high):</strong> Represent the confidence intervals for the correlation values, showing the range within which the actual correlation likely falls.</p></li>
</ul>
</section>
<section id="which-events-in-the-7-event-heptathlon-are-most-highly-correlated-with-scores-in-hurdles" class="level4">
<h4 class="anchored" data-anchor-id="which-events-in-the-7-event-heptathlon-are-most-highly-correlated-with-scores-in-hurdles">3. <strong>Which events in the 7-event heptathlon are most highly correlated with scores in hurdles?</strong></h4>
<p>According to the graph, the <strong>200m sprint</strong> and <strong>800m run</strong> are the most highly correlated events with the hurdles scores, as indicated by the positive correlation values and larger significance levels. These events seem to have the strongest association with an athlete’s performance in hurdles.</p>
</section>
<section id="if-an-athlete-was-a-record-holder-in-both-high-jump-and-hurdles-what-would-be-your-opinion-about-them-justify-based-on-the-graph" class="level4">
<h4 class="anchored" data-anchor-id="if-an-athlete-was-a-record-holder-in-both-high-jump-and-hurdles-what-would-be-your-opinion-about-them-justify-based-on-the-graph">4. <strong>If an athlete was a record holder in both high jump and hurdles, what would be your opinion about them? Justify based on the graph!</strong></h4>
<p>Based on the graph, the <strong>high jump</strong> event does not show a strong correlation with hurdles performance, as its correlation value is negative and the error bars are relatively large, indicating uncertainty in the strength of the relationship. If an athlete excels in both high jump and hurdles, it would suggest they have a unique skill set, combining strong technical ability in high jump (which is less correlated with hurdles) with speed and agility in hurdles (a more significant event). This combination would make them a well-rounded and versatile athlete, excelling in both power-based and speed-based events despite the weaker connection between the two disciplines.</p>
</section>
</section>
<section id="inference-and-story-from-the-graph-and-data" class="level3">
<h3 class="anchored" data-anchor-id="inference-and-story-from-the-graph-and-data">Inference and Story from the Graph and Data</h3>
<p>The graph titled “<strong>Heptathlon Scores and Correlations</strong>” offers an insightful exploration into the relationship between the seven heptathlon events and their correlations with hurdles performance. By examining the correlation patterns across these events, we uncover key relationships that shape the athletic performance of heptathletes. This visualization provides clarity on which events significantly influence hurdles performance and sheds light on the multidimensional skills required for success in the heptathlon.</p>
<section id="key-observations" class="level4">
<h4 class="anchored" data-anchor-id="key-observations">Key Observations:</h4>
<p>From analyzing the graph and the heptathlon dataset, the following patterns emerged:</p>
<ul>
<li><p><strong>Strong Correlation with Speed-Based Events</strong>: Events like the <strong>200m sprint</strong> and <strong>800m run</strong> show the highest positive correlation with hurdles performance. This suggests that athletes who excel in hurdles tend to also perform exceptionally well in speed and endurance events. These events share common elements of speed, agility, and sustained effort, which likely explains their high correlation.</p></li>
<li><p><strong>Mixed Correlation with Field Events</strong>: The <strong>long jump</strong> shows a positive correlation with hurdles scores, suggesting that explosive power and coordination are valuable across both events. However, <strong>shot put</strong> and <strong>javelin</strong> exhibit weaker correlations with hurdles, which is expected as these events require strength and technique rather than speed, showing that different skills are necessary across the heptathlon.</p></li>
<li><p><strong>Weaker Correlation with High Jump</strong>: Surprisingly, <strong>high jump</strong> has a weaker correlation with hurdles performance. Despite requiring leg strength and explosive power, these skills do not seem to translate as directly to hurdles success, likely due to the technical nature of high jump.</p></li>
</ul>
</section>
<section id="insights-on-event-dynamics" class="level4">
<h4 class="anchored" data-anchor-id="insights-on-event-dynamics">Insights on Event Dynamics:</h4>
<p>If we were to draw conclusions from the data, it’s evident that <strong>speed-based events</strong> are the most closely related to hurdles performance. Athletes who perform well in hurdles are likely to excel in the <strong>200m sprint</strong> and <strong>800m run</strong>, emphasizing the importance of speed and endurance in the overall heptathlon score. This highlights the key role that sprinting ability plays in shaping an athlete’s overall success in this multi-discipline sport.</p>
<p>On the other hand, the <strong>field events</strong>, while important, contribute less directly to hurdles performance. The mixed correlation suggests that while events like the <strong>long jump</strong> can complement speed and agility, events such as <strong>shot put</strong> and <strong>javelin</strong> rely on entirely different skill sets that do not significantly overlap with hurdles.</p>
</section>
<section id="event-specific-insights" class="level4">
<h4 class="anchored" data-anchor-id="event-specific-insights">Event-Specific Insights:</h4>
<p>Each heptathlon event provides different insights into the correlation with hurdles performance:</p>
<ul>
<li><p><strong>Speed-Based Events (200m, 800m)</strong>: These events, which are dominated by speed, stamina, and technique, show strong positive correlations with hurdles. It’s clear that speed is a common denominator for athletes who succeed in hurdles, and mastering these events is crucial for improving overall performance in the heptathlon.</p></li>
<li><p><strong>Power-Based Events (Shot Put, Javelin)</strong>: These events require strength and technique, showing weaker correlations with hurdles. This highlights that strength-based events do not heavily influence an athlete’s hurdles performance, underscoring the need for a diverse skill set in the heptathlon.</p></li>
<li><p><strong>Mixed-Skill Events (Long Jump, High Jump)</strong>: While <strong>long jump</strong> shows some positive correlation due to the need for explosive power, <strong>high jump</strong> shows a weaker relationship, indicating that technical skill in one event doesn’t always translate directly to others.</p></li>
</ul>
</section>
<section id="the-versatile-athlete---record-holder-in-both-high-jump-and-hurdles" class="level4">
<h4 class="anchored" data-anchor-id="the-versatile-athlete---record-holder-in-both-high-jump-and-hurdles">The Versatile Athlete - Record Holder in Both High Jump and Hurdles:</h4>
<p>If an athlete were a record holder in both <strong>high jump</strong> and <strong>hurdles</strong>, they would stand out as an exceptionally versatile competitor. While the correlation between hurdles and high jump is not particularly strong according to the data, the athlete would demonstrate a rare ability to excel in both a speed-based event and a technical jumping event. This speaks to their <strong>diversity of skills</strong>—combining speed, agility, explosive power, and technical precision—making them a well-rounded and formidable athlete in the heptathlon.</p>
</section>
<section id="the-power-of-data-visualization" class="level4">
<h4 class="anchored" data-anchor-id="the-power-of-data-visualization">The Power of Data Visualization:</h4>
<p>This graph effectively highlights how different events within the heptathlon influence hurdles performance, providing valuable insights for athletes, coaches, and sports scientists. By visually representing these correlations, it becomes clear which events an athlete should prioritize to maximize their overall performance. The data underscores the importance of <strong>speed-based events</strong> and reveals that while field events play a role, they may not be as critical in determining hurdles success.</p>
<p>This visualization offers a clear path for athletes to tailor their training strategies by focusing on events that have the most significant impact on hurdles performance, ultimately improving their standing in the heptathlon.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>