{
  "hash": "57d635f8f452a84133adb8b644beced5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Day 3\"\nauthor: \"Khushi\"\n---\n\n\n## Introduction\n\nWe are working with bar graphs today.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.1     ✔ tibble    3.2.1\n✔ lubridate 1.9.3     ✔ tidyr     1.3.1\n✔ purrr     1.0.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(mosaic)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRegistered S3 method overwritten by 'mosaic':\n  method                           from   \n  fortify.SpatialPolygonsDataFrame ggplot2\n\nThe 'mosaic' package masks several functions from core packages in order to add \nadditional features.  The original behavior of these functions should not be affected by this.\n\nAttaching package: 'mosaic'\n\nThe following object is masked from 'package:Matrix':\n\n    mean\n\nThe following objects are masked from 'package:dplyr':\n\n    count, do, tally\n\nThe following object is masked from 'package:purrr':\n\n    cross\n\nThe following object is masked from 'package:ggplot2':\n\n    stat\n\nThe following objects are masked from 'package:stats':\n\n    binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,\n    quantile, sd, t.test, var\n\nThe following objects are masked from 'package:base':\n\n    max, mean, min, prod, range, sample, sum\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggformula)\nlibrary(skimr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'skimr'\n\nThe following object is masked from 'package:mosaic':\n\n    n_missing\n```\n\n\n:::\n:::\n\n\n### Look at the taxi dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntaxi <- read_csv(\"https://vincentarelbundock.github.io/Rdatasets/csv/modeldata/taxi.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 10000 Columns: 8\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (5): tip, company, local, dow, month\ndbl (3): rownames, distance, hour\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\ntaxi\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10,000 × 8\n   rownames tip   distance company                      local dow   month  hour\n      <dbl> <chr>    <dbl> <chr>                        <chr> <chr> <chr> <dbl>\n 1        1 yes      17.2  Chicago Independents         no    Thu   Feb      16\n 2        2 yes       0.88 City Service                 yes   Thu   Mar       8\n 3        3 yes      18.1  other                        no    Mon   Feb      18\n 4        4 yes      20.7  Chicago Independents         no    Mon   Apr       8\n 5        5 yes      12.2  Chicago Independents         no    Sun   Mar      21\n 6        6 yes       0.94 Sun Taxi                     yes   Sat   Apr      23\n 7        7 yes      17.5  Flash Cab                    no    Fri   Mar      12\n 8        8 yes      17.7  other                        no    Sun   Jan       6\n 9        9 yes       1.85 Taxicab Insurance Agency Llc no    Fri   Apr      12\n10       10 yes       1.47 City Service                 no    Tue   Mar      14\n# ℹ 9,990 more rows\n```\n\n\n:::\n:::\n\n\nThe taxi dataset contains 10,000 entries, detailing information about individual taxi rides. It includes whether a tip was given, the distance of the ride, the company providing the service, and whether the ride was local. Additionally, it records the day of the week, the month, and the hour the ride took place. The dataset allows for analyzing patterns in tipping, ride distances, and usage trends by time (day, month, and hour) as well as comparing performance across different taxi companies. This can provide insights into ride behaviors and preferences.\n\n### Glimpse - taxi dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(taxi)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 10,000\nColumns: 8\n$ rownames <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18…\n$ tip      <chr> \"yes\", \"yes\", \"yes\", \"yes\", \"yes\", \"yes\", \"yes\", \"yes\", \"yes\"…\n$ distance <dbl> 17.19, 0.88, 18.11, 20.70, 12.23, 0.94, 17.47, 17.67, 1.85, 1…\n$ company  <chr> \"Chicago Independents\", \"City Service\", \"other\", \"Chicago Ind…\n$ local    <chr> \"no\", \"yes\", \"no\", \"no\", \"no\", \"yes\", \"no\", \"no\", \"no\", \"no\",…\n$ dow      <chr> \"Thu\", \"Thu\", \"Mon\", \"Mon\", \"Sun\", \"Sat\", \"Fri\", \"Sun\", \"Fri\"…\n$ month    <chr> \"Feb\", \"Mar\", \"Feb\", \"Apr\", \"Mar\", \"Apr\", \"Mar\", \"Jan\", \"Apr\"…\n$ hour     <dbl> 16, 8, 18, 8, 21, 23, 12, 6, 12, 14, 18, 11, 12, 19, 17, 13, …\n```\n\n\n:::\n:::\n\n\nThis glimpse of the taxi dataset provides an overview of its 10,000 rows and 8 columns. This structure gives a clear, organized view of ride-specific information.\n\n### Inspect - taxi dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninspect(taxi)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\ncategorical variables:  \n     name     class levels     n missing\n1     tip character      2 10000       0\n2 company character      7 10000       0\n3   local character      2 10000       0\n4     dow character      7 10000       0\n5   month character      4 10000       0\n                                   distribution\n1 yes (92.1%), no (7.9%)                       \n2 other (27.1%) ...                            \n3 no (81.2%), yes (18.8%)                      \n4 Thu (19.6%), Wed (17.5%), Tue (16.3%) ...    \n5 Apr (31.8%), Mar (31.4%), Feb (20.4%) ...    \n\nquantitative variables:  \n      name   class min      Q1  median        Q3     max        mean\n1 rownames numeric   1 2500.75 5000.50 7500.2500 10000.0 5000.500000\n2 distance numeric   0    0.94    1.78   15.5625    42.3    6.224144\n3     hour numeric   0   11.00   15.00   18.0000    23.0   14.177300\n           sd     n missing\n1 2886.895680 10000       0\n2    7.381397 10000       0\n3    4.359904 10000       0\n```\n\n\n:::\n:::\n\n\nThe inspection of the taxi dataset shows that it contains 10,000 entries with both categorical and quantitative variables. The categorical variables include tip, company, local, dow (day of the week), and month, all of which are character types. For example, 92.1% of rides resulted in a tip, and 81.2% of the rides were local. The quantitative variables include rownames, distance, and hour, all of which are numeric. The distance of rides ranges from 0 to 42.3 miles, with a mean of 6.22 miles, and the hour variable represents the time of day, ranging from 0 to 23.\n\n### Skim - taxi dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nskim(taxi)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |      |\n|:------------------------|:-----|\n|Name                     |taxi  |\n|Number of rows           |10000 |\n|Number of columns        |8     |\n|_______________________  |      |\n|Column type frequency:   |      |\n|character                |5     |\n|numeric                  |3     |\n|________________________ |      |\n|Group variables          |None  |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|tip           |         0|             1|   2|   3|     0|        2|          0|\n|company       |         0|             1|   5|  28|     0|        7|          0|\n|local         |         0|             1|   2|   3|     0|        2|          0|\n|dow           |         0|             1|   3|   3|     0|        7|          0|\n|month         |         0|             1|   3|   3|     0|        4|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|    mean|      sd| p0|     p25|     p50|     p75|    p100|hist  |\n|:-------------|---------:|-------------:|-------:|-------:|--:|-------:|-------:|-------:|-------:|:-----|\n|rownames      |         0|             1| 5000.50| 2886.90|  1| 2500.75| 5000.50| 7500.25| 10000.0|▇▇▇▇▇ |\n|distance      |         0|             1|    6.22|    7.38|  0|    0.94|    1.78|   15.56|    42.3|▇▁▂▁▁ |\n|hour          |         0|             1|   14.18|    4.36|  0|   11.00|   15.00|   18.00|    23.0|▁▃▅▇▃ |\n\n\n:::\n:::\n\n\nThis summary provides a detailed breakdown of the dataset's completeness and distribution, making it well-prepared for further analysis.\n\n### Data Munging\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntaxi_modified <- taxi %>%\n  dplyr::mutate(\n    local = factor(local,\n      levels = c(\"no\", \"yes\"),\n      labels = c(\"no\", \"yes\"),\n      ordered = TRUE\n    ),\n    dow = factor(dow,\n      levels = c(\"Mon\", \"Tue\", \"Wed\", \"Thu\", \"Fri\", \"Sat\", \"Sun\"),\n      labels = c(\"Mon\", \"Tue\", \"Wed\", \"Thu\", \"Fri\", \"Sat\", \"Sun\"),\n      ordered = TRUE\n    ),\n    month = factor(month,\n      levels = c(\"Jan\", \"Feb\", \"Mar\", \"Apr\"),\n      labels = c(\"Jan\", \"Feb\", \"Mar\", \"Apr\"),\n      ordered = TRUE\n    )\n  )\nglimpse(taxi_modified)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 10,000\nColumns: 8\n$ rownames <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18…\n$ tip      <chr> \"yes\", \"yes\", \"yes\", \"yes\", \"yes\", \"yes\", \"yes\", \"yes\", \"yes\"…\n$ distance <dbl> 17.19, 0.88, 18.11, 20.70, 12.23, 0.94, 17.47, 17.67, 1.85, 1…\n$ company  <chr> \"Chicago Independents\", \"City Service\", \"other\", \"Chicago Ind…\n$ local    <ord> no, yes, no, no, no, yes, no, no, no, no, no, no, no, yes, no…\n$ dow      <ord> Thu, Thu, Mon, Mon, Sun, Sat, Fri, Sun, Fri, Tue, Tue, Sun, W…\n$ month    <ord> Feb, Mar, Feb, Apr, Mar, Apr, Mar, Jan, Apr, Mar, Mar, Apr, A…\n$ hour     <dbl> 16, 8, 18, 8, 21, 23, 12, 6, 12, 14, 18, 11, 12, 19, 17, 13, …\n```\n\n\n:::\n:::\n\n\nThis modified version of the taxi dataset includes the conversion of several variables into factors with ordered levels. Specifically, the variables local, dow, and month have been converted into factors. Each has been assigned specific ordered levels. The local variable indicates whether a ride was local (\"no\" or \"yes\"), while dow is now ordered from Monday to Sunday, and month from January to April. This change improves the dataset for analysis where the natural order of days and months is important, making it easier to perform time-based analyses or comparisons.\n\n### Plot 1A: Counts of Tips\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_bar(~tip, data = taxi_modified) %>%\n  gf_labs(title = \"Plot 1A: Counts of Tips\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# gf_labs- Metadata about the graph\n```\n:::\n\n\nThe bar chart titled \"Counts of Tips\" displays the frequency of taxi rides where a tip was given versus those where no tip was provided. The chart shows a significantly higher count of rides where a tip was given, with over 7,500 rides including a tip, compared to a much smaller count of rides without a tip, which is under 1,000. This indicates that the majority of taxi rides in this dataset included a tip.\n\n### Plot 2A: Colour Bar Chart\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntaxi_modified %>%\n  gf_bar(~tip,\n    colour = ~local,\n  ) %>%\n  gf_labs(title = \"Plot 2A: Colour Bar Chart\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# colour-outline colour\n```\n:::\n\n\nThis colour-coded bar chart titled \"Plot 2A: Colour Bar Chart\" displays the count of taxi rides where a tip was given or not, with an additional distinction based on whether the ride was local or not. The darker bars represent non-local rides, while the lighter-coloured edges represent local rides.From the chart, it is clear that the majority of taxi rides where a tip was given were non-local, as the darker colour dominates the \"yes\" category. Similarly, for rides without a tip, the majority are also non-local. There are relatively few local rides, indicated by the lighter-coloured edges, in both the tip and no-tip categories.\n\n### Plot 2B: Stacked Bar Chart\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntaxi_modified %>%\n  gf_bar(~tip,\n    fill = ~local,\n  ) %>%\n  gf_labs(title = \"Plot 2B: Stacked Bar Chart\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# fill- fill the bar with a colour or variable\n```\n:::\n\n\nThis stacked bar chart titled \"Plot 2B: Stacked Bar Chart\" shows the distribution of taxi rides based on whether a tip was given, with the additional breakdown of local and non-local rides. The purple sections represent non-local rides, while the yellow sections represent local rides. In the \"yes\" category (rides with a tip), most of the rides are non-local (purple), with a smaller portion being local (yellow). Similarly, in the \"no\" category (rides without a tip), the majority are also non-local rides.\n\n### Plot 2C: Dodged Bar Chart\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntaxi_modified %>%\n  gf_bar(~tip,\n    fill = ~local,\n    position = \"dodge\"\n  ) %>%\n  gf_labs(title = \"Plot 2C: Dodged Bar Chart\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nThis \"Dodged Bar Chart\" (Plot 2C) provides a side-by-side comparison of taxi rides where tips were given or not, categorized by whether the ride was local or non-local. The purple bars represent non-local rides, and the yellow bars represent local rides.\n\n### Plot 2D: Filled Bar Chart\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntaxi_modified %>%\n  gf_bar(~tip,\n    fill = ~local,\n    position = \"fill\"\n  ) %>%\n  gf_labs(\n    title = \"Plot 2D: Filled Bar Chart\",\n    subtitle = \"Shows Per group differences in Proportions!\"\n  )# position = \"fill\"- Used for proportions\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nThis \"Filled Bar Chart\" (Plot 2D) shows the proportion of local and non-local taxi rides for both the tipping and non-tipping categories. The purple colour represents non-local rides, and the yellow colour represents local rides.This chart emphasizes the relative proportion of local versus non-local rides rather than the absolute counts, making it useful for understanding the distribution of ride types across tipping behaviour.\n\n### Plot 3A: Proportion of taxi rides where tips were given or not, broken down by different taxi companies\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntaxi_modified %>%\n  gf_bar(~company, fill = ~tip, position = \"fill\") %>%\n  gf_labs(\n    title = \"Plot 3A: Proportion of taxi rides where tips were given or not, broken down by different taxi companies\"\n  ) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nThis \"Filled Bar Chart\" (Plot 3A) displays the proportion of taxi rides where tips were given or not, broken down by different taxi companies. The blue segments represent rides where tips were given, and the red segments represent rides without tips. From the chart, it is clear that for all companies, the majority of rides resulted in a tip, while the non-tipping rides make up a smaller proportion across all companies. Some companies, like \"Flash Cab,\" have a slightly larger proportion of non-tipping rides compared to others, but overall, tipping is the dominant behaviour for all the companies displayed. This chart emphasizes the tipping pattern across different taxi providers, showing relatively consistent behaviour.\n\n### Plot 4: Counts of Tips by Hour\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_bar(~hour, fill = ~tip, data = taxi_modified) %>%\n  gf_labs(title = \"Plot 4: Counts of Tips by Hour\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nThe \"Counts of Tips by Hour\" chart shows the distribution of taxi rides and tipping behaviour throughout the day. The number of rides increases steadily during the morning, peaks between 2 PM and 4 PM, and then declines in the evening. Most rides result in a tip, as indicated by the large blue bars across all hours, with a smaller proportion of non-tipping rides (red bars). The highest concentration of rides and tips occurs during the afternoon hours, while early morning and late evening see fewer rides overall. This pattern highlights that tipping is consistent throughout the day, especially during peak ride times.\n\n### Plot 5: Counts of Tips by Day of Week\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_bar(~dow, fill = ~tip, data = taxi_modified) %>%\n  gf_labs(title = \"Plot 5: Counts of Tips by Day of Week\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nThe \"Counts of Tips by Day of Week\" chart shows the number of taxi rides and tipping behaviour across different days of the week. Thursdays have the highest number of rides, followed by Wednesdays, while the weekends (Saturday and Sunday) have the lowest ride counts. Across all days, most rides result in a tip, as indicated by the blue bars. A small portion of rides, particularly on weekdays, do not result in a tip, shown by the red bars. Overall, tipping behavior is consistent throughout the week, but ride volumes peak midweek and decrease during the weekend.\n\n### Plot 6: Counts of Tips by Month\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_bar(~month, fill = ~tip, data = taxi_modified) %>%\n  gf_labs(title = \"Plot 6: Counts of Tips by Month\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nThe bar chart illustrates the distribution of taxi rides and tipping behaviour over the months of January through April. March and April show the highest ride counts, both exceeding 3,000 rides, with a significant majority of these rides resulting in tips. February has a moderate number of rides, slightly lower than March and April, but tipping behavior remains strong. January has the fewest rides, but similarly, most rides result in tips. Overall, tipping appears consistent across all four months, with a clear trend of most taxi rides receiving tips, regardless of the month.\n\n### Plot 7: Counts of Tips by Day of Week and Month\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_bar(~ month | dow, fill = ~tip, data = taxi_modified) %>%\n  gf_labs(title = \"Plot 7: Counts of Tips by Day of Week and Month\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nThe multi-faceted bar chart depicts the counts of taxi rides and tipping patterns across different days of the week (Monday to Sunday) and months (January to April). For most days of the week, March and April show higher counts of rides compared to January and February. Thursdays and Fridays have the highest ride counts, with a strong tendency toward tipping, particularly in March and April. Sundays generally have the fewest rides but maintain a steady tipping trend. Overall, tipping behaviour remains consistent across different days, with the majority of rides receiving tips, especially as the year progresses into spring months.\n\n### Plot 8A: Counts of Tips by Hour and Day of Week\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_bar(~ dow | hour, fill = ~tip, data = taxi_modified) %>%\n  gf_labs(\n    title = \"Plot 8A: Counts of Tips by Hour and Day of Week\",\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nThe bar chart shows the distribution of taxi rides and tipping behaviour across different hours of the day and days of the week. Tipping generally follows a similar pattern throughout the week, with the highest ride counts and tips occurring between 8 AM and 6 PM, particularly around midday. Monday through Friday sees more rides, with a peak tipping period from 8 AM to 3 PM. The early morning and late evening hours (before 7 AM and after 9 PM) have significantly fewer rides and tips. Weekends, especially Sundays, show lower overall ride and tipping activity throughout all hours of the day.\n\n### Plot 8B: Proportions of Tips by Hour and Day of Week\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_bar(~ dow | hour, fill = ~tip, position =\"fill\", data = taxi_modified) %>%\n  gf_labs(\n    title = \"Plot 8B: Proportions of Tips by Hour and Day of Week\",\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nThe bar chart visualizes the proportion of taxi rides that result in tips across different hours of the day ( segregated as multiple graphs) and days of the week ( x-axis). The consistent blue (representing tips) across most hours and days suggests that a large majority of rides result in tipping, regardless of the time or day. However, some fluctuations occur, particularly during early morning hours (2 AM - 5 AM) on weekdays, when the percentage of rides without tips (in red) increases slightly. Despite these minor variations, tipping appears to be a regular part of most rides across all hours and days.\n\n### Plot 9: Counts of Tips by Hour and Day of Week\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_bar(~ hour | dow, fill = ~tip, data = taxi_modified) %>%\n  gf_labs(\n    title = \"Plot 9: Counts of Tips by Hour and Day of Week\",\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nThe chart illustrates the distribution of taxi rides that resulted in tips across different hours of the day (x-axis) for each day of the week( shown as different graphs). The data reveals that tipping patterns are fairly consistent throughout the week, with peak hours for tipping occurring in the late morning to afternoon (around 9 AM to 3 PM). The chart also shows that there are fewer rides without tips (in red) during these peak hours, while early morning and late-night hours, especially on weekends, tend to have a smaller proportion of tipping. Thursdays and Fridays appear to have the highest number of taxi rides with tips.\n\n### Plot 10: Counts of Tips by Hour\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_bar(~hour, fill = ~tip, position =\"fill\", data = taxi_modified) %>%\n  gf_labs(\n    title = \"Plot 10: Counts of Tips by Hour\",\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\nThis bar chart illustrates the proportion of taxi rides that resulted in tips (in blue) versus no tips (in red) across different hours of the day. The majority of taxi rides during all hours tend to result in a tip, as indicated by the dominant blue colour in the chart. There is a slightly higher proportion of rides without tips in the early morning (around 1 AM to 5 AM) and later in the night, but overall, tipping remains consistent throughout the day, with a slight dip in tip occurrences during off-peak hours.\n\n### Plot 11: Counts of Tips by Day of Week\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_bar(~dow, fill = ~tip, position =\"fill\", data = taxi_modified) %>%\n  gf_labs(\n    title = \"Plot 11: Counts of Tips by Day of Week\",\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\nThis bar chart shows the proportion of taxi rides that received tips (in blue) versus no tips (in red) for each day of the week. Across all days, a majority of rides result in tips, as shown by the larger blue segments in each bar. The proportion of no-tips (red) remains fairly consistent throughout the week, with no significant differences between the days. This suggests that tipping behaviour is relatively uniform, regardless of the day of the week.\n\n### Look at the HELPrct dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"HELPrct\")\nHELPrct\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    age anysubstatus anysub cesd  d1 daysanysub dayslink drugrisk e2b female\n1    37            1    yes   49   3        177      225        0  NA      0\n2    37            1    yes   30  22          2       NA        0  NA      0\n3    26            1    yes   39   0          3      365       20  NA      0\n4    39            1    yes   15   2        189      343        0   1      1\n5    32            1    yes   39  12          2       57        0   1      0\n6    47            1    yes    6   1         31      365        0  NA      1\n7    49           NA   <NA>   52  14         NA      334        0   1      1\n8    28            1    yes   32   1         47      365        7   8      0\n9    50            1    yes   50  14         31      365       18   7      1\n10   39            1    yes   46   4        115      382       20   3      0\n11   34           NA   <NA>   46   0         NA      365        8  NA      1\n12   58            0     no   49   3        192      365        0  NA      1\n13   58            1    yes   22   5          6      365        0  NA      0\n14   60            1    yes   36  10          6       22        0   1      0\n15   36            1    yes   43   2          0      443        0  NA      0\n16   28            1    yes   35   6         27       41        0   2      1\n17   35            1    yes   19   1          2      405        0  NA      0\n18   29            0     no   40   2        220      449        0   1      0\n19   27            0     no   52   0        198       49       10   4      1\n20   27            1    yes   37   1         52      367        0  NA      0\n21   41           NA   <NA>   35   1         NA      391       12   1      0\n22   33            1    yes   18   1        129      272        0  NA      0\n23   34           NA   <NA>   36   4         NA      293        0   2      0\n24   31            1    yes   28   2          3      428        0   3      0\n25   48            1    yes   19   4         67      365        0  NA      1\n26   34            1    yes   30   1        154       56        0  NA      0\n27   35            1    yes   27   0         34      361        1  NA      0\n28   34            0     no   24   0        204      365        0  NA      0\n29   29            1    yes   47   1        142       79        0   3      0\n30   35            0     no   45   2        189      364        0  NA      0\n31   43            1    yes   18  10          4      365        0  NA      0\n32   37            0     no   11   0        203      203        3  NA      0\n33   29            0     no   26   1        193      354        0  NA      0\n34   33            1    yes   29   1         10       29        0  NA      0\n35   20            1    yes   34   1        177      365        0  NA      0\n36   38            0     no   37   2        195      365        0   3      0\n37   28            1    yes   23   0          7      365        1   2      0\n38   33            1    yes   41   7         14      365        0   3      0\n39   40           NA   <NA>   21   0         NA      365        1  NA      0\n40   43            0     no   16  15        191      414        0  NA      0\n41   28            1    yes   36   1         31      414        0  NA      0\n42   45            0     no   17   2        174       43        0   2      0\n43   42            1    yes   36   2         17       38        7  NA      0\n44   30           NA   <NA>   19   0         NA      264        0  NA      0\n45   34            1    yes    5   2         23       14        0  NA      1\n46   36            1    yes   25   2          2      377        0  NA      0\n47   44           NA   <NA>   36   5         NA      321       19   1      0\n48   41            1    yes   27   0         30       NA        0  NA      0\n49   30            0     no   44   2        209       26       21   2      0\n50   37            1    yes   29   2        111       18        0  NA      0\n51   35            1    yes   46   3         17      365        0  NA      1\n52   37            1    yes   16   5        137      171        0  NA      0\n53   44            1    yes   44   1          4       27        0  NA      0\n54   47            1    yes   42   2          3      190        0   4      0\n55   38            1    yes   30   5         18       30        0   2      0\n56   37            1    yes   25   0          2      365        1  NA      0\n57   34            1    yes   26   1          1      365        0  11      0\n58   41            0     no   29   3        181       19        0   2      1\n59   29            0     no   33   3        180      365        1   4      1\n60   35            1    yes   28   1         36      400        0   1      0\n61   36           NA   <NA>   33   0         NA      365        0   1      0\n62   27            0     no   44   3        252      431        0   1      0\n63   36            0     no   29   1        195      195        0   1      0\n64   40            0     no   57   5        181       34        0  NA      1\n65   38           NA   <NA>   26   4         NA      133        1  NA      0\n66   42            1    yes   31   2        103       48        8   3      0\n67   26           NA   <NA>   30   4         NA       NA        0  NA      1\n68   41            1    yes   43   0          2       NA       10  NA      1\n69   43            1    yes   28  10         78      365        0  NA      0\n70   28            1    yes   29   3          9      129        0   2      0\n71   30            1    yes   32   2         53       NA        3  NA      0\n72   42           NA   <NA>   30   4         NA       35        0  NA      0\n73   22            1    yes   34   7          4      365        0   1      0\n74   31           NA   <NA>   49   2         NA      439        3   1      0\n75   30            0     no   36   0        177       44        0   3      0\n76   25           NA   <NA>   42   1         NA      365        1   1      0\n77   26            1    yes   40   1          4       77       10  NA      0\n78   35            1    yes   29   1         47       35        0   1      0\n79   53            1    yes   31   3          5      365        0   1      0\n80   29           NA   <NA>   10   2         NA      143        0  NA      0\n81   32            1    yes   37   2        175      365        0  NA      1\n82   24            1    yes   32   2        168      115        3   1      0\n83   35            1    yes   16   1         20      386        1   3      0\n84   32            1    yes   15   0         55      365        0  NA      0\n85   47            1    yes    4   2         56       63        1  NA      0\n86   26           NA   <NA>   30   2         NA      365        0  NA      0\n87   45            1    yes   44   2         63       35       14   1      0\n88   33           NA   <NA>    8   1         NA       NA        0  NA      0\n89   45           NA   <NA>   16  20         NA      365        0   2      0\n90   33           NA   <NA>   47   9         NA       38        0   3      1\n91   27            1    yes   49   1        222      136        0  NA      0\n92   40            1    yes   30   2          9       37        1  NA      0\n93   40           NA   <NA>   36   1         NA      217        0   1      1\n94   37            1    yes   48   3         16      349        0  NA      0\n95   26            1    yes   17   1         59       NA        0  NA      0\n96   27            1    yes   39   0        102      365        0   3      0\n97   35           NA   <NA>   30   2         NA       16        0  NA      1\n98   29           NA   <NA>   24   0         NA       NA       10   2      0\n99   33           NA   <NA>   25   2         NA       60        0  NA      0\n100  39            1    yes   51   3          2      365        0   5      0\n101  33            1    yes   17   3          3      365        7  NA      0\n102  35            1    yes   37  20         63      399        0  NA      0\n103  38           NA   <NA>   45   0         NA       NA        0   1      0\n104  44            1    yes   28   1         47      112       17   1      0\n105  28           NA   <NA>   17   3         NA      365        0  NA      0\n106  33           NA   <NA>   23   0         NA       NA        0  NA      0\n107  30            0     no   39   0        201       18        0   1      1\n108  35            1    yes   38   2        114      365        0   4      0\n109  32           NA   <NA>   53  15         NA       41        0  NA      1\n110  42            0     no   26  10        183      358        0   2      1\n111  37            0     no   47   0        183      169        0  NA      0\n112  41           NA   <NA>   49   4         NA      365        0   1      0\n113  28            1    yes   34   5          0      325       17   2      0\n114  30           NA   <NA>   51   9         NA       NA        9   1      1\n115  35            1    yes   33   2          2      345        0  14      0\n116  35           NA   <NA>   58   5         NA       17        0   2      1\n117  41            1    yes   28   1         17      104        0  NA      0\n118  37            0     no    4   2        183       36        0  NA      0\n119  30            1    yes   15   1         15      365        0  NA      1\n120  39            1    yes   40   3         11      365        0   4      0\n121  32           NA   <NA>   33   2         NA       NA        0  NA      0\n122  50            0     no   35   6        178       49        0  NA      1\n123  33           NA   <NA>   28   1         NA       90        0   2      0\n124  27            1    yes   21   0        163      169        0  NA      0\n125  33            1    yes   33   0          7      399        1  NA      0\n126  38           NA   <NA>   26   4         NA       28        0  NA      1\n127  43            1    yes   45   6          4      358        0   8      0\n128  24            1    yes   45   0         68      365        0   1      1\n129  35            1    yes   31  10        185      387        0   1      0\n130  49           NA   <NA>   28  13         NA      193        0   1      1\n131  49            1    yes   22   5          1      126        0   4      0\n132  33           NA   <NA>   39   1         NA      365        1   1      0\n133  24            0     no   31   0        183       52        9   1      0\n134  28            1    yes   48   4         12      413        0  NA      1\n135  45            0     no   48   2        185       50        0   7      0\n136  46           NA   <NA>   34  20         NA       NA        0  NA      0\n137  37           NA   <NA>   35   1         NA      106        0  NA      1\n138  32            0     no   46   2        183       42        0  NA      0\n139  45           NA   <NA>   34   1         NA      303       11   2      0\n140  39            0     no   10   0        186       30        0   1      0\n141  34            1    yes   31   1        146      113        0  NA      0\n142  32           NA   <NA>   34   2         NA      365        0   3      0\n143  32            1    yes   26   2          5      369        0   1      0\n144  31            1    yes   15   1         31      365        0  NA      1\n145  45           NA   <NA>   48   1         NA       98        0   2      0\n146  30           NA   <NA>   37   1         NA      338        0  NA      0\n147  36            1    yes   20   8         57      365        7   1      0\n148  25            1    yes   38   3          0      414        8   1      0\n149  48            0     no   39   8        178       58        0  NA      0\n150  42            0     no   46   1        256      368        0   1      0\n151  33            1    yes   17   1         61      364        0   1      0\n152  36           NA   <NA>    6   1         NA      365        1  NA      0\n153  41           NA   <NA>   18   4         NA      365        0  NA      0\n154  30            1    yes   29   2         12      365        0  NA      1\n155  57           NA   <NA>   51  10         NA      365        0  NA      0\n156  57            1    yes   39   4         28      380        0   1      1\n157  47           NA   <NA>   31   2         NA      365        5  NA      0\n158  54            1    yes   49   0          0       38        0   4      0\n159  55            0     no   43   1        164       31        0  NA      0\n160  33            1    yes   45   1         13      330       10   1      0\n161  29           NA   <NA>   46   6         NA      365        5   3      1\n162  33           NA   <NA>   44   4         NA      427        0  NA      1\n163  28           NA   <NA>   41   3         NA      443       11   2      0\n164  37            0     no   29   2        163       29        0  NA      0\n165  28            1    yes   38   3        117      218        0  NA      1\n166  32           NA   <NA>   51   1         NA      365        0  NA      0\n167  31           NA   <NA>   38  10         NA      405       20   1      1\n168  36           NA   <NA>   53   3         NA       45        0   3      1\n169  39           NA   <NA>   29   2         NA       14        0   2      0\n170  29           NA   <NA>   31   1         NA      424       13   1      0\n171  38           NA   <NA>   57   4         NA      370        0  NA      1\n172  33           NA   <NA>   38   0         NA       NA        0   2      0\n173  31           NA   <NA>   39  10         NA       17        2  NA      0\n174  39           NA   <NA>   43   1         NA      365       13   1      1\n175  33            1    yes   19  40          3      146        0   1      1\n176  31            1    yes   23   0          9       15        0  NA      0\n177  46            1    yes   44   1        144       14        0   6      0\n178  36            1    yes   12   1         11      140        0  NA      0\n179  22            1    yes   35   0          1      365        0   4      0\n180  33            1    yes   47   2         27      365        0   2      0\n181  35           NA   <NA>   53   2         NA      365       14   2      0\n182  38            1    yes   34   1          0      348       14   1      1\n183  28           NA   <NA>   15   1         NA       48        0  NA      0\n184  33           NA   <NA>   31   2         NA       32        0   2      0\n185  49            1    yes   27   2         61      365        0  NA      0\n186  43           NA   <NA>   36   1         NA       18        0  NA      1\n187  33            1    yes   24   6          2      365        1  NA      1\n188  29           NA   <NA>   54   0         NA      407        4  NA      1\n189  34            0     no   31   2        183       30        0  NA      0\n190  41           NA   <NA>   22   4         NA      365        0  NA      0\n191  47            0     no   41   1        190       78        0  NA      1\n192  24           NA   <NA>   23   0         NA      365        0  NA      0\n193  31           NA   <NA>   18   3         NA       NA        8   1      1\n194  40           NA   <NA>   60   7         NA      406        0  NA      1\n195  32            0     no   34   3        184      365        0  NA      1\n196  32            0     no   26   4        192       22        0   3      0\n197  39           NA   <NA>   40   1         NA      365        0   1      0\n198  19           NA   <NA>   40   1         NA       63        0   8      0\n199  49            1    yes    1   2        166       78        0  NA      0\n200  27           NA   <NA>   41   4         NA      365        1   4      0\n201  38            0     no   38   3        247      365        0   1      1\n202  32            1    yes   37   1         82      348        0  NA      1\n203  22            0     no   16   1        162      357        0  NA      0\n204  36            1    yes   33   3         47       12        0  NA      0\n205  32            1    yes    4   0         88       50        0  NA      0\n206  35           NA   <NA>   24   1         NA      365        0  NA      1\n207  35            0     no   34   1        172      136        0  NA      1\n208  41            1    yes   40   2         63       22        0  NA      0\n209  36            1    yes   39   2         94        7        0  NA      0\n210  43            1    yes   32   2         73       70        0  NA      0\n211  45            1    yes   40   5          7      365        0   1      1\n212  39            1    yes   51   4         33      331        0  NA      0\n213  47           NA   <NA>   39   2         NA      365        1   3      1\n214  32            1    yes   40   6        183       76        0  NA      0\n215  33            1    yes   22   0          9      183        0  NA      0\n216  39            1    yes   42   4        215      428        0  NA      1\n217  44           NA   <NA>   13   0         NA      365        0  NA      1\n218  35           NA   <NA>   49   4         NA       43        0   1      0\n219  31            1    yes   35   1         32      307        1   3      0\n220  25           NA   <NA>   43   0         NA      365        0  NA      0\n221  48            1    yes   27   1         74      353        0   6      0\n222  35           NA   <NA>   40   1         NA       37        0  NA      0\n223  42           NA   <NA>   38   4         NA      349        0   2      0\n224  51            1    yes   39   6          4      272        0   4      0\n225  55            1    yes   30   2         11       40        0   2      1\n226  32            1    yes   35   6         70       37        0  NA      0\n227  41            1    yes   34   2          2      365        0   3      0\n228  34           NA   <NA>   19   1         NA      329        0  NA      1\n229  30           NA   <NA>   39   2         NA      442        0  NA      0\n230  34           NA   <NA>   36   1         NA      326        0  NA      1\n231  38           NA   <NA>   58   8         NA      452        0   1      0\n232  41           NA   <NA>   38   2         NA       24        2  NA      0\n233  31           NA   <NA>   22   0         NA      359        0  NA      1\n234  29           NA   <NA>   46   2         NA      336        0   3      0\n235  36           NA   <NA>   31  10         NA      365        0   1      0\n236  45           NA   <NA>   11   0         NA      379        0  NA      0\n237  36           NA   <NA>   32   2         NA      434       10  NA      0\n238  30            1    yes   33   1         59       12        0  NA      0\n239  40            1    yes   39   1         16      294        0  NA      0\n240  27            1    yes   33   0          4      365        0   2      1\n241  39           NA   <NA>   27   1         NA       21        0  NA      0\n242  39            0     no   43   4        170      350        0   2      0\n243  37            1    yes   30   1          2      440        0   5      0\n244  43            1    yes   12   4         11      236        0   4      0\n245  20            1    yes   42   1         20      365        0  NA      0\n246  35            1    yes   31   2         32       35        5  17      0\n247  32           NA   <NA>   40   6         NA       29       11   2      0\n248  42            0     no   17   0        188      456        0  NA      0\n249  27           NA   <NA>   44   0         NA      279        0  NA      0\n250  30           NA   <NA>   15   2         NA      365        0  NA      0\n251  27           NA   <NA>   41   0         NA      365        8   3      0\n252  41           NA   <NA>   51   3         NA      349        0  NA      0\n253  32            1    yes   24  20          7       46        6   1      0\n254  47            1    yes   29   1         31      368        0   1      0\n255  36           NA   <NA>   40   2         NA      365        0   2      0\n256  32            1    yes   33   2          2      365        0   1      0\n257  33            1    yes   51   1          5      365        1   6      1\n258  30           NA   <NA>   30   6         NA       83        0  NA      1\n259  29           NA   <NA>   46   0         NA       79        8  NA      0\n260  34           NA   <NA>   38   2         NA      365        8  NA      1\n261  34            1    yes   42   0         52      365        1   2      0\n262  40           NA   <NA>   17   2         NA      365        0   2      0\n263  45           NA   <NA>   22   3         NA      365        7  21      0\n264  37            0     no   37   2        179       41        0  NA      1\n265  32           NA   <NA>   11   2         NA       17        0  NA      0\n266  26           NA   <NA>   56   2         NA      365        0  NA      1\n267  31            1    yes   14   0          2      365        0   1      0\n268  39            1    yes   26   0         94      425        0  NA      0\n269  49            1    yes   36   1         94      365        0  NA      0\n270  45            1    yes   41   0         33      365        4   1      1\n271  43           NA   <NA>   18   0         NA      365       10  NA      0\n272  38           NA   <NA>   19   1         NA      365        0  NA      0\n273  23            1    yes   48   1          2      365        0   2      1\n274  35            1    yes   45   3          1       26        0   1      1\n275  23            1    yes   44  20         45      207        0  NA      0\n276  42           NA   <NA>   52   3         NA       63        0  NA      1\n277  29           NA   <NA>   19   1         NA      318        0  NA      0\n278  43            1    yes    9   2          0      365        0   2      0\n279  29           NA   <NA>   55   0         NA      365        0  NA      0\n280  39            1    yes   18   0         16      358        0   2      0\n281  32            1    yes   45   4          1      427        0   2      1\n282  35           NA   <NA>   12   1         NA      441        0   2      0\n283  22            1    yes   33   2          3       30        0  NA      0\n284  39            1    yes   32   1        132       41        0  NA      0\n285  38            1    yes   20   1         NA      285        0   2      0\n286  56            1    yes   37  36          0      412        3  11      0\n287  36            1    yes   39   1        136      324        0   2      1\n288  40           NA   <NA>   43   1         NA       15       17   2      0\n289  22            1    yes   51   2          2      374        9   1      1\n290  39           NA   <NA>   27   5         NA      293        8   4      0\n291  47            1    yes   40   2          3      365        0  NA      0\n292  32            1    yes    8   3         30      373        0   1      0\n293  41            1    yes   54   3          1      356        4  NA      0\n294  32            0     no   35   1        191       21        0  NA      0\n295  37           NA   <NA>   58   8         NA      365        0   2      1\n296  41            0     no   50   2        174       17        1   1      0\n297  31            1    yes   55   5         65      365        0   1      0\n298  33            1    yes   19   0         64       33        0  NA      1\n299  30            1    yes   37   6          8      303       16   1      0\n300  32            1    yes   20   1         93      449        0   1      0\n301  35           NA   <NA>   40   1         NA       77        0  NA      0\n302  32           NA   <NA>   37   1         NA       35        0   3      0\n303  33           NA   <NA>   43   0         NA      365        0   2      0\n304  30            1    yes    8   8          5       32        1  NA      0\n305  44           NA   <NA>   56   3         NA      365        0   2      0\n306  46            1    yes   51   0         62      365        0   2      0\n307  43            0     no    7   0        187       41        0  NA      1\n308  47           NA   <NA>   36   4         NA      365       13   5      0\n309  34            1    yes   49   0         93       32        0  NA      0\n310  47            1    yes   54   1          4      349        8  NA      1\n311  40            1    yes   53   2          1      393        0   7      0\n312  34            1    yes   15  15          5       NA        0  NA      0\n313  48            1    yes   53   4          0      302        0   3      1\n314  37            1    yes    6   5          1      364        1  NA      0\n315  35            1    yes   54   1          5      365       13  NA      1\n316  38           NA   <NA>   42   4         NA      337        0  NA      1\n317  27           NA   <NA>   31   1         NA       31        0   1      0\n318  39            0     no   40   0        178        9        4  NA      0\n319  23            1    yes   37   1          0      359       20   4      0\n320  35            0     no   36   0        178      361        0  NA      1\n321  53            0     no   40   2        175       80       19   2      0\n322  31           NA   <NA>   41   1         NA      365        0  NA      0\n323  32            1    yes   39   0         15       14        0   1      0\n324  33            0     no   38   1        219      398        0   1      0\n325  25            1    yes   38   0          1       40        1   1      0\n326  37           NA   <NA>    9   1         NA       40        0  NA      0\n327  26            1    yes   36   0         18       74        0  NA      0\n328  29           NA   <NA>   27   0         NA      308        5   2      0\n329  30            0     no   26   1        215        7        0  NA      0\n330  47           NA   <NA>   52   8         NA      365        0   2      1\n331  33           NA   <NA>   24   1         NA      300        0  NA      0\n332  36            1    yes   16   1        125      361        0   1      0\n333  23           NA   <NA>   34   3         NA      393        0   1      0\n334  36            1    yes   46   8          5        9        0   5      0\n335  34            1    yes   24   1          2      350        2   1      0\n336  28            1    yes   25   2          1      365        0   2      0\n337  33           NA   <NA>   40   4         NA       21        0  NA      1\n338  26            1    yes   33   0         35      296        0   1      1\n339  30            1    yes   31   0         15        6        0  NA      0\n340  41           NA   <NA>   37   1         NA       19        0  NA      0\n341  31           NA   <NA>   28   1         NA      123        1   4      0\n342  28           NA   <NA>   27   0         NA       44        0  NA      0\n343  59           NA   <NA>    6   2         NA      365        0  NA      0\n344  39            1    yes   21   0         31      363        0  NA      0\n345  36           NA   <NA>   29   0         NA       33        0  NA      0\n346  47            1    yes   23   1         32      152        0  NA      0\n347  26           NA   <NA>   35   0         NA      365        0  NA      0\n348  22            1    yes   55   0         10      338       11   2      0\n349  36           NA   <NA>    3   0         NA      365        0  NA      0\n350  34           NA   <NA>   36   1         NA      365        2   6      0\n351  27           NA   <NA>   40   1         NA      365        3   2      0\n352  34            1    yes   29   0         12      356        0  NA      1\n353  21           NA   <NA>   28   3         NA      331        0   1      0\n354  33           NA   <NA>   21   0         NA      309        0  NA      0\n355  42            1    yes   34   5          3      289       11   1      0\n356  46           NA   <NA>   42   2         NA      306        0   2      0\n357  26            1    yes   23   4        106      410        0  NA      0\n358  36            1    yes   36   3          3      362        0  NA      0\n359  47            0     no   32   3        158       74        0  NA      1\n360  48            0     no   30   2        191       16        0   1      0\n361  32           NA   <NA>   25   5         NA      340       10  NA      0\n362  38           NA   <NA>   35   7         NA      365        0   1      0\n363  43            1    yes   23   2         61       11        0   2      0\n364  30            1    yes   16   0         30      365        0  NA      0\n365  40            0     no   27   1        176       41        0  NA      0\n366  38           NA   <NA>   14   0         NA      292        1  NA      0\n367  22            0     no   44   1        260      376       NA   5      0\n368  39            0     no   52   2        268      449        0  NA      1\n369  22           NA   <NA>   48   2         NA        8        2   3      0\n370  37            0     no   11   1        210      370        0   2      0\n371  37            1    yes   41  10          1      393        0  NA      1\n372  44            1    yes   41   3          0      365        0   1      0\n373  38            0     no   37   1        165      166        1  NA      0\n374  37            1    yes   31   2          2       89        0   3      0\n375  43            1    yes   34   4          2      418        5  NA      0\n376  39            1    yes   40   8          0      247        0   3      0\n377  45            1    yes   37   2          2      322        3  NA      0\n378  39            0     no   30   8        154      265        0  NA      0\n379  31            1    yes   42   1         15      365        0  NA      1\n380  32            1    yes   51   0          5       NA        6   3      0\n381  42            1    yes   42   5         33       98        0  NA      1\n382  33           NA   <NA>   15   0         NA      365        0  NA      1\n383  47            1    yes   12   1         NA      345        0  NA      0\n384  24            1    yes   39   2         32      365        0   3      0\n385  27            1    yes   10   1          2       20        0  NA      0\n386  38           NA   <NA>   33   1         NA      286        1  NA      1\n387  53           NA   <NA>   57   4         NA      365        0  NA      0\n388  39           NA   <NA>   17   1         NA       34        0   4      0\n389  32           NA   <NA>   20   4         NA      365        1  NA      0\n390  27           NA   <NA>   49   2         NA      365        0   1      0\n391  43           NA   <NA>   23   4         NA      365        0   2      1\n392  31           NA   <NA>   26   1         NA      365        0  NA      0\n393  41           NA   <NA>   28   3         NA      365        0  NA      0\n394  27           NA   <NA>    3   0         NA      365        0  NA      1\n395  28           NA   <NA>   18  17         NA       85        0  NA      0\n396  39           NA   <NA>   39   8         NA      365        0  NA      0\n397  39           NA   <NA>   51   0         NA      365       12   3      0\n398  21           NA   <NA>   39   0         NA       NA        6  NA      1\n399  29           NA   <NA>   47   2         NA      365        0  NA      1\n400  31           NA   <NA>   45   5         NA      365        5  NA      0\n401  29           NA   <NA>   28   2         NA      118        2   1      0\n402  45           NA   <NA>   41   2         NA      365        0   1      1\n403  25           NA   <NA>   31   7         NA       68        0  NA      0\n404  24           NA   <NA>   34   2         NA      365       14   8      1\n405  41           NA   <NA>   21   5         NA      365        0  NA      0\n406  27           NA   <NA>   41   3         NA      365        0   1      0\n407  21           NA   <NA>   38   1         NA       44       14   4      0\n408  27           NA   <NA>   36   5         NA       NA        0  NA      0\n409  31           NA   <NA>   24   1         NA      365        0   1      0\n410  41           NA   <NA>   10   0         NA      365        0  NA      0\n411  33           NA   <NA>   41   1         NA      365        0  NA      0\n412  49           NA   <NA>   51   1         NA      365        8   3      0\n413  41           NA   <NA>   45   4         NA      365        1   1      0\n414  25           NA   <NA>   29   0         NA       44        6  NA      0\n415  41           NA   <NA>   56   4         NA       10        0  NA      0\n416  34           NA   <NA>   34   1         NA       87        0   2      0\n417  29           NA   <NA>    4   0         NA      365        0  NA      0\n418  28           NA   <NA>   32   0         NA      365        0  NA      0\n419  29           NA   <NA>   38   2         NA       NA        9   1      0\n420  36           NA   <NA>   26   0         NA      115        0   5      0\n421  36           NA   <NA>   27   0         NA      365        0  NA      0\n422  24           NA   <NA>   21   4         NA      365        0  NA      0\n423  38           NA   <NA>   30   2         NA        6        0   2      0\n424  31           NA   <NA>    7   1         NA      365        0  NA      0\n425  26           NA   <NA>   35   1         NA      365        0  NA      0\n426  35           NA   <NA>   23   2         NA       28        0  NA      1\n427  26           NA   <NA>   36   4         NA      365        1  NA      0\n428  33           NA   <NA>   15   0         NA      365        0  NA      0\n429  46           NA   <NA>   48 100         NA      365        0  NA      0\n430  33           NA   <NA>   31   0         NA      365        0   1      0\n431  39           NA   <NA>   54   6         NA       64        0  NA      0\n432  27           NA   <NA>   21   1         NA      365        9   1      0\n433  33           NA   <NA>   21   8         NA       NA        0  NA      1\n434  36           NA   <NA>   29   4         NA      365        0  NA      1\n435  23           NA   <NA>   23   0         NA      365        5   2      0\n436  33           NA   <NA>   33   2         NA      365       11   1      0\n437  26           NA   <NA>   14   0         NA      365        0  NA      0\n438  38           NA   <NA>   27  10         NA      365        0  NA      0\n439  52           NA   <NA>   24   1         NA      365        0   1      0\n440  39           NA   <NA>   33   2         NA      365        3   1      0\n441  36           NA   <NA>   25   1         NA        2        1  NA      0\n442  44           NA   <NA>   37   0         NA       NA        0   2      0\n443  37           NA   <NA>   47   2         NA        4       21  NA      0\n444  33           NA   <NA>   40   2         NA      365        0   1      1\n445  31           NA   <NA>    9   1         NA      365        0  NA      0\n446  25           NA   <NA>   37   3         NA      365        0   3      0\n447  31           NA   <NA>   47   1         NA      365        0  NA      1\n448  24           NA   <NA>   34   0         NA      365       13   2      0\n449  33           NA   <NA>   28   1         NA      365        0   1      0\n450  49           NA   <NA>   37   0         NA        7        0  NA      0\n451  39           NA   <NA>   28   0         NA      365        1  NA      1\n452  59           NA   <NA>   11   2         NA      365        0   1      0\n453  45           NA   <NA>   35   1         NA      365        0   1      0\n       sex g1b homeless  i1  i2  id indtot linkstatus link       mcs      pcs\n1     male yes   housed  13  26   1     39          1  yes 25.111990 58.41369\n2     male yes homeless  56  62   2     43         NA <NA> 26.670307 36.03694\n3     male  no   housed   0   0   3     41          0   no  6.762923 74.80633\n4   female  no   housed   5   5   4     28          0   no 43.967880 61.93168\n5     male  no homeless  10  13   5     38          1  yes 21.675755 37.34558\n6   female  no   housed   4   4   6     29          0   no 55.508991 46.47521\n7   female yes   housed  13  20   7     38          0   no 21.793024 24.51504\n8     male yes homeless  12  24   8     44          0   no  9.160530 65.13801\n9   female  no homeless  71 129   9     44          0   no 22.029678 38.27088\n10    male  no homeless  20  27  10     44          0   no 36.143761 22.61060\n11  female  no   housed   0   0  11     34          0   no 43.974678 60.07915\n12  female  no   housed  13  13  12     11          0   no 13.382205 41.93376\n13    male  no homeless  20  31  14     40          0   no 49.089302 39.24264\n14    male  no homeless  13  20  15     41          1  yes 25.846157 31.82965\n15    male  no   housed  51  51  16     38          0   no 23.608444 55.16998\n16  female yes homeless   0   0  17     26          1  yes 29.799828 44.77651\n17    male  no   housed   0   0  18     17          0   no 42.166462 56.43837\n18    male yes homeless   1   1  19     40          0   no 16.732292 58.29807\n19  female yes   housed   9  24  20     37          1  yes 15.458271 37.45214\n20    male  no   housed  23  23  21     37          0   no 55.128109 34.33926\n21    male  no   housed  26  26  22     36          0   no 20.871447 36.58481\n22    male  no   housed   0   0  23     27          1  yes 47.286739 61.64098\n23    male yes homeless  34  34  24     42          0   no 19.620596 46.22176\n24    male  no homeless   4   5  25     42          0   no 44.442104 51.56324\n25  female  no   housed   6   8  27     40          0   no 21.668474 36.01007\n26    male  no   housed   3   3  28     34          1  yes 37.371555 63.06006\n27    male  no homeless   7   7  30     37          0   no 34.335667 61.82597\n28    male yes   housed  24  48  31     41          0   no 46.340755 43.53374\n29    male  no homeless   0   0  32     37          1  yes 27.717710 42.22490\n30    male  no homeless  20  20  33     44          0   no 18.984324 42.40059\n31    male  no homeless   3   3  34     41          0   no 58.241264 50.14700\n32    male  no homeless   6   6  35     35          1  yes 27.852608 63.52000\n33    male  no   housed   0   0  36     21          0   no 54.774349 53.35109\n34    male  no   housed   0   0  37     30          1  yes 27.495481 56.73985\n35    male  no homeless  32 135  38     33          0   no 56.324333 53.23396\n36    male  no   housed   2  24  39     43          0   no 37.006042 62.04113\n37    male  no   housed   3   3  40     41          0   no 39.897774 38.39529\n38    male yes homeless  27  27  42     41          0   no 18.640594 51.30330\n39    male  no   housed   3   7  43     32          0   no 45.134098 56.68389\n40    male  no homeless  24  36  44     41          0   no 15.861924 71.39259\n41    male  no homeless   6  12  45     39          0   no 24.148815 52.61977\n42    male  no homeless   0   0  46     22          1  yes 29.901625 36.04588\n43    male  no   housed  13  13  47     39          1  yes 29.412977 50.06427\n44    male  no homeless  25  28  49     38          1  yes 35.206970 62.03183\n45  female  no   housed   6  13  50      8          1  yes 59.454094 52.69898\n46    male  no   housed  13  61  51     36          0   no 20.999893 56.38669\n47    male yes homeless  15  26  52     42          0   no 29.390280 40.38438\n48    male yes   housed   7   7  53     31         NA <NA> 26.773279 58.16169\n49    male yes homeless   9  15  54     44          1  yes 17.925251 45.48341\n50    male  no homeless   5  13  56     40          1  yes 34.434696 63.05807\n51  female  no   housed  13  20  57     32          0   no 24.000315 46.75086\n52    male yes   housed  34  34  58     29          1  yes 47.671936 29.45625\n53    male yes   housed   3   6  59     44          1  yes 26.653036 40.46056\n54    male yes homeless  37  43  60     43          1  yes 28.469273 57.20213\n55    male  no homeless  36  36  61     38          1  yes 26.065777 47.60514\n56    male yes   housed  13  15  62     34          0   no 31.501711 50.16318\n57    male  no   housed   3  19  63     41          0   no 24.998930 50.39870\n58  female yes   housed   3   6  65     20          1  yes 33.374172 55.23372\n59  female yes homeless   0   0  66     29          0   no 27.575460 35.12470\n60    male  no   housed  32  32  67     38          0   no 35.839642 52.68871\n61    male  no   housed  35  42  68     42          0   no 17.565235 67.53625\n62    male yes homeless  20  20  69     41          0   no 20.025341 36.98058\n63    male  no homeless   7  25  70     38          1  yes 25.812592 64.29022\n64  female yes homeless  59 164  71     43          1  yes 17.705963 36.04016\n65    male  no   housed   0   0  72     38          1  yes 39.934162 53.15686\n66    male  no homeless  26  51  73     44          1  yes 23.996725 45.18499\n67  female yes   housed  12  18  74     37         NA <NA> 26.697262 54.38272\n68  female  no   housed   0   0  75     40         NA <NA> 15.447794 55.32189\n69    male  no   housed  18  36  76     38          0   no 38.752102 27.36663\n70    male  no   housed   6  12  78     29          1  yes 34.839962 58.25895\n71    male  no   housed  13  17  80     35         NA <NA> 22.957235 63.91367\n72    male yes homeless   5   5  81     28          1  yes 28.418003 56.90441\n73    male  no homeless   2   2  82     31          0   no 33.115913 48.79136\n74    male  no homeless 102 102  83     40          0   no 14.913925 52.59380\n75    male yes homeless   0   0  84     44          1  yes 17.449858 68.12395\n76    male yes   housed  21  21  85     36          0   no 13.134663 57.07777\n77    male yes homeless   6   8  86     29          1  yes 19.344807 42.62894\n78    male  no   housed   1   1  87     42          1  yes 26.221968 59.56708\n79    male  no homeless  19  19  88     40          0   no 34.210976 44.16995\n80    male  no   housed   1  22  89     29          1  yes 52.926834 58.21477\n81  female yes   housed   2   2  90     40          0   no 28.858498 43.94296\n82    male  no homeless   0   0  91     39          1  yes 26.918222 59.82454\n83    male  no   housed  26  47  93     39          0   no 39.298168 38.46090\n84    male  no   housed   0   0  94     35          0   no 47.550678 37.18519\n85    male  no homeless   9  19  95     38          1  yes 54.053368 56.50476\n86    male  no   housed  10  10  96     40          0   no 37.845036 57.33492\n87    male yes homeless   4   5  97     44          1  yes 20.202173 28.85472\n88    male  no   housed   6  15  98     19         NA <NA> 51.788670 60.58733\n89    male yes homeless  26  51  99     43          0   no 32.566528 30.05406\n90  female yes   housed  64  64 100     44          1  yes 19.595461 40.48884\n91    male yes homeless  26  26 102     34          1  yes 16.302422 55.98083\n92    male yes   housed   2   3 103     42          1  yes 15.754984 48.05733\n93  female yes homeless  33  38 104     42          1  yes 27.993336 44.53589\n94    male yes   housed  61 184 105     40          0   no 23.659925 30.23405\n95    male yes   housed   2   2 106     39         NA <NA> 34.737865 65.74425\n96    male  no homeless  19  19 107     40          0   no 15.618371 55.50122\n97  female  no   housed   9  15 108     33          1  yes 23.299021 51.81045\n98    male  no   housed   0   0 109     38         NA <NA> 40.941338 63.61380\n99    male yes   housed  18  47 110     41          1  yes 24.330456 46.41464\n100   male yes homeless  51  51 111     42          0   no 15.196477 54.13217\n101   male  no   housed   0   0 112     37          0   no 50.788845 46.75063\n102   male  no homeless  36  66 113     43          0   no 23.554617 40.18310\n103   male  no   housed  31  91 114     38         NA <NA> 15.822761 63.48228\n104   male  no   housed   0   0 115     33          1  yes 45.402626 43.62142\n105   male  no   housed  26  69 116     34          0   no 53.616177 57.95000\n106   male  no   housed   2  20 117     28         NA <NA> 59.264427 54.44389\n107 female  no   housed   0   0 118     19          1  yes 24.747171 54.10854\n108   male yes homeless  51  51 119     43          0   no 12.432887 48.89978\n109 female yes homeless  34  34 120     33          1  yes 27.136280 54.79462\n110 female  no homeless  39  95 121     31          0   no 41.321629 36.68874\n111   male  no   housed  19  26 122     42          1  yes 21.912630 43.00148\n112   male  no homeless  13  13 123     33          0   no 28.972683 59.74108\n113   male  no homeless   0   0 124     36          0   no 16.284695 48.89844\n114 female yes   housed   0   0 125     43         NA <NA> 19.156574 34.33698\n115   male  no homeless  13  13 126     19          0   no 41.590557 40.88239\n116 female yes   housed   1   1 127     37          1  yes 18.465418 39.33260\n117   male  no   housed  22  22 128     25          1  yes 39.450993 28.93009\n118   male  no homeless  13  33 129     42          1  yes 42.539974 60.92048\n119 female  no   housed  26  26 131     25          0   no 37.438934 49.29042\n120   male yes homeless  19  30 132     39          0   no 22.669971 35.39379\n121   male yes homeless  26  26 133     41         NA <NA> 45.529411 57.32318\n122 female  no   housed  13  13 134     28          1  yes 20.310446 33.48925\n123   male  no homeless   3   3 135     40          1  yes 23.729639 45.54259\n124   male  no   housed  24  24 136     40          1  yes 40.676174 59.10600\n125   male  no   housed   0   0 137     29          0   no 28.075939 42.01285\n126 female  no   housed   0   0 138     39          1  yes 22.787546 28.74085\n127   male yes homeless  53  53 140     39          0   no 21.460621 45.01618\n128 female  no homeless   7   7 141     39          0   no 28.505577 37.79718\n129   male  no homeless  25  25 142     38          0   no 33.652927 48.87681\n130 female  no homeless  15  15 143     36          1  yes 40.156929 40.96234\n131   male yes homeless  64 179 144     42          1  yes 45.491100 38.13606\n132   male yes homeless   4   4 148     42          0   no 23.371147 29.47202\n133   male yes homeless   3   6 149     37          1  yes 34.598862 50.21533\n134 female  no   housed   2   2 150     33          0   no 22.017500 40.24271\n135   male  no homeless  13  13 151     42          1  yes 29.082914 36.24839\n136   male  no   housed  20  51 152     37         NA <NA> 24.422007 45.56750\n137 female  no homeless   1   3 153     25          1  yes 33.366123 45.16520\n138   male  no homeless  38  38 154     43          1  yes 18.690155 59.47648\n139   male  no homeless   8   8 156     40          0   no 27.683458 31.97959\n140   male  no homeless   0   0 158     34          1  yes 47.145802 53.66537\n141   male  no   housed  13  13 160     43          1  yes 33.517311 29.78529\n142   male  no homeless  39  39 163     30          0   no 41.131794 24.43518\n143   male  no   housed  12  20 164     44          0   no 24.090509 53.75950\n144 female  no   housed   0   0 166     38          0   no 50.030434 57.38777\n145   male  no   housed   0   0 167     37          1  yes 20.069775 50.23810\n146   male  no   housed   1   1 168     29          0   no 18.211269 56.00507\n147   male  no   housed  19  32 169     43          0   no 30.071957 44.92406\n148   male  no   housed   0   0 170     30          0   no 28.679745 61.78611\n149   male yes   housed  26  51 172     37          1  yes 20.517740 54.35444\n150   male  no   housed  19  19 173     29          0   no 31.188143 55.74972\n151   male  no homeless   3   6 174     41          0   no 43.881058 61.44474\n152   male  no   housed   1   1 177     35          0   no 56.784805 56.84005\n153   male  no   housed  12  17 178     41          0   no 39.074711 36.56960\n154 female  no homeless  29  29 179     31          0   no 52.197483 55.73845\n155   male  no homeless  38  38 180     42          0   no 21.200043 32.28706\n156 female  no   housed  12  12 181     36          0   no 36.651463 30.50811\n157   male  no   housed   4   4 182     38          0   no 10.564762 52.94168\n158   male yes homeless  19  50 183     41          1  yes 22.640652 31.00380\n159   male  no   housed  41  54 185     40          1  yes 39.270416 26.45694\n160   male  no   housed   1   3 186     36          0   no 18.771036 40.46645\n161 female  no   housed   0   0 187     39          0   no 20.119982 32.96189\n162 female yes homeless  59  59 188     38          0   no 25.257971 42.12069\n163   male  no homeless  19  19 189     42          0   no 21.049545 45.46138\n164   male  no   housed   8   8 190     34          1  yes 50.018494 54.07817\n165 female yes   housed  16  20 191     35          1  yes 18.324743 43.24062\n166   male  no   housed  12  12 192     34          0   no  7.938221 53.61504\n167 female yes homeless  26  33 193     44          0   no 22.442661 35.90619\n168 female yes homeless  50  50 194     41          1  yes 27.171751 37.75567\n169   male  no homeless  12  20 198     36          1  yes 41.054363 57.70763\n170   male yes homeless   1   3 199     36          0   no 29.860514 53.68318\n171 female yes   housed  13  32 200     39          0   no 20.356680 35.97361\n172   male  no homeless  10  13 201     44         NA <NA> 26.252979 54.42475\n173   male yes   housed   3  24 202     41          1  yes 40.167236 61.28633\n174 female yes   housed  20  20 203     37          0   no 22.815102 35.22702\n175 female  no homeless  19  26 204     32          1  yes 40.032974 38.10227\n176   male yes   housed   6  12 206     32          1  yes 25.615507 66.59317\n177   male  no homeless 102 102 208     38          1  yes 14.358881 49.27981\n178   male  no   housed   1   4 209     39          1  yes 27.122667 58.16642\n179   male  no   housed   0   0 210     29          0   no 36.823708 31.52861\n180   male yes   housed  58  58 211     41          0   no 17.509274 49.36320\n181   male  no   housed   9   9 212     37          0   no 17.927528 43.17081\n182 female  no homeless   0   0 213     32          0   no 43.353584 21.91906\n183   male  no   housed  35  65 214     43          1  yes 47.711655 57.81969\n184   male  no   housed  33  51 215     42          1  yes 20.731987 54.82264\n185   male  no   housed  19  19 217     28          0   no 52.455845 60.41816\n186 female yes   housed  58  58 219     40          1  yes 36.100307 37.03778\n187 female yes   housed  32  38 220     23          0   no 33.259956 41.66993\n188 female  no   housed   0   0 221     33          0   no 12.323594 48.21926\n189   male  no   housed   0   0 222     38          1  yes 23.058514 54.36913\n190   male  no   housed   6   6 223     40          0   no 45.011848 35.79145\n191 female yes homeless   0   0 224     21          1  yes 37.953403 57.64361\n192   male  no   housed  18  18 225     36          0   no 48.410297 59.32288\n193 female yes   housed   0   0 226     32         NA <NA> 27.641029 48.37090\n194 female yes homeless  38  38 228     43          0   no 16.786348 38.51597\n195 female  no   housed  13  13 229     31          0   no 54.768539 23.48208\n196   male yes homeless   0   0 230     41          1  yes 46.119808 23.50237\n197   male  no   housed  46  46 231     32          0   no 35.955441 56.30513\n198   male  no homeless  27  30 232     40          1  yes 30.300137 41.06454\n199   male  no homeless   3   3 233     40          1  yes 59.453930 58.16510\n200   male yes homeless  12  12 235     42          0   no 23.546112 41.57280\n201 female yes   housed  16  26 236     34          0   no 14.919310 57.83691\n202 female  no   housed   1   6 237     28          0   no 40.462433 56.90286\n203   male  no homeless  26  26 238     29          0   no 46.729744 54.59662\n204   male  no   housed  23  92 239     40          1  yes 37.674961 47.36353\n205   male  no   housed  13  13 240     34          1  yes 57.260887 56.89963\n206 female  no   housed   0   0 241     34          0   no 44.351089 46.79942\n207 female  no homeless   4   4 242     36          1  yes 16.469986 58.49455\n208   male yes homeless  26  26 243     43          1  yes 35.235611 48.48331\n209   male  no homeless  13  13 245     35          1  yes 48.239128 56.39499\n210   male  no homeless  13  13 246     35          1  yes 30.371395 47.35083\n211 female yes   housed  10  14 247     34          0   no 26.311474 43.25021\n212   male yes homeless  23  42 248     42          1  yes 22.884369 29.11139\n213 female  no   housed  42  48 249     33          0   no 27.471394 52.42204\n214   male  no   housed  15  15 250     34          1  yes 30.280018 34.58012\n215   male  no   housed  19  20 253     30          1  yes 47.979435 48.27899\n216 female yes   housed   0   0 254     20          0   no 13.968738 48.97176\n217 female  no   housed  13  13 255     26          0   no 41.867615 46.36879\n218   male  no   housed   2   3 256     39          1  yes 25.039495 63.25544\n219   male yes homeless  13  26 257     45          0   no 26.453758 46.76894\n220   male  no   housed  14  16 258     43          0   no 14.480626 70.14779\n221   male  no homeless  51  51 259     36          0   no 52.789551 50.25876\n222   male  no homeless  10  26 260     37          1  yes 35.576111 29.49112\n223   male  no homeless  16  16 261     42          0   no 26.799009 42.42209\n224   male yes homeless 102 102 262     44          1  yes 27.808109 25.61815\n225 female  no   housed   1   2 264     41          1  yes 23.547628 37.35865\n226   male yes   housed   6  20 265     33          1  yes 27.650967 53.05504\n227   male  no homeless  27  27 268     42          0   no 27.177586 43.00587\n228 female  no   housed   4   4 269     27          0   no 34.048084 57.24648\n229   male  no homeless  27  41 270     33          1  yes 31.328341 41.78789\n230 female  no   housed   1   1 272     38          0   no 32.384045 44.85584\n231   male yes   housed  54  73 273     45          0   no 16.125675 47.65467\n232   male yes   housed  24  36 274     40          1  yes 17.625854 44.01194\n233 female  no   housed  10  20 275     23          0   no 47.442879 52.85658\n234   male  no homeless  30  41 276     42          0   no 27.898603 43.68238\n235   male  no homeless  43  43 277     39          0   no 23.683241 43.55378\n236   male  no   housed   2   2 278     21          0   no 58.168713 49.47607\n237   male  no   housed  16  16 279     37          0   no 31.777193 41.87122\n238   male  no   housed   3   3 280      4          1  yes 52.955296 60.10658\n239   male  no   housed  34  51 283     36          1  yes 24.813925 35.46683\n240 female  no homeless   8   8 284     38          0   no 31.781149 51.49556\n241   male  no   housed  28  28 285     42          1  yes 46.830055 62.44834\n242   male  no   housed  13  13 287     44          0   no 16.398746 42.32603\n243   male  no   housed  51  51 288     38          0   no 36.798199 57.78556\n244   male  no homeless 134 140 289     42          1  yes 55.991005 32.58783\n245   male yes homeless   5   6 290     28          0   no 41.624405 53.04678\n246   male  no homeless   5   5 291     40          1  yes 19.645632 46.33508\n247   male yes   housed   3   3 292     44          1  yes 26.919926 48.62301\n248   male  no   housed   0   0 293     37          0   no 37.953053 61.60262\n249   male yes   housed  26  26 294     32          0   no 31.877844 51.38743\n250   male  no   housed  15  30 295     30          0   no 54.970051 33.79744\n251   male yes homeless   9  20 296     39          0   no 30.701992 51.40308\n252   male  no   housed  10  15 297     41          0   no 27.607288 44.29502\n253   male yes   housed   0   0 298     31          1  yes 29.505835 46.76040\n254   male yes   housed  24  45 299     39          0   no 21.931257 49.87759\n255   male yes homeless  33  51 300     40          0   no 20.979116 59.28272\n256   male  no   housed   0   0 302     32          0   no 28.558788 36.63770\n257 female yes   housed   8  13 304     28          0   no 20.911337 33.07642\n258 female yes homeless  27  33 306     25          1  yes 44.446507 45.79400\n259   male yes   housed   0   0 307     39          1  yes 11.819070 62.81930\n260 female  no   housed   0   0 308     33          0   no 21.543468 52.35651\n261   male  no homeless   3   3 309     40          0   no 25.548498 46.98674\n262   male  no homeless  14  20 310     39          0   no 34.139271 56.95329\n263   male  no homeless  12  12 311     38          0   no 29.400602 44.11552\n264 female  no homeless   1   1 313     33          1  yes 27.601431 37.83872\n265   male  no   housed   0   0 315     27          1  yes 56.963795 46.56849\n266 female  no   housed   1   1 316     36          0   no 14.415197 46.74971\n267   male  no   housed   0   0 317     29          0   no 41.195469 40.11784\n268   male  no   housed  25  33 318     39          0   no 36.719200 30.27282\n269   male yes   housed  42  57 319     40          0   no 48.008137 51.74989\n270 female  no   housed   2   2 320     22          0   no 34.747746 64.35030\n271   male  no   housed   6   6 322     32          0   no 58.477470 58.89470\n272   male  no   housed  19  19 323     38          0   no 62.031616 36.10949\n273 female yes homeless  29  58 324     27          0   no 16.718819 35.70664\n274 female  no   housed   0   0 325     32          1  yes 20.220354 32.44772\n275   male yes homeless   0   0 326     37          1  yes 24.378925 35.89378\n276 female yes homeless   0   0 327     32          1  yes 28.447634 39.93384\n277   male  no homeless  22  32 328     31          0   no 18.677704 71.62856\n278   male  no homeless  19  19 329     19          0   no 58.899960 59.34274\n279   male yes homeless  13  19 331     41          0   no 15.773271 48.61113\n280   male yes   housed   1   1 332     34          0   no 34.541599 54.08614\n281 female yes homeless  67  67 333     40          0   no 17.926985 39.09279\n282   male  no homeless  13  13 334     40          0   no 51.918278 51.16233\n283   male  no   housed  20  20 335     37          1  yes 23.137871 51.24271\n284   male  no   housed   0   0 336     39          1  yes 22.939909 33.03571\n285   male  no   housed   3   9 337     26          0   no 33.888065 33.92213\n286   male  no homeless 142 142 338     37          0   no 34.412716 25.92422\n287 female yes homeless  53  53 339     36          0   no 22.237560 36.52407\n288   male yes homeless  64  64 341     32          1  yes 22.354912 31.76573\n289 female  no   housed   0   0 342     40          0   no  7.035307 52.51404\n290   male  no   housed   2   2 343     42          0   no 19.718121 41.32350\n291   male  no homeless  51  51 346     43          0   no 28.747435 51.08913\n292   male  no   housed   1   1 347     12          0   no 55.912579 51.01180\n293   male  no homeless  24  30 348     44          0   no 18.948950 40.42006\n294   male  no   housed  35  35 350     40          1  yes 38.851971 45.13578\n295 female yes homeless  67  80 351     41          0   no 16.922634 34.09209\n296   male  no homeless   0   0 352     41          1  yes 31.739616 31.52352\n297   male yes   housed  13  26 353     38          0   no 17.837486 54.94331\n298 female  no homeless   6   6 354     22          1  yes 24.923189 63.77832\n299   male yes homeless  12  12 355     41          0   no 20.911737 44.87310\n300   male  no homeless   7   7 356     37          0   no 32.773659 63.90699\n301   male yes homeless  26  26 357     40          1  yes 23.771542 47.50178\n302   male yes homeless  41  56 359     41          1  yes 23.242210 30.34914\n303   male yes homeless   3   3 360     41          0   no 22.447948 45.32498\n304   male  no   housed  18  31 361     31          1  yes 58.851147 58.71478\n305   male  no homeless  38  55 362     43          0   no 27.218351 34.31445\n306   male  no   housed  12  15 363     39          0   no 18.287806 43.60749\n307 female  no homeless  26  26 364     15          1  yes 60.542084 55.44015\n308   male  no homeless   4   4 365     40          0   no 37.835770 32.12609\n309   male  no   housed  32  32 366     24          1  yes 37.698196 52.02918\n310 female yes   housed  13  13 367     35          0   no 13.852996 31.11147\n311   male  no homeless  34 102 368     42          0   no 18.615227 58.15246\n312   male  no homeless  38  51 369     29         NA <NA> 47.255920 46.52069\n313 female yes homeless   0   0 370     32          0   no 19.808329 27.09086\n314   male  no homeless  13  13 371     31          0   no 57.873539 57.59651\n315 female  no   housed   0   0 372     44          0   no  9.406377 41.95401\n316 female yes   housed   3   3 374     40          0   no 27.495565 51.27790\n317   male  no   housed  49  49 376     42          1  yes 41.010502 62.97789\n318   male  no homeless  18  36 377     35          1  yes 39.963680 37.80672\n319   male yes   housed   0   0 378     37          0   no 21.599306 36.64597\n320 female  no homeless  58  58 379     13          0   no 44.767254 53.42212\n321   male yes homeless   2   2 380     43          1  yes 29.332056 25.43683\n322   male  no   housed   6  13 381     40          0   no 18.604780 66.09068\n323   male  no homeless   6  13 382     33          1  yes 19.291830 59.91458\n324   male  no   housed  10  10 383     37          0   no 31.856297 64.18298\n325   male  no   housed   0   0 385     36          1  yes 26.698538 43.39342\n326   male  no homeless   6  20 386     26          1  yes 53.340359 57.65739\n327   male  no homeless   6   6 387     42          1  yes 51.003738 51.70669\n328   male  no   housed   0   0 388     35          0   no 28.639238 48.98777\n329   male  no   housed  32  32 389     41          1  yes 44.215485 54.15862\n330 female  no   housed   6   6 391     34          0   no  7.226597 47.60948\n331   male  no   housed   3  12 392     36          0   no 57.296200 59.14530\n332   male  no homeless   6   6 394     42          0   no 30.918043 63.34270\n333   male  no homeless   0   0 395     33          0   no 24.849377 51.15330\n334   male  no homeless  25  25 399     38          1  yes 17.863741 38.19618\n335   male  no homeless  13  26 400     41          0   no 48.483433 57.44889\n336   male  no homeless  18  18 401     36          0   no 27.514502 64.07393\n337 female  no   housed  13  26 402     38          1  yes 19.819555 32.99675\n338 female  no   housed   0   0 403     41          0   no 29.213017 56.69189\n339   male  no   housed   2   2 404     39          1  yes 36.029205 61.19665\n340   male yes homeless  26  38 405     41          1  yes 25.465322 65.26759\n341   male  no homeless   5  25 406     39          1  yes 38.778580 41.73849\n342   male yes   housed  10  23 407     25          1  yes 31.255833 56.56525\n343   male  no homeless   0   0 408     32          0   no 58.750145 53.01821\n344   male  no   housed   4   4 409     39          0   no 32.313843 57.04919\n345   male  no   housed  29  85 411     31          1  yes 40.056877 57.73149\n346   male  no homeless  20  20 413     40          1  yes 37.504734 54.06671\n347   male  no   housed   3  12 415     29          0   no 18.340139 43.89911\n348   male yes homeless   6  12 416     41          0   no 14.108759 48.81484\n349   male  no homeless  13  13 418      9          0   no 59.930012 58.22468\n350   male  no homeless  36  36 419     39          0   no 26.474701 48.76114\n351   male  no homeless  18  18 420     37          0   no 57.489437 37.74971\n352 female  no   housed   0   0 421     37          0   no 31.077631 64.91865\n353   male  no homeless  45  45 422     40          0   no 41.324745 36.81136\n354   male  no   housed  13  13 423     31          0   no 38.907230 49.43321\n355   male  no homeless   4  10 424     42          0   no 22.673281 45.18067\n356   male  no homeless   6  26 425     42          0   no 30.106504 36.35557\n357   male  no   housed   6   6 428     15          0   no 38.276970 36.49366\n358   male  no   housed  25  42 430     37          0   no 45.859604 14.07429\n359 female  no   housed  21  21 431     13          1  yes 51.922516 54.52398\n360   male  no homeless  13  13 432     35          1  yes 25.544411 42.86974\n361   male  no   housed  37  37 433     30          0   no 22.730097 56.85568\n362   male  no   housed  25  25 435     44          0   no 25.445648 44.17665\n363   male yes homeless  38  38 436     32          1  yes 46.967522 58.74847\n364   male  no   housed  12  29 437     32          0   no 47.133209 51.92163\n365   male  no   housed   6  24 438     38          1  yes 42.632927 56.86680\n366   male  no homeless   6   6 440     34          0   no 54.851093 50.26602\n367   male  no   housed   0   0 441     44          0   no 15.101494 48.11589\n368 female  no   housed   0   0 442     37          0   no 24.930353 33.53111\n369   male yes homeless   8   8 443     40          1  yes 19.116766 45.58474\n370   male  no   housed  32  32 444     41          0   no 51.843193 59.72128\n371 female  no homeless  24  51 445     44          0   no 25.710777 49.18084\n372   male  no homeless  51  51 447     30          0   no 32.484653 44.22039\n373   male  no   housed  35  35 448     42          1  yes 43.498222 20.74029\n374   male  no homeless  73  73 449     36          1  yes 18.795931 54.93296\n375   male yes homeless   9  31 452     45          0   no 18.525930 47.58062\n376   male yes homeless  51  51 457     44          1  yes 25.738285 34.90893\n377   male  no   housed   6   8 458     28          0   no 14.891697 60.11456\n378   male  no   housed   6  16 459     32          1  yes 41.360710 44.59728\n379 female yes homeless   6  13 461     34          0   no 16.863588 46.69877\n380   male  no homeless   2   3 464     44         NA <NA> 17.082233 47.00855\n381 female yes   housed  26  41 465     35          1  yes 30.701563 38.40187\n382 female  no   housed   0   0 466      6          0   no 41.624706 62.08943\n383   male  no   housed   1   1 467     31          0   no 43.441059 59.99293\n384   male  no homeless  49 109 468     42          0   no 27.801510 51.69448\n385   male  no   housed  19  25 469     35          1  yes 42.457150 53.54025\n386 female yes   housed   3  16 470     33          0   no 22.337873 42.31495\n387   male  no   housed  38  51  13     45          0   no 18.750151 46.04046\n388   male  no homeless  26  40  26     45          1  yes 28.556833 53.17226\n389   male  no homeless  83 145  29     42          0   no 28.602417 47.83191\n390   male yes   housed  32  40  48     43          0   no 15.268264 40.83885\n391 female  no homeless  19  19  55     31          0   no 27.717655 41.10135\n392   male  no   housed  30 101  64     41          0   no 40.633827 58.78673\n393   male  no   housed  42  42 130     31          0   no 46.269627 36.50988\n394 female  no   housed   1   1 139     21          0   no 57.834595 58.21511\n395   male  no   housed  18  26 145     36          1  yes 33.659222 45.00826\n396   male yes homeless  35 105 146     36          0   no 21.645960 41.52777\n397   male  no homeless  20  20 147     41          0   no 23.724752 32.87765\n398 female yes   housed   0   0 155     35         NA <NA> 47.773228 41.09781\n399 female  no homeless  11  14 157     35          0   no  9.732559 69.17161\n400   male yes   housed  26  26 159     33          0   no 15.599421 47.65695\n401   male  no homeless  43  54 161     43          1  yes 28.475632 45.82243\n402 female  no homeless  19  26 162     25          0   no 55.479382 54.09069\n403   male  no   housed   1   2 165     35          1  yes 36.594727 59.08202\n404 female  no   housed  13  26 171     38          0   no 28.590870 57.76270\n405   male  no   housed  51  51 175     37          0   no 15.078867 41.00370\n406   male yes homeless  24  48 176     44          0   no 38.950596 59.73408\n407   male yes   housed  13  13 184     43          1  yes 31.680859 60.97185\n408   male  no   housed  20  26 195     41         NA <NA> 19.096197 59.91701\n409   male  no   housed  26  26 197     35          0   no 48.442287 58.50863\n410   male  no   housed   8  18 205     36          0   no 52.697727 58.58452\n411   male yes   housed  61  61 207     34          0   no 19.919922 64.95238\n412   male  no   housed  13  19 216     33          0   no 13.312669 49.44656\n413   male yes homeless  28  37 218     43          0   no 15.686288 58.84382\n414   male  no   housed   6   7 227     32          1  yes 33.820976 27.27006\n415   male  no   housed  10  10 234     41          1  yes 11.499865 66.23132\n416   male  no   housed   0   0 244     36          1  yes 26.392733 32.35484\n417   male  no   housed   4  10 251     19          0   no 52.945427 58.86002\n418   male  no   housed  25  37 252     33          0   no 39.972664 56.95388\n419   male  no homeless   2   2 263     40         NA <NA> 23.446474 40.40644\n420   male  no homeless  26  26 266     44          1  yes 42.341843 61.74688\n421   male  no   housed  24  24 267     33          0   no 28.061911 53.93607\n422   male yes homeless   0   0 271     38          0   no 28.073883 63.86327\n423   male  no homeless  13  13 281     38          1  yes 37.116608 35.98627\n424   male  no   housed  12  12 282     31          0   no 57.800064 49.21747\n425   male  no   housed  12  30 301     41          0   no 12.204219 51.45133\n426 female  no   housed   4   4 303     20          1  yes 45.425110 58.75759\n427   male  no   housed  12  18 305     38          0   no 39.038631 47.92621\n428   male  no homeless   3   3 312     36          0   no 37.102394 51.63569\n429   male  no   housed  51  69 314     29          0   no 23.898293 23.55043\n430   male  no homeless   5   5 321     29          0   no 46.330513 59.16547\n431   male  no homeless  68  68 330     42          1  yes 13.412563 42.08535\n432   male  no homeless  29  29 340     43          0   no 49.503277 51.01598\n433 female  no homeless  26  26 345     28         NA <NA> 18.594315 38.86502\n434 female  no   housed   7   8 349     27          0   no 25.676130 54.98139\n435   male  no   housed   5   5 373     38          0   no 33.345051 46.42344\n436   male  no homeless  32  32 390     41          0   no 18.530807 52.71838\n437   male  no   housed   0   0 393     14          0   no 54.525818 59.42862\n438   male  no   housed  76  78 396     10          0   no 44.171612 38.49107\n439   male  no homeless  26  26 397     32          0   no 47.779892 52.73988\n440   male  no homeless  41  62 398     39          0   no 21.271496 45.72916\n441   male  no homeless  18  18 410     43          1  yes 39.929405 61.97865\n442   male  no homeless  22  30 412     31         NA <NA> 25.632202 60.46511\n443   male  no   housed  53  63 417     43          1  yes 23.716438 38.24600\n444 female yes homeless  26  32 427     37          0   no 34.152245 45.27036\n445   male  no homeless   4  13 434     34          0   no 52.792542 57.12674\n446   male  no   housed   3   3 439     30          0   no 28.609346 52.02338\n447 female yes homeless  56  61 451     41          0   no 17.050970 34.51623\n448   male  no homeless   0   0 453     36          0   no 25.851772 50.60834\n449   male  no   housed   0   0 454     38          0   no 41.943066 56.96868\n450   male  no   housed  13  20 455     39          1  yes 62.175503 57.25384\n451 female  no homeless   1  24 460     28          0   no 33.434536 40.04572\n452   male  no homeless  13  13 462     26          0   no 54.424816 53.73204\n453   male  no homeless  51  51 463     43          0   no 30.212227 43.47607\n    pss_fr  racegrp satreat sexrisk substance treat avg_drinks max_drinks\n1        0    black      no       4   cocaine   yes         13         26\n2        1    white      no       7   alcohol   yes         56         62\n3       13    black      no       2    heroin    no          0          0\n4       11    white     yes       4    heroin    no          5          5\n5       10    black      no       6   cocaine    no         10         13\n6        5    black      no       5   cocaine   yes          4          4\n7        1    black     yes       8   cocaine    no         13         20\n8        4    white     yes       6   alcohol   yes         12         24\n9        5    white      no       8   alcohol    no         71        129\n10       0    white     yes       0    heroin   yes         20         27\n11       0    white      no       2    heroin   yes          0          0\n12      13    black     yes       0   alcohol    no         13         13\n13      13    white     yes       1   alcohol    no         20         31\n14       1    black      no       4   cocaine   yes         13         20\n15       1    white      no       8   alcohol   yes         51         51\n16       7 hispanic     yes       3    heroin   yes          0          0\n17       9    black      no       4    heroin    no          0          0\n18       1    other      no       4   cocaine    no          1          1\n19      13    white      no       3    heroin   yes          9         24\n20      11    black     yes       7   cocaine    no         23         23\n21       8    black      no       4    heroin   yes         26         26\n22      14    black      no       4   cocaine   yes          0          0\n23      10    white      no       6   alcohol    no         34         34\n24       6    black     yes       9   cocaine    no          4          5\n25       6    black      no       7   cocaine    no          6          8\n26       3    white      no       5   cocaine   yes          3          3\n27       6    black      no       4    heroin   yes          7          7\n28       4    white      no       5   alcohol    no         24         48\n29       5    black     yes       2   cocaine   yes          0          0\n30       3    black      no       6   alcohol    no         20         20\n31      12    black      no       0   alcohol    no          3          3\n32       2    black     yes       5   cocaine   yes          6          6\n33      10    black      no       2   cocaine   yes          0          0\n34      10    black      no       0   cocaine   yes          0          0\n35       8    black      no       3   alcohol   yes         32        135\n36       6    white      no       4   alcohol    no          2         24\n37      11    black      no       4    heroin    no          3          3\n38       1    white     yes       0   alcohol    no         27         27\n39      10 hispanic      no       4    heroin    no          3          7\n40       3    white      no       7   cocaine   yes         24         36\n41       4    black      no       7   cocaine   yes          6         12\n42       7    black      no       6   cocaine    no          0          0\n43      14    white      no       4    heroin   yes         13         13\n44      10    black      no       5   alcohol    no         25         28\n45      12    black      no       4   cocaine   yes          6         13\n46      12    black      no       1   alcohol    no         13         61\n47      11    black      no      10    heroin   yes         15         26\n48       6    black      no       6   cocaine    no          7          7\n49       6    other      no       9    heroin   yes          9         15\n50       2    black      no       7   alcohol   yes          5         13\n51       1    black      no       7   cocaine   yes         13         20\n52       8    white      no       3   alcohol    no         34         34\n53      13    other      no       4   cocaine   yes          3          6\n54       1    white     yes       2   alcohol    no         37         43\n55      10    black      no       4   alcohol   yes         36         36\n56       7    black     yes       6    heroin    no         13         15\n57       6    black     yes       7   cocaine    no          3         19\n58      13    white     yes       4   alcohol   yes          3          6\n59       4 hispanic     yes       4    heroin    no          0          0\n60      12    black     yes       6   cocaine   yes         32         32\n61      11    black     yes       4   alcohol    no         35         42\n62       5    white      no       6   alcohol    no         20         20\n63       5    black     yes       9   alcohol    no          7         25\n64       1    black      no       4   alcohol   yes         59        164\n65       8    white     yes       2    heroin   yes          0          0\n66       3    white     yes       6   alcohol   yes         26         51\n67       6    white      no       9   cocaine    no         12         18\n68      14    white      no       3    heroin    no          0          0\n69       4    black      no       5   cocaine   yes         18         36\n70       5    white      no       8   cocaine    no          6         12\n71      10    white      no      12   cocaine    no         13         17\n72       2    black      no       4   cocaine   yes          5          5\n73       4    black      no       9    heroin    no          2          2\n74       9    black     yes       6   cocaine    no        102        102\n75       7    white     yes       6   alcohol   yes          0          0\n76       1 hispanic      no       3    heroin    no         21         21\n77      12    white      no      11    heroin   yes          6          8\n78       1    black      no       7   cocaine   yes          1          1\n79      10    black      no       4   alcohol    no         19         19\n80      13    black      no       4   alcohol   yes          1         22\n81      11    black      no       3   cocaine    no          2          2\n82       9    other      no       5   alcohol   yes          0          0\n83       8    white     yes       2   alcohol    no         26         47\n84       3    black      no       1    heroin   yes          0          0\n85      12    white      no       1    heroin   yes          9         19\n86      14    black      no       4   cocaine    no         10         10\n87       4 hispanic      no       5    heroin   yes          4          5\n88      10    black      no       5   cocaine    no          6         15\n89       9    white      no       3   alcohol    no         26         51\n90       1    other      no       7   alcohol   yes         64         64\n91      10    black     yes       4   cocaine   yes         26         26\n92       9    black      no      10   cocaine   yes          2          3\n93       7    white     yes       3   alcohol    no         33         38\n94       6    black      no       3   cocaine   yes         61        184\n95       5    black      no       2   cocaine    no          2          2\n96       9    black     yes       7   cocaine    no         19         19\n97      12    black     yes       5   alcohol   yes          9         15\n98       1    white     yes       4    heroin    no          0          0\n99       4    white      no       6   alcohol   yes         18         47\n100      8    white      no       0   alcohol   yes         51         51\n101      4    white     yes       5    heroin    no          0          0\n102      9    black      no       6   alcohol    no         36         66\n103      6    black      no       3   alcohol    no         31         91\n104      5    white      no       4    heroin   yes          0          0\n105      7    black      no       4   alcohol   yes         26         69\n106      2    black      no       5   cocaine    no          2         20\n107     14 hispanic      no       4   cocaine   yes          0          0\n108      4    white     yes      13   alcohol    no         51         51\n109      7    black      no       5   alcohol   yes         34         34\n110      4    black      no      10   cocaine    no         39         95\n111      3    black      no       9   cocaine   yes         19         26\n112      6    white     yes       4   alcohol    no         13         13\n113     12    white     yes       4    heroin   yes          0          0\n114     10    white      no       6    heroin    no          0          0\n115      3    other      no       9   cocaine    no         13         13\n116     13    black     yes       6   cocaine   yes          1          1\n117      7    black      no       3   alcohol   yes         22         22\n118      4    black      no       7   cocaine   yes         13         33\n119     11    black     yes       3   cocaine   yes         26         26\n120      5    white     yes       3   alcohol    no         19         30\n121      2    white      no       5   alcohol    no         26         26\n122      2    white      no       0   alcohol    no         13         13\n123      8    black     yes       7   cocaine   yes          3          3\n124      9    black      no       7   cocaine   yes         24         24\n125     11    black      no       4    heroin   yes          0          0\n126      9    other      no       7   cocaine   yes          0          0\n127      7    white      no       0   alcohol    no         53         53\n128      7    black     yes       7   cocaine   yes          7          7\n129      1    black      no       7   alcohol    no         25         25\n130      7 hispanic     yes       9   alcohol    no         15         15\n131      5    black      no       6   alcohol   yes         64        179\n132     12    black      no       4    heroin    no          4          4\n133      9    white     yes       5    heroin   yes          3          6\n134      1    white      no       5   cocaine   yes          2          2\n135      8    white      no       7   alcohol    no         13         13\n136      7    white      no       5   alcohol    no         20         51\n137      8    black      no       9   cocaine   yes          1          3\n138      7    other      no       5   cocaine   yes         38         38\n139      6    black     yes       6    heroin    no          8          8\n140      3    black     yes       6   cocaine   yes          0          0\n141      3    black      no       2   cocaine    no         13         13\n142      8    white      no       5   alcohol   yes         39         39\n143     10    black      no       7   cocaine    no         12         20\n144      9    black     yes       2   cocaine    no          0          0\n145     11    white      no       4    heroin   yes          0          0\n146     11    other     yes       3    heroin    no          1          1\n147      9    white     yes       1   alcohol    no         19         32\n148      2    white      no       6    heroin    no          0          0\n149      8    white      no       4   alcohol   yes         26         51\n150      8    black      no       7   alcohol   yes         19         19\n151      7    black      no       8   cocaine    no          3          6\n152      3    black     yes       9   cocaine   yes          1          1\n153      5    white     yes       5   alcohol    no         12         17\n154     13    black     yes       7   cocaine   yes         29         29\n155      2    white      no       8   alcohol    no         38         38\n156      6    white     yes       0   alcohol    no         12         12\n157      9    black      no       0    heroin    no          4          4\n158      7    white      no       0   alcohol   yes         19         50\n159     11 hispanic      no       3   alcohol   yes         41         54\n160      2    other      no       0    heroin    no          1          3\n161      3    white      no       4    heroin   yes          0          0\n162      7 hispanic      no       5   alcohol    no         59         59\n163      1    white      no       6    heroin   yes         19         19\n164      7    black      no       2   cocaine   yes          8          8\n165     14    black      no      11   cocaine    no         16         20\n166     10    black      no       4   cocaine    no         12         12\n167      8    white      no      11   alcohol    no         26         33\n168      3    white      no       9   alcohol   yes         50         50\n169     14    white      no       0   alcohol   yes         12         20\n170     11    white      no       1    heroin   yes          1          3\n171      0    black      no      14   cocaine    no         13         32\n172      3 hispanic      no       7   cocaine    no         10         13\n173      4    black      no       8   cocaine   yes          3         24\n174     10    white      no       4    heroin   yes         20         20\n175      2    black     yes       7   cocaine    no         19         26\n176     10    white      no       4   alcohol   yes          6         12\n177      2    black     yes       7   alcohol   yes        102        102\n178     10    black      no       7   cocaine    no          1          4\n179      2    other     yes       5    heroin   yes          0          0\n180     12    black      no       8    heroin    no         58         58\n181      2    white      no       4    heroin   yes          9          9\n182      9    black      no       8    heroin    no          0          0\n183      2    black      no       6   cocaine   yes         35         65\n184      5    black      no       8   alcohol   yes         33         51\n185     13    black     yes       3   alcohol    no         19         19\n186     11    black     yes       2   alcohol   yes         58         58\n187      8    other      no       3    heroin    no         32         38\n188     11    white      no       6    heroin    no          0          0\n189      6    white      no       6   cocaine   yes          0          0\n190     10    black      no       3   cocaine   yes          6          6\n191     11    black      no       0   cocaine    no          0          0\n192      6 hispanic      no       6   alcohol    no         18         18\n193     12    white      no       4    heroin    no          0          0\n194      3    white     yes      11   cocaine   yes         38         38\n195     12    black     yes       0   cocaine    no         13         13\n196      5    black      no       3   alcohol   yes          0          0\n197     11    black      no       3   alcohol    no         46         46\n198      4    white     yes       2    heroin   yes         27         30\n199     14    black      no       2   cocaine    no          3          3\n200      7    white      no       4    heroin    no         12         12\n201      3    white      no       5   alcohol   yes         16         26\n202      3    black     yes       4   cocaine   yes          1          6\n203      1    white      no       0   alcohol    no         26         26\n204      2    black     yes       7   alcohol   yes         23         92\n205      0    black     yes       5   alcohol    no         13         13\n206      4    black      no       2   cocaine    no          0          0\n207      2    black      no       8   cocaine    no          4          4\n208      0    white     yes       5   alcohol   yes         26         26\n209      3    black      no       2   cocaine   yes         13         13\n210      1    other      no       5   cocaine   yes         13         13\n211      8    white      no       5   alcohol    no         10         14\n212      5    black      no       4   alcohol    no         23         42\n213     10    black      no       5    heroin    no         42         48\n214     12    white      no       4   alcohol   yes         15         15\n215      6    black      no       4   cocaine   yes         19         20\n216     11    black      no       4   cocaine   yes          0          0\n217      7 hispanic      no       4    heroin    no         13         13\n218     14    black      no       8   cocaine    no          2          3\n219      3    white      no       5    heroin    no         13         26\n220      5    white      no       5   cocaine   yes         14         16\n221      1    white     yes       6   alcohol    no         51         51\n222      3    black      no       7   cocaine   yes         10         26\n223     10    white      no       0   alcohol    no         16         16\n224      7    white      no       1   alcohol   yes        102        102\n225      7    black     yes       2    heroin   yes          1          2\n226      6    black      no       5   cocaine   yes          6         20\n227      6    black      no      11   cocaine    no         27         27\n228     12    black      no       2   cocaine    no          4          4\n229      1    black      no       7   cocaine   yes         27         41\n230     10    black      no       4   cocaine    no          1          1\n231     11    white     yes       1   alcohol    no         54         73\n232     13 hispanic      no       4    heroin   yes         24         36\n233     11    black      no       7   alcohol   yes         10         20\n234      2    white     yes       1   alcohol    no         30         41\n235      9    black      no       4   alcohol   yes         43         43\n236      3    black      no       8   cocaine    no          2          2\n237      4    black      no       0    heroin    no         16         16\n238     12    black      no       4   cocaine   yes          3          3\n239     12    black      no       5   cocaine    no         34         51\n240      7    black     yes       8   cocaine   yes          8          8\n241      1    black      no       1   alcohol   yes         28         28\n242      3    black      no       6   cocaine    no         13         13\n243     13    black     yes       7   cocaine   yes         51         51\n244     11    black     yes      13   alcohol   yes        134        140\n245      6    black     yes       2   alcohol    no          5          6\n246      9    white      no       5    heroin   yes          5          5\n247      3    white      no       4   alcohol    no          3          3\n248      6    black     yes       4   cocaine    no          0          0\n249     11 hispanic      no       3   cocaine    no         26         26\n250     12    white      no       1   alcohol   yes         15         30\n251      4    white      no       4    heroin   yes          9         20\n252      5    white     yes       0   alcohol    no         10         15\n253     10 hispanic      no       3    heroin    no          0          0\n254      6    other      no       2   alcohol   yes         24         45\n255      1    white     yes       0   alcohol   yes         33         51\n256      4 hispanic      no       5    heroin    no          0          0\n257      6 hispanic     yes       4    heroin   yes          8         13\n258     12    black      no       4   alcohol   yes         27         33\n259      2 hispanic     yes       4    heroin   yes          0          0\n260     10    white      no       4    heroin    no          0          0\n261      5 hispanic      no       3    heroin   yes          3          3\n262     14    white      no       4   alcohol   yes         14         20\n263      3    white     yes       2    heroin    no         12         12\n264     11    black      no       6   cocaine    no          1          1\n265      5    black      no       4   cocaine   yes          0          0\n266      2    black      no      11    heroin   yes          1          1\n267     11 hispanic      no       3    heroin   yes          0          0\n268      9    other      no       4   alcohol    no         25         33\n269     11 hispanic      no       0   alcohol    no         42         57\n270      3    white      no       1    heroin   yes          2          2\n271     11    white     yes       6    heroin   yes          6          6\n272     12    black      no       5   cocaine    no         19         19\n273      3    black      no      11   alcohol   yes         29         58\n274      2    black      no       9   alcohol   yes          0          0\n275      4 hispanic      no       4    heroin    no          0          0\n276      2    other      no       0    heroin   yes          0          0\n277      6    black      no       6   cocaine    no         22         32\n278     12    black     yes       6   alcohol   yes         19         19\n279      3    black     yes       5   alcohol    no         13         19\n280      5    black      no       8   cocaine   yes          1          1\n281      7    black      no       6   alcohol    no         67         67\n282     12    black     yes      11   cocaine    no         13         13\n283     10    white      no       2    heroin   yes         20         20\n284     10    black      no       2    heroin   yes          0          0\n285      2    black     yes       7   cocaine   yes          3          9\n286      5    white      no       8   alcohol    no        142        142\n287      3    black     yes       5   alcohol    no         53         53\n288      1    white     yes       0    heroin    no         64         64\n289      8    other      no       7    heroin   yes          0          0\n290      7    other      no       3    heroin    no          2          2\n291     10    white      no       6   alcohol   yes         51         51\n292     11    black     yes       6   cocaine   yes          1          1\n293      7    black      no       9   alcohol    no         24         30\n294     12 hispanic      no       1   alcohol    no         35         35\n295      0    other      no       2   alcohol    no         67         80\n296      0    white      no       4    heroin   yes          0          0\n297      5    black      no       1   cocaine    no         13         26\n298      8    black      no       4   cocaine   yes          6          6\n299      2 hispanic      no       8    heroin   yes         12         12\n300      2 hispanic      no       0   alcohol    no          7          7\n301      5    white      no       7   alcohol   yes         26         26\n302      9    white     yes       6   alcohol   yes         41         56\n303      2 hispanic     yes       7   alcohol    no          3          3\n304      4    black      no       5   alcohol   yes         18         31\n305      0    white      no       9   alcohol    no         38         55\n306      2    black     yes       4   alcohol    no         12         15\n307     13    white      no       1    heroin   yes         26         26\n308      4    black     yes       0    heroin    no          4          4\n309     11 hispanic      no       4   alcohol   yes         32         32\n310      9    black      no       0   cocaine   yes         13         13\n311      5    white      no       4   alcohol    no         34        102\n312      6    black      no       7   cocaine   yes         38         51\n313     13    white     yes       3   alcohol    no          0          0\n314     14    black      no       8   cocaine   yes         13         13\n315     13    white      no       4    heroin    no          0          0\n316      3    black      no       9   cocaine    no          3          3\n317      5    black     yes      11   cocaine   yes         49         49\n318      0    white      no       3   alcohol    no         18         36\n319      1 hispanic     yes       3    heroin   yes          0          0\n320     14    black      no       4   cocaine    no         58         58\n321      5 hispanic      no       4    heroin   yes          2          2\n322      4    black      no       5   cocaine   yes          6         13\n323      6    black      no       5   cocaine   yes          6         13\n324      7    black     yes       6   cocaine    no         10         10\n325      3 hispanic      no       1    heroin   yes          0          0\n326     12    white      no       0   alcohol    no          6         20\n327      2 hispanic     yes       2   cocaine   yes          6          6\n328     10    white      no       2    heroin    no          0          0\n329      9    black      no       6   alcohol   yes         32         32\n330      9    white      no       4   alcohol   yes          6          6\n331      5 hispanic     yes       4   alcohol    no          3         12\n332     11    black     yes       5   cocaine   yes          6          6\n333      1 hispanic     yes       4   cocaine   yes          0          0\n334      6    white      no       0   alcohol   yes         25         25\n335      5    white      no       5   alcohol    no         13         26\n336      3    black     yes       5   alcohol    no         18         18\n337      0    black      no       4   alcohol   yes         13         26\n338      3    black     yes       3    heroin    no          0          0\n339      1    black      no       3   cocaine   yes          2          2\n340      5    black      no       9   cocaine    no         26         38\n341     10    black     yes       8   cocaine   yes          5         25\n342      7    black      no       6   cocaine   yes         10         23\n343     12    black      no       8   cocaine    no          0          0\n344     14    black      no       4    heroin    no          4          4\n345     11    black      no       5   cocaine   yes         29         85\n346      3    other      no       2   alcohol    no         20         20\n347     12    black      no       2   cocaine   yes          3         12\n348      5    white     yes       5    heroin    no          6         12\n349      3    black      no       7   cocaine    no         13         13\n350     12    white     yes       3    heroin   yes         36         36\n351      8    white     yes       3    heroin    no         18         18\n352     14    black      no      12   cocaine   yes          0          0\n353      3 hispanic      no       2    heroin    no         45         45\n354     11    black     yes       2    heroin   yes         13         13\n355      4    white      no       0    heroin    no          4         10\n356      5    white     yes       4   alcohol    no          6         26\n357      5    black      no       3    heroin    no          6          6\n358      8    white      no       4   alcohol    no         25         42\n359     12 hispanic      no       0   alcohol    no         21         21\n360     12    other      no       4    heroin   yes         13         13\n361     11 hispanic      no       2    heroin   yes         37         37\n362      8    black     yes       5   alcohol    no         25         25\n363      4    white     yes       1   alcohol   yes         38         38\n364      8 hispanic      no       3   alcohol    no         12         29\n365      6    black      no       4   cocaine   yes          6         24\n366      3    black      no       5    heroin   yes          6          6\n367      0    white     yes       5    heroin    no          0          0\n368      7    black      no       2    heroin   yes          0          0\n369      4    white     yes       1    heroin   yes          8          8\n370      5    white      no       5   alcohol    no         32         32\n371      9    other      no       9   alcohol    no         24         51\n372      4    white     yes       3   alcohol    no         51         51\n373      3    black      no       4   alcohol   yes         35         35\n374      4 hispanic     yes       2   alcohol    no         73         73\n375      3    white      no       4    heroin   yes          9         31\n376      2    white      no       5   alcohol   yes         51         51\n377      2    black      no       7    heroin    no          6          8\n378      7    white      no       3   alcohol   yes          6         16\n379      0    black      no      10   cocaine   yes          6         13\n380     14    white      no       5    heroin   yes          2          3\n381      5    white      no       6   alcohol   yes         26         41\n382     11    black     yes       6   cocaine   yes          0          0\n383     14    black     yes       5   cocaine    no          1          1\n384      1    black      no       5   cocaine    no         49        109\n385     11 hispanic      no       4    heroin   yes         19         25\n386      8    black      no       1    heroin    no          3         16\n387      5    white      no       2   alcohol    no         38         51\n388     14    white      no       3   alcohol   yes         26         40\n389      6    white      no       5   alcohol    no         83        145\n390      7    white      no       7    heroin    no         32         40\n391      3    black      no       6   alcohol    no         19         19\n392      4 hispanic     yes      12   cocaine   yes         30        101\n393     14    black      no       3   alcohol    no         42         42\n394      4    black     yes       1   cocaine    no          1          1\n395      8    other      no       7   cocaine   yes         18         26\n396      8    white      no       4   alcohol    no         35        105\n397      7 hispanic      no       0   alcohol   yes         20         20\n398     14    white      no       1    heroin    no          0          0\n399      4    black      no       7   cocaine    no         11         14\n400      4 hispanic     yes       2    heroin   yes         26         26\n401      7    white      no       6   alcohol   yes         43         54\n402      4    white      no       4   alcohol    no         19         26\n403      8    white      no       5   cocaine   yes          1          2\n404      9    white     yes      14    heroin   yes         13         26\n405      3    white     yes       4   alcohol   yes         51         51\n406     11    white      no       1   alcohol    no         24         48\n407      1    white      no      10    heroin   yes         13         13\n408      3    white     yes       1   alcohol    no         20         26\n409      7    black     yes       3   alcohol    no         26         26\n410     11    white      no       3   alcohol    no          8         18\n411      5    white      no       8   alcohol    no         61         61\n412      8    black      no       3    heroin    no         13         19\n413      1 hispanic      no       8   alcohol   yes         28         37\n414      4    other      no       5    heroin   yes          6          7\n415      4    other      no       3   alcohol   yes         10         10\n416      7 hispanic      no       8    heroin   yes          0          0\n417     11    white     yes       5   cocaine   yes          4         10\n418      3    black     yes       2   alcohol    no         25         37\n419      8 hispanic      no       9    heroin    no          2          2\n420      3    white      no       0   alcohol   yes         26         26\n421     12    black      no       4   cocaine    no         24         24\n422      9 hispanic      no       3   cocaine   yes          0          0\n423      9    black     yes       8   cocaine   yes         13         13\n424     12    black      no       4   cocaine    no         12         12\n425     11    white      no       2   cocaine    no         12         30\n426      1    black      no       2   cocaine   yes          4          4\n427      0    black      no       7   cocaine    no         12         18\n428      2    black      no       3   cocaine    no          3          3\n429      9    white     yes       2   alcohol    no         51         69\n430      8    black      no       3   cocaine    no          5          5\n431      7    white      no       3   cocaine    no         68         68\n432      3    white      no       5   alcohol   yes         29         29\n433      3    white      no       4   alcohol    no         26         26\n434     13    white      no       4   alcohol   yes          7          8\n435      1    white      no       6    heroin   yes          5          5\n436      1    white     yes       7    heroin    no         32         32\n437      5 hispanic      no       4    heroin    no          0          0\n438      1    white      no       4   alcohol    no         76         78\n439     10    white      no       0   alcohol    no         26         26\n440      2    white      no       8   alcohol   yes         41         62\n441      3    white     yes       4    heroin   yes         18         18\n442     14    white      no       3   alcohol    no         22         30\n443      7 hispanic      no       1    heroin   yes         53         63\n444      2 hispanic      no       3   alcohol   yes         26         32\n445     11    other      no       2   alcohol    no          4         13\n446      6    black     yes       4    heroin    no          3          3\n447      8 hispanic     yes      14   alcohol    no         56         61\n448      5    white     yes       4    heroin    no          0          0\n449      7    white      no       4    heroin   yes          0          0\n450     11    white      no       0   alcohol   yes         13         20\n451      1    white      no       2    heroin    no          1         24\n452      7    black     yes       9   cocaine    no         13         13\n453     11    white      no       4   alcohol    no         51         51\n    hospitalizations\n1                  3\n2                 22\n3                  0\n4                  2\n5                 12\n6                  1\n7                 14\n8                  1\n9                 14\n10                 4\n11                 0\n12                 3\n13                 5\n14                10\n15                 2\n16                 6\n17                 1\n18                 2\n19                 0\n20                 1\n21                 1\n22                 1\n23                 4\n24                 2\n25                 4\n26                 1\n27                 0\n28                 0\n29                 1\n30                 2\n31                10\n32                 0\n33                 1\n34                 1\n35                 1\n36                 2\n37                 0\n38                 7\n39                 0\n40                15\n41                 1\n42                 2\n43                 2\n44                 0\n45                 2\n46                 2\n47                 5\n48                 0\n49                 2\n50                 2\n51                 3\n52                 5\n53                 1\n54                 2\n55                 5\n56                 0\n57                 1\n58                 3\n59                 3\n60                 1\n61                 0\n62                 3\n63                 1\n64                 5\n65                 4\n66                 2\n67                 4\n68                 0\n69                10\n70                 3\n71                 2\n72                 4\n73                 7\n74                 2\n75                 0\n76                 1\n77                 1\n78                 1\n79                 3\n80                 2\n81                 2\n82                 2\n83                 1\n84                 0\n85                 2\n86                 2\n87                 2\n88                 1\n89                20\n90                 9\n91                 1\n92                 2\n93                 1\n94                 3\n95                 1\n96                 0\n97                 2\n98                 0\n99                 2\n100                3\n101                3\n102               20\n103                0\n104                1\n105                3\n106                0\n107                0\n108                2\n109               15\n110               10\n111                0\n112                4\n113                5\n114                9\n115                2\n116                5\n117                1\n118                2\n119                1\n120                3\n121                2\n122                6\n123                1\n124                0\n125                0\n126                4\n127                6\n128                0\n129               10\n130               13\n131                5\n132                1\n133                0\n134                4\n135                2\n136               20\n137                1\n138                2\n139                1\n140                0\n141                1\n142                2\n143                2\n144                1\n145                1\n146                1\n147                8\n148                3\n149                8\n150                1\n151                1\n152                1\n153                4\n154                2\n155               10\n156                4\n157                2\n158                0\n159                1\n160                1\n161                6\n162                4\n163                3\n164                2\n165                3\n166                1\n167               10\n168                3\n169                2\n170                1\n171                4\n172                0\n173               10\n174                1\n175               40\n176                0\n177                1\n178                1\n179                0\n180                2\n181                2\n182                1\n183                1\n184                2\n185                2\n186                1\n187                6\n188                0\n189                2\n190                4\n191                1\n192                0\n193                3\n194                7\n195                3\n196                4\n197                1\n198                1\n199                2\n200                4\n201                3\n202                1\n203                1\n204                3\n205                0\n206                1\n207                1\n208                2\n209                2\n210                2\n211                5\n212                4\n213                2\n214                6\n215                0\n216                4\n217                0\n218                4\n219                1\n220                0\n221                1\n222                1\n223                4\n224                6\n225                2\n226                6\n227                2\n228                1\n229                2\n230                1\n231                8\n232                2\n233                0\n234                2\n235               10\n236                0\n237                2\n238                1\n239                1\n240                0\n241                1\n242                4\n243                1\n244                4\n245                1\n246                2\n247                6\n248                0\n249                0\n250                2\n251                0\n252                3\n253               20\n254                1\n255                2\n256                2\n257                1\n258                6\n259                0\n260                2\n261                0\n262                2\n263                3\n264                2\n265                2\n266                2\n267                0\n268                0\n269                1\n270                0\n271                0\n272                1\n273                1\n274                3\n275               20\n276                3\n277                1\n278                2\n279                0\n280                0\n281                4\n282                1\n283                2\n284                1\n285                1\n286               36\n287                1\n288                1\n289                2\n290                5\n291                2\n292                3\n293                3\n294                1\n295                8\n296                2\n297                5\n298                0\n299                6\n300                1\n301                1\n302                1\n303                0\n304                8\n305                3\n306                0\n307                0\n308                4\n309                0\n310                1\n311                2\n312               15\n313                4\n314                5\n315                1\n316                4\n317                1\n318                0\n319                1\n320                0\n321                2\n322                1\n323                0\n324                1\n325                0\n326                1\n327                0\n328                0\n329                1\n330                8\n331                1\n332                1\n333                3\n334                8\n335                1\n336                2\n337                4\n338                0\n339                0\n340                1\n341                1\n342                0\n343                2\n344                0\n345                0\n346                1\n347                0\n348                0\n349                0\n350                1\n351                1\n352                0\n353                3\n354                0\n355                5\n356                2\n357                4\n358                3\n359                3\n360                2\n361                5\n362                7\n363                2\n364                0\n365                1\n366                0\n367                1\n368                2\n369                2\n370                1\n371               10\n372                3\n373                1\n374                2\n375                4\n376                8\n377                2\n378                8\n379                1\n380                0\n381                5\n382                0\n383                1\n384                2\n385                1\n386                1\n387                4\n388                1\n389                4\n390                2\n391                4\n392                1\n393                3\n394                0\n395               17\n396                8\n397                0\n398                0\n399                2\n400                5\n401                2\n402                2\n403                7\n404                2\n405                5\n406                3\n407                1\n408                5\n409                1\n410                0\n411                1\n412                1\n413                4\n414                0\n415                4\n416                1\n417                0\n418                0\n419                2\n420                0\n421                0\n422                4\n423                2\n424                1\n425                1\n426                2\n427                4\n428                0\n429              100\n430                0\n431                6\n432                1\n433                8\n434                4\n435                0\n436                2\n437                0\n438               10\n439                1\n440                2\n441                1\n442                0\n443                2\n444                2\n445                1\n446                3\n447                1\n448                0\n449                1\n450                0\n451                0\n452                2\n453                1\n```\n\n\n:::\n:::\n\n\nThe HELPrct dataset displayed contains 453 rows and 30 columns of various types of variables. These variables include data related to demographic characteristics (like age, sex), substance use (such as anysub, daysanysub), risks (drugrisk, sexrisk), treatments (treat, hospitalization), and psychological factors (such as cesd score, mcs, pcs). The dataset provides details like the number of days since a participant last used substances, their risk levels, treatment history, average and maximum number of drinks consumed, and hospitalization incidents. It includes a mix of categorical and numeric data, offering a comprehensive look at factors relevant to participants' treatment and health risks.\n\n### Plot 1: Primary Substance of Abuse\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHELPrct %>% \n  gf_bar(~substance)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\nThe bar chart illustrates the distribution of primary substances of abuse among the participants in the dataset. The three substances depicted are alcohol, cocaine, and heroin. Alcohol has the highest count, with over 150 participants primarily abusing it. Cocaine comes next, followed by heroin, which has the lowest count among the three substances. This suggests that alcohol abuse is more prevalent among the participants compared to cocaine and heroin.\n\n### Plot 2: Proportion of Primary Substance of Abuse by Sex\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHELPrct %>%\n  gf_props(~substance, fill=~sex)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\nThis displays the proportion of male and female participants who primarily abuse alcohol, cocaine, or heroin. Each bar is divided to represent the proportion of males (shown in blue) and females (shown in red) for each substance. For alcohol and heroin, males make up a larger portion of the abusers, whereas cocaine has a more balanced proportion between males and females. Overall, more males than females are represented across all three substances of abuse.\n\n### Look at the apartments dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\napartments <- read_csv(\"../../data/apartments.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 1460 Columns: 1\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (1): GrLivArea;SalePrice\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\napartments\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,460 × 1\n   `GrLivArea;SalePrice`\n   <chr>                \n 1 1710;208500          \n 2 1262;181500          \n 3 1786;223500          \n 4 1717;140000          \n 5 2198;250000          \n 6 1362;143000          \n 7 1694;307000          \n 8 2090;200000          \n 9 1774;129900          \n10 1077;118000          \n# ℹ 1,450 more rows\n```\n\n\n:::\n:::\n\n\nThe dataset combines two attributes-living area and sale price in each row, allowing for analysis of how living space correlates with the sale price across different apartments.\n\n### Specifying Delimiter\n\n\n::: {.cell}\n\n```{.r .cell-code}\napartments <- read_delim(file=\"../../data/apartments.csv\",delim =\";\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 1460 Columns: 2\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \";\"\ndbl (2): GrLivArea, SalePrice\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\nThe dataset is read using a semicolon (;) delimiter.\n\n### Dataset - apartments\n\n\n::: {.cell}\n\n```{.r .cell-code}\napartments\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,460 × 2\n   GrLivArea SalePrice\n       <dbl>     <dbl>\n 1      1710    208500\n 2      1262    181500\n 3      1786    223500\n 4      1717    140000\n 5      2198    250000\n 6      1362    143000\n 7      1694    307000\n 8      2090    200000\n 9      1774    129900\n10      1077    118000\n# ℹ 1,450 more rows\n```\n\n\n:::\n:::\n\n\n### First 10 rows of the Apartments dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\napartments %>% \n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 2\n   GrLivArea SalePrice\n       <dbl>     <dbl>\n 1      1710    208500\n 2      1262    181500\n 3      1786    223500\n 4      1717    140000\n 5      2198    250000\n 6      1362    143000\n 7      1694    307000\n 8      2090    200000\n 9      1774    129900\n10      1077    118000\n```\n\n\n:::\n:::\n\n\nThe first 10 rows of the apartments dataset provide details of apartments based on two key variables: GrLivArea (above-ground living area in square feet) and SalePrice (the sale price in US dollars). The data shows a range of living areas from 1,077 to 2,198 square feet, with corresponding sale prices ranging from \\$118,000 to \\$307,000. The dataset highlights variations in apartment sizes and their market prices, suggesting that larger apartments tend to have higher sale prices. This provides a preliminary glimpse into how apartment size might influence property pricing.\n\n### Glimpse - apartments dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(apartments)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,460\nColumns: 2\n$ GrLivArea <dbl> 1710, 1262, 1786, 1717, 2198, 1362, 1694, 2090, 1774, 1077, …\n$ SalePrice <dbl> 208500, 181500, 223500, 140000, 250000, 143000, 307000, 2000…\n```\n\n\n:::\n:::\n\n\nThe glimpse gives an overview of the relationship between the living area and sale price for different apartments.\n\n### Inspect - apartments dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninspect(apartments)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nquantitative variables:  \n       name   class   min       Q1 median        Q3    max       mean\n1 GrLivArea numeric   334   1129.5   1464   1776.75   5642   1515.464\n2 SalePrice numeric 34900 129975.0 163000 214000.00 755000 180921.196\n          sd    n missing\n1   525.4804 1460       0\n2 79442.5029 1460       0\n```\n\n\n:::\n:::\n\n\nThe ground living area ranges from 334 to 5,642 square feet, with a median of 1,464 square feet and an average of 1,515 square feet. The sale prices vary from \\$34,900 to \\$755,000, with a median price of \\$163,000 and an average price of around \\$180,921. The inspection shows a substantial spread in both the living areas and the sale prices of apartments, as indicated by the large standard deviations.\n\n### Skim - apartments dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nskim(apartments)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |apartments |\n|Number of rows           |1460       |\n|Number of columns        |2          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|numeric                  |2          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|      mean|       sd|    p0|      p25|    p50|       p75|   p100|hist  |\n|:-------------|---------:|-------------:|---------:|--------:|-----:|--------:|------:|---------:|------:|:-----|\n|GrLivArea     |         0|             1|   1515.46|   525.48|   334|   1129.5|   1464|   1776.75|   5642|▇▇▁▁▁ |\n|SalePrice     |         0|             1| 180921.20| 79442.50| 34900| 129975.0| 163000| 214000.00| 755000|▇▅▁▁▁ |\n\n\n:::\n:::\n\n\nThe skim summary of the apartments dataset shows that there are no missing values in either of the two variables, GrLivArea and SalePrice. The dataset has a complete rate of 1 for both variables. The mean ground living area is 1,515.464 square feet with a standard deviation of 525.4804, indicating variation in apartment sizes. Similarly, the mean sale price is \\$180,921.20 with a higher standard deviation of \\$79,442.50, reflecting significant variability in apartment prices.\n\n### Data Dictionary\n\n**Quantitative Data**\n\n-   **GrLivArea (dbl)**: The above-ground living area in square feet for each apartment.\n\n-   **SalePrice (dbl)**: The sale price of the apartment in US dollars.\n\n### What is the average sale price of the apartments?\n\n\n::: {.cell}\n\n```{.r .cell-code}\navg_sale_price <- mean(apartments$SalePrice, na.rm = TRUE)\navg_sale_price\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 180921.2\n```\n\n\n:::\n:::\n\n\nThe average sale price of the apartments in the dataset is approximately \\$180,921.2. This figure is calculated by taking the mean of the SalePrice column, which represents the sale prices of the apartments.\n\n### How do sale prices vary by quartiles?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(apartments$SalePrice, probs = c(0.25, 0.5, 0.75), na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   25%    50%    75% \n129975 163000 214000 \n```\n\n\n:::\n:::\n\n\nThis means that 25% of the apartments have a sale price below \\$129,975, 50% are below \\$163,000, and 75% are below \\$214,000.\n\n### What is the typical size of an apartment in terms of living area?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmedian(apartments$GrLivArea, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1464\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(apartments$GrLivArea, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1515.464\n```\n\n\n:::\n:::\n\n\nThese values suggest that most apartments have a living area close to these sizes, with the median indicating the middle value and the mean reflecting the average size across the dataset.\n\n### What is the distribution of living area sizes?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_histogram(~ GrLivArea, data = apartments, binwidth = 100, \n             color = \"green\", alpha = 0.6) %>%\n  gf_labs(title = \"Distribution of Living Area Sizes\", \n          x = \"Living Area (sq ft)\", \n          y = \"Count\") %>%\n  gf_theme(theme_minimal())\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\nThe majority of apartments have a living area between 1,000 and 2,500 square feet, with a peak around 1,500 to 2,000 square feet. There are fewer apartments with very small or very large living areas, and the distribution shows a right-skew, with a small number of larger apartments exceeding 3,000 square feet. This suggests that most apartments in the dataset fall within the mid-range of living areas.\n\n### How frequently do apartments of different living area sizes occur?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_histogram(~ GrLivArea, data = apartments, fill = \"red\", bins = 50) %>%\n  gf_labs(x = \"Living Area (sqft)\", y = \"Count\", title = \"Frequency of Different Living Area Sizes\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\nMost apartments have living areas between 1,000 and 2,000 square feet, with a noticeable peak around 1,500 to 2,000 square feet. As the living area increases beyond 2,500 square feet, the frequency of apartments decreases significantly. Few apartments have living areas larger than 3,500 square feet, indicating that larger apartments are much less common.\n\n### What is the price per square foot of the apartments, and how does it vary?\n\n\n::: {.cell}\n\n```{.r .cell-code}\napartments$PricePerSqFt <- apartments$SalePrice / apartments$GrLivArea\ngf_histogram(~ PricePerSqFt, data = apartments, bins = 50, fill = \"yellow\", color = \"orange\") %>%\n  gf_labs(x = \"Price per Square Foot\", y = \"Count\", title = \"Distribution of Price per Square Foot\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n\n```{.r .cell-code}\nsummary(apartments$PricePerSqFt)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  28.36   99.82  120.10  120.57  138.70  276.25 \n```\n\n\n:::\n:::\n\n\nMost apartments are priced between \\$75 and \\$125 per square foot, with the highest concentration just below \\$100. As the price per square foot increases beyond \\$150, the frequency decreases significantly, with very few apartments exceeding \\$200 per square foot. This indicates that the majority of apartments are within a mid-range price, with fewer properties being priced at the higher end.\n\n### Look at the Fertility dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfert <- read_csv(\"../../data/Fertility.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 254654 Columns: 9\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (6): morekids, gender1, gender2, afam, hispanic, other\ndbl (3): rownames, age, work\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\nfert\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 254,654 × 9\n   rownames morekids gender1 gender2   age afam  hispanic other  work\n      <dbl> <chr>    <chr>   <chr>   <dbl> <chr> <chr>    <chr> <dbl>\n 1        1 no       male    female     27 no    no       no        0\n 2        2 no       female  male       30 no    no       no       30\n 3        3 no       male    female     27 no    no       no        0\n 4        4 no       male    female     35 yes   no       no        0\n 5        5 no       female  female     30 no    no       no       22\n 6        6 no       male    female     26 no    no       no       40\n 7        7 no       female  male       29 no    no       no        0\n 8        8 no       male    male       33 no    no       no       52\n 9        9 no       female  male       29 no    no       no        0\n10       10 no       male    female     27 no    no       no        0\n# ℹ 254,644 more rows\n```\n\n\n:::\n:::\n\n\nThe Fertility dataset consists of 254,654 rows and 9 columns, capturing demographic and work-related information. It includes both quantitative and qualitative variables. The quantitative data, such as age and work experience, shows that the individuals range in age from 26 to 35, with work experience varying between 0 to 52 years. The qualitative data provides insights into factors like gender (gender1, gender2), ethnicity (African American, Hispanic, and other ethnicities), and whether individuals have more children (morekids).\n\n### First 10 rows of the Fertility dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfert %>% \n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 9\n   rownames morekids gender1 gender2   age afam  hispanic other  work\n      <dbl> <chr>    <chr>   <chr>   <dbl> <chr> <chr>    <chr> <dbl>\n 1        1 no       male    female     27 no    no       no        0\n 2        2 no       female  male       30 no    no       no       30\n 3        3 no       male    female     27 no    no       no        0\n 4        4 no       male    female     35 yes   no       no        0\n 5        5 no       female  female     30 no    no       no       22\n 6        6 no       male    female     26 no    no       no       40\n 7        7 no       female  male       29 no    no       no        0\n 8        8 no       male    male       33 no    no       no       52\n 9        9 no       female  male       29 no    no       no        0\n10       10 no       male    female     27 no    no       no        0\n```\n\n\n:::\n:::\n\n\nThe first 10 rows of the Fertility dataset provide a snapshot of individuals, focusing on whether they desire more children (\"morekids\"), gender roles of both partners (\"gender1\" and \"gender2\"), age, ethnicity (whether they are African American \"afam\" or Hispanic), and work experience. The data shows a mix of individuals with varying work experience, ranging from 0 to 52 years, and includes demographic details such as gender and ethnicity. Most individuals in these first 10 rows do not desire more children.\n\n### Glimpse - Fertility Dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(fert)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 254,654\nColumns: 9\n$ rownames <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18…\n$ morekids <chr> \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"…\n$ gender1  <chr> \"male\", \"female\", \"male\", \"male\", \"female\", \"male\", \"female\",…\n$ gender2  <chr> \"female\", \"male\", \"female\", \"female\", \"female\", \"female\", \"ma…\n$ age      <dbl> 27, 30, 27, 35, 30, 26, 29, 33, 29, 27, 28, 28, 35, 34, 32, 2…\n$ afam     <chr> \"no\", \"no\", \"no\", \"yes\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", …\n$ hispanic <chr> \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"…\n$ other    <chr> \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"…\n$ work     <dbl> 0, 30, 0, 0, 22, 40, 0, 52, 0, 0, 0, 52, 52, 52, 8, 7, 0, 40,…\n```\n\n\n:::\n:::\n\n\nThe glimpse gives a quick summary of the structure of the data, highlighting the types of variables and their initial values.\n\n### Inspect - Fertility Dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninspect(fert)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\ncategorical variables:  \n      name     class levels      n missing\n1 morekids character      2 254654       0\n2  gender1 character      2 254654       0\n3  gender2 character      2 254654       0\n4     afam character      2 254654       0\n5 hispanic character      2 254654       0\n6    other character      2 254654       0\n                                   distribution\n1 no (61.9%), yes (38.1%)                      \n2 male (51.4%), female (48.6%)                 \n3 male (51.3%), female (48.7%)                 \n4 no (94.8%), yes (5.2%)                       \n5 no (92.6%), yes (7.4%)                       \n6 no (94.4%), yes (5.6%)                       \n\nquantitative variables:  \n      name   class min       Q1   median       Q3    max         mean\n1 rownames numeric   1 63664.25 127327.5 190990.8 254654 127327.50000\n2      age numeric  21    28.00     31.0     33.0     35     30.39327\n3     work numeric   0     0.00      5.0     44.0     52     19.01833\n            sd      n missing\n1 73512.422063 254654       0\n2     3.386447 254654       0\n3    21.867277 254654       0\n```\n\n\n:::\n:::\n\n\nThe categorical variables capture demographic information, such as whether an individual has more children (with 61.9% indicating \"no\" and 38.1% indicating \"yes\"), the gender of the parents (roughly evenly split between male and female), and ethnic background (with 94.8% identifying as non-African American and 92.6% identifying as non-Hispanic). The quantitative variables include age, with a median of 31 years and a range from 21 to 35 years, and hours worked per week, with a median of 5 hours and a range extending up to 52 hours. This dataset provides a broad demographic and work-related profile of individuals.\n\n### Skim - Fertility Dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nskim(fert)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |       |\n|:------------------------|:------|\n|Name                     |fert   |\n|Number of rows           |254654 |\n|Number of columns        |9      |\n|_______________________  |       |\n|Column type frequency:   |       |\n|character                |6      |\n|numeric                  |3      |\n|________________________ |       |\n|Group variables          |None   |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|morekids      |         0|             1|   2|   3|     0|        2|          0|\n|gender1       |         0|             1|   4|   6|     0|        2|          0|\n|gender2       |         0|             1|   4|   6|     0|        2|          0|\n|afam          |         0|             1|   2|   3|     0|        2|          0|\n|hispanic      |         0|             1|   2|   3|     0|        2|          0|\n|other         |         0|             1|   2|   3|     0|        2|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|      mean|       sd| p0|      p25|      p50|      p75|   p100|hist  |\n|:-------------|---------:|-------------:|---------:|--------:|--:|--------:|--------:|--------:|------:|:-----|\n|rownames      |         0|             1| 127327.50| 73512.42|  1| 63664.25| 127327.5| 190990.8| 254654|▇▇▇▇▇ |\n|age           |         0|             1|     30.39|     3.39| 21|    28.00|     31.0|     33.0|     35|▁▃▅▇▇ |\n|work          |         0|             1|     19.02|    21.87|  0|     0.00|      5.0|     44.0|     52|▇▁▁▁▃ |\n\n\n:::\n:::\n\n\nFrom the skim summary, the dataset has no missing values across all columns. The age of individuals in the dataset ranges from 21 to 35 years, with a mean of approximately 30. The work variable ranges from 0 to 52, with a mean value of around 19, indicating a spread of work hours or some related measurement.\n\n### Data Dictionary\n\n### Quantitative Data:\n\n-   **rowname (dbl)**: The index or row number of the dataset.\n\n-   **age (dbl)**: The age of individuals in the dataset.\n\n-   **work (dbl)**: The number of years the individuals have worked.\n\n### Qualitative Data:\n\n-   **morekids (chr)**: Indicates whether the individual has more kids (e.g., yes, no).\n\n-   **gender1 (chr)**: The gender of the individual (e.g., male, female).\n\n-   **gender2 (chr)**: Another column representing gender (e.g., male, female).\n\n-   **afam (chr)**: Indicates African American status (e.g., yes, no).\n\n-   **hispanic (chr)**: Indicates Hispanic ethnicity (e.g., yes, no).\n\n-   **other (chr)**: Indicates whether the individual belongs to another ethnic group (e.g., yes, no).\n\n### What is the distribution of ages?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_bar(~ age, data = fert, bins = 30, fill = \"purple\") %>%\n  gf_labs(x = \"Age\", y = \"Count\", title = \"Distribution of Age\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n:::\n\n\nThe distribution of ages in the fertility dataset shows that the majority of individuals fall between the ages of 25 and 35. There is a noticeable peak around the ages of 30 to 33, where the count of individuals reaches its highest point. The dataset contains fewer individuals under the age of 25 and over the age of 35, indicating a concentration of respondents in their late 20s to early 30s. This histogram suggests that the dataset primarily includes individuals in this middle age range, which could be typical for studies related to fertility.\n\n### What is the proportion of individuals with more children?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_bar(~ morekids, data = fert, fill = \"lightgreen\") %>%\n  gf_labs(x = \"More Children\", y = \"Count\", title = \"Proportion of Individuals with More Children\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n:::\n\n\nA larger portion of individuals, over 150,000, indicated that they do not have more children, while a smaller group, approximately 100,000, reported having more children. This indicates that the majority of respondents do not have additional children compared to those who do. The distribution suggests a notable difference between the two groups, with fewer individuals opting for more children.\n\n### What is the distribution of work hours across individuals?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_histogram(~ work, data = fert, bins = 20, fill = \"orange\") %>%\n  gf_labs(x = \"Work Hours\", y = \"Count\", title = \"Distribution of Work Hours\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-45-1.png){width=672}\n:::\n:::\n\n\nThe histogram illustrates the distribution of work hours across individuals. A significant proportion of the individuals report zero work hours, as seen by the large spike at the beginning of the graph. There are also smaller groups of individuals with higher work hours, particularly around the 40-hour mark, which is typically considered a full-time workload. This suggests that many individuals in the dataset do not work, while those who do often work around 40 hours per week. The distribution is heavily skewed toward the lower end of the work hours scale.\n\n### What is the gender distribution?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_props(~ gender1, data = fert, fill = \"lightblue\") %>%\n  gf_labs(x = \"Gender 1\", y = \"Count\", title = \"Gender 1 Distribution\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-46-1.png){width=672}\n:::\n\n```{.r .cell-code}\ngf_props(~ gender2, data = fert, fill = \"darkblue\") %>%\n  gf_labs(x = \"Gender 2\", y = \"Count\", title = \"Gender 2 Distribution\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-46-2.png){width=672}\n:::\n:::\n\n\nThe fertility dataset presents a balanced distribution of genders across both the Gender 1 and Gender 2 categories. In both groups, males and females are represented almost equally, as shown by the bar charts. The proportion of males in Gender 1 is slightly higher at 51.4%, while the proportion of females is 48.6%. Similarly, in Gender 2, the male proportion is 51.3%, with females comprising 48.7%. This even distribution highlights that gender representation is fairly uniform within the dataset, providing a balanced basis for further analysis regarding gender-related variables.\n\n### What is the ethnicity distribution?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_bar(~ afam, data = fert, fill = \"lightpink\") %>%\n  gf_labs(x = \"African American\", y = \"Count\", title = \"African American Status Distribution\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-47-1.png){width=672}\n:::\n\n```{.r .cell-code}\ngf_bar(~ hispanic, data = fert, fill = \"violet\") %>%\n  gf_labs(x = \"Hispanic\", y = \"Count\", title = \"Hispanic Status Distribution\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-47-2.png){width=672}\n:::\n:::\n\n\nThe two graphs show the distribution of African American and Hispanic statuses within the dataset. For both variables, the majority of individuals are classified as \"no,\" indicating they are not African American or Hispanic, while a smaller proportion is classified as \"yes,\" indicating they are. This suggests that the dataset has a relatively low representation of both African American and Hispanic individuals.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}