<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Khushi">

<title>Data-As-Material - Assignment 2 - Part 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Data-As-Material</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Assignment 2 - Part 2</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Assignments</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Khushi </p>
            </div>
    </div>
      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>This is Part 2 of Assignment 2.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'mosaic':
  method                           from   
  fortify.SpatialPolygonsDataFrame ggplot2

The 'mosaic' package masks several functions from core packages in order to add 
additional features.  The original behavior of these functions should not be affected by this.

Attaching package: 'mosaic'

The following object is masked from 'package:Matrix':

    mean

The following objects are masked from 'package:dplyr':

    count, do, tally

The following object is masked from 'package:purrr':

    cross

The following object is masked from 'package:ggplot2':

    stat

The following objects are masked from 'package:stats':

    binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,
    quantile, sd, t.test, var

The following objects are masked from 'package:base':

    max, mean, min, prod, range, sample, sum</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'skimr'

The following object is masked from 'package:mosaic':

    n_missing</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggformula)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="dataset---gender-at-the-work-place" class="level3">
<h3 class="anchored" data-anchor-id="dataset---gender-at-the-work-place">Dataset - <strong>Gender at the Work Place</strong></h3>
<p>This is a dataset pertaining to gender and compensation at the workplace.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>job_gender <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"../../data/job_gender_data.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat &lt;- vroom(...)
  problems(dat)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 32 Columns: 1
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): year;occupation;major_category;minor_category;total_workers;workers...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>job_gender</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 32 × 1
   year;occupation;major_category;minor_category;total_workers;workers_male;wo…¹
   &lt;chr&gt;                                                                        
 1 2016;Dietitians and nutritionists;Healthcare Practitioners and Technical;Hea…
 2 2016;Medical records and health information technicians;Healthcare Practitio…
 3 2016;Pharmacists;Healthcare Practitioners and Technical;Healthcare Practitio…
 4 2016;Licensed practical and licensed vocational nurses;Healthcare Practition…
 5 2016;Miscellaneous therapists, including exercise physiologists;Healthcare P…
 6 2016;Clinical laboratory technologists and technicians;Healthcare Practition…
 7 2016;Registered nurses;Healthcare Practitioners and Technical;Healthcare Pra…
 8 2016;Nurse practitioners;Healthcare Practitioners and Technical;Healthcare P…
 9 2016;Physician assistants;Healthcare Practitioners and Technical;Healthcare …
10 2016;Health practitioner support technologists and technicians;Healthcare Pr…
# ℹ 22 more rows
# ℹ abbreviated name:
#   ¹​`year;occupation;major_category;minor_category;total_workers;workers_male;workers_female;percent_female;total_earnings;total_earnings_male;total_earnings_female;wage_percent_of_male`</code></pre>
</div>
</div>
</section>
<section id="specifying-delimiter" class="level3">
<h3 class="anchored" data-anchor-id="specifying-delimiter">Specifying Delimiter</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>job_gender <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="at">file=</span><span class="st">"../../data/job_gender_data.csv"</span>,<span class="at">delim =</span><span class="st">";"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 32 Columns: 12
── Column specification ────────────────────────────────────────────────────────
Delimiter: ";"
chr (3): occupation, major_category, minor_category
dbl (7): year, total_workers, workers_male, workers_female, total_earnings, ...
num (2): percent_female, wage_percent_of_male

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>job_gender</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 32 × 12
    year occupation     major_category minor_category total_workers workers_male
   &lt;dbl&gt; &lt;chr&gt;          &lt;chr&gt;          &lt;chr&gt;                  &lt;dbl&gt;        &lt;dbl&gt;
 1  2016 Dietitians an… Healthcare Pr… Healthcare Pr…         70729         8095
 2  2016 Medical recor… Healthcare Pr… Healthcare Pr…        148302        14938
 3  2016 Pharmacists    Healthcare Pr… Healthcare Pr…        214665        97539
 4  2016 Licensed prac… Healthcare Pr… Healthcare Pr…        602316        77484
 5  2016 Miscellaneous… Healthcare Pr… Healthcare Pr…        107797        25250
 6  2016 Clinical labo… Healthcare Pr… Healthcare Pr…        245278        68887
 7  2016 Registered nu… Healthcare Pr… Healthcare Pr…       2317493       281048
 8  2016 Nurse practit… Healthcare Pr… Healthcare Pr…        116166        14128
 9  2016 Physician ass… Healthcare Pr… Healthcare Pr…         76018        27869
10  2016 Health practi… Healthcare Pr… Healthcare Pr…        440607        98824
# ℹ 22 more rows
# ℹ 6 more variables: workers_female &lt;dbl&gt;, percent_female &lt;dbl&gt;,
#   total_earnings &lt;dbl&gt;, total_earnings_male &lt;dbl&gt;,
#   total_earnings_female &lt;dbl&gt;, wage_percent_of_male &lt;dbl&gt;</code></pre>
</div>
</div>
<p>The dataset includes columns such as total workers, the distribution of male and female workers, total earnings (segregated by gender), and wage comparisons between male and female workers. It categorizes these occupations under a major category called “Healthcare Practitioners and Technical,” which is further divided into specific occupations like dietitians, registered nurses, and nurse practitioners. The dataset highlights gender disparities in these healthcare roles by comparing the number of male and female workers, their respective earnings, and the proportion of female workers in each role. It provides insights into wage differences, showing a column indicating how female earnings compare to male earnings (wage_percent_of_male).</p>
</section>
<section id="first-10-rows-of-the-gender-at-the-work-place-dataset" class="level3">
<h3 class="anchored" data-anchor-id="first-10-rows-of-the-gender-at-the-work-place-dataset">First 10 rows of the <strong>Gender at the Work Place</strong> dataset</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>job_gender <span class="sc">%&gt;%</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 12
    year occupation     major_category minor_category total_workers workers_male
   &lt;dbl&gt; &lt;chr&gt;          &lt;chr&gt;          &lt;chr&gt;                  &lt;dbl&gt;        &lt;dbl&gt;
 1  2016 Dietitians an… Healthcare Pr… Healthcare Pr…         70729         8095
 2  2016 Medical recor… Healthcare Pr… Healthcare Pr…        148302        14938
 3  2016 Pharmacists    Healthcare Pr… Healthcare Pr…        214665        97539
 4  2016 Licensed prac… Healthcare Pr… Healthcare Pr…        602316        77484
 5  2016 Miscellaneous… Healthcare Pr… Healthcare Pr…        107797        25250
 6  2016 Clinical labo… Healthcare Pr… Healthcare Pr…        245278        68887
 7  2016 Registered nu… Healthcare Pr… Healthcare Pr…       2317493       281048
 8  2016 Nurse practit… Healthcare Pr… Healthcare Pr…        116166        14128
 9  2016 Physician ass… Healthcare Pr… Healthcare Pr…         76018        27869
10  2016 Health practi… Healthcare Pr… Healthcare Pr…        440607        98824
# ℹ 6 more variables: workers_female &lt;dbl&gt;, percent_female &lt;dbl&gt;,
#   total_earnings &lt;dbl&gt;, total_earnings_male &lt;dbl&gt;,
#   total_earnings_female &lt;dbl&gt;, wage_percent_of_male &lt;dbl&gt;</code></pre>
</div>
</div>
<p>The first ten rows of the “Gender at the Workplace” dataset focus on healthcare-related occupations in 2016. These occupations include roles like “Dietitians and Nutritionists,” “Pharmacists,” and “Registered Nurses.” For example, there are 70,729 total workers in the “Dietitians and Nutritionists” category, with 8,095 males and 62,634 females, making females account for roughly 88.55% of this workforce. Similarly, “Registered Nurses” have a workforce of 2,036,445 individuals, of which 281,048 are males and 1,755,397 are females, showing a dominant female representation at 87.87%. In terms of earnings, male registered nurses earn an average of $64,413 compared to females who earn $64,119, with female wages being approximately 99.78% of male wages in this occupation.</p>
</section>
<section id="glimpse---job_gender" class="level3">
<h3 class="anchored" data-anchor-id="glimpse---job_gender">Glimpse - job_gender</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(job_gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 32
Columns: 12
$ year                  &lt;dbl&gt; 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, …
$ occupation            &lt;chr&gt; "Dietitians and nutritionists", "Medical records…
$ major_category        &lt;chr&gt; "Healthcare Practitioners and Technical", "Healt…
$ minor_category        &lt;chr&gt; "Healthcare Practitioners and Technical", "Healt…
$ total_workers         &lt;dbl&gt; 70729, 148302, 214665, 602316, 107797, 245278, 2…
$ workers_male          &lt;dbl&gt; 8095, 14938, 97539, 77484, 25250, 68887, 281048,…
$ workers_female        &lt;dbl&gt; 62634, 133364, 117126, 524832, 82547, 176391, 20…
$ percent_female        &lt;dbl&gt; 8.855491e+14, 8.992731e+14, 5.456222e+14, 8.7135…
$ total_earnings        &lt;dbl&gt; 49841, 38273, 120878, 38946, 50208, 48170, 65331…
$ total_earnings_male   &lt;dbl&gt; 47439, 37208, 122351, 40939, 52202, 51112, 70952…
$ total_earnings_female &lt;dbl&gt; 49886, 38404, 118461, 38523, 48955, 46984, 64413…
$ wage_percent_of_male  &lt;dbl&gt; 1.051582e+15, 1.032144e+15, 9.682062e+14, 9.4098…</code></pre>
</div>
</div>
<p>The glimpse of the dataset “job_gender” provides an overview of the 32 rows and 12 columns in the job_gender dataset.</p>
</section>
<section id="inspect---job_gender" class="level3">
<h3 class="anchored" data-anchor-id="inspect---job_gender">Inspect - job_gender</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">inspect</span>(job_gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
categorical variables:  
            name     class levels  n missing
1     occupation character     32 32       0
2 major_category character      1 32       0
3 minor_category character      1 32       0
                                   distribution
1 Audiologists (3.1%) ...                      
2  (%) ...                                     
3  (%) ...                                     

quantitative variables:  
                   name   class          min           Q1       median
1                  year numeric 2.016000e+03 2.016000e+03 2.016000e+03
2         total_workers numeric 4.001000e+03 3.750350e+04 8.978400e+04
3          workers_male numeric 0.000000e+00 7.437000e+03 2.608100e+04
4        workers_female numeric 9.530000e+02 1.375975e+04 5.753250e+04
5        percent_female numeric 1.564090e+14 5.738413e+14 6.703936e+14
6        total_earnings numeric 3.246600e+04 4.942325e+04 6.443150e+04
7   total_earnings_male numeric 3.609300e+04 5.111500e+04 7.095200e+04
8 total_earnings_female numeric 3.209300e+04 4.846225e+04 6.012800e+04
9  wage_percent_of_male numeric 6.643337e+14 8.020231e+14 8.666381e+14
            Q3          max         mean           sd  n missing
1 2.016000e+03 2.016000e+03 2.016000e+03 0.000000e+00 32       0
2 1.637307e+05 2.317493e+06 2.049671e+05 4.208274e+05 32       0
3 6.672025e+04 4.897480e+05 5.645797e+04 9.613719e+04 32       0
4 1.060613e+05 2.036445e+06 1.485091e+05 3.617156e+05 32       0
5 8.657607e+14 1.000000e+15 6.517922e+14 2.274756e+14 32       0
6 1.008672e+05 2.015420e+05 7.792281e+04 4.053443e+04 32       0
7 1.073760e+05 2.314200e+05 8.478716e+04 4.538677e+04 31       1
8 1.001310e+05 1.663880e+05 7.166166e+04 3.405611e+04 32       0
9 9.106884e+14 1.051582e+15 8.581675e+14 1.008336e+14 24       8</code></pre>
</div>
</div>
<p>The mean values for total workers range from 40,010 to over 2.05 million, showing the average number of workers in each occupation. The median total earnings for male workers is around 36,093 to 122,351, whereas for female workers, it ranges from 32,093 to 118,461, reflecting wage disparities. The standard deviation (sd) for total earnings across workers is also high, with a maximum value of over 4.05e+05, indicating significant variation in earnings. Additionally, wage_percent_of_male shows the mean wage gap, ranging from 6.64e+14 to 1.05e+15, reflecting the earnings of female workers as a percentage of male workers’ earnings. These statistics highlight key insights into the gender wage gap and employment distribution.</p>
</section>
<section id="skim---job_gender" class="level3">
<h3 class="anchored" data-anchor-id="skim---job_gender">Skim - job_gender</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(job_gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">job_gender</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">32</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">12</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">character</td>
<td style="text-align: left;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">9</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 20%">
<col style="width: 13%">
<col style="width: 19%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">empty</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: right;">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">occupation</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">58</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">major_category</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">minor_category</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 15%">
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">year</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2.016000e+03</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">2.016000e+03</td>
<td style="text-align: right;">2.016000e+03</td>
<td style="text-align: right;">2.016000e+03</td>
<td style="text-align: right;">2.016000e+03</td>
<td style="text-align: right;">2.016000e+03</td>
<td style="text-align: left;">▁▁▇▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">total_workers</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2.049671e+05</td>
<td style="text-align: right;">4.208275e+05</td>
<td style="text-align: right;">4.001000e+03</td>
<td style="text-align: right;">3.750350e+04</td>
<td style="text-align: right;">8.978400e+04</td>
<td style="text-align: right;">1.637307e+05</td>
<td style="text-align: right;">2.317493e+06</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">workers_male</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">5.645797e+04</td>
<td style="text-align: right;">9.613719e+04</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">7.437000e+03</td>
<td style="text-align: right;">2.608100e+04</td>
<td style="text-align: right;">6.672025e+04</td>
<td style="text-align: right;">4.897480e+05</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">workers_female</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.485091e+05</td>
<td style="text-align: right;">3.617156e+05</td>
<td style="text-align: right;">9.530000e+02</td>
<td style="text-align: right;">1.375975e+04</td>
<td style="text-align: right;">5.753250e+04</td>
<td style="text-align: right;">1.060613e+05</td>
<td style="text-align: right;">2.036445e+06</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">percent_female</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">6.517922e+14</td>
<td style="text-align: right;">2.274756e+14</td>
<td style="text-align: right;">1.564090e+14</td>
<td style="text-align: right;">5.738413e+14</td>
<td style="text-align: right;">6.703936e+14</td>
<td style="text-align: right;">8.657607e+14</td>
<td style="text-align: right;">1.000000e+15</td>
<td style="text-align: left;">▃▂▇▇▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">total_earnings</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">7.792281e+04</td>
<td style="text-align: right;">4.053443e+04</td>
<td style="text-align: right;">3.246600e+04</td>
<td style="text-align: right;">4.942325e+04</td>
<td style="text-align: right;">6.443150e+04</td>
<td style="text-align: right;">1.008672e+05</td>
<td style="text-align: right;">2.015420e+05</td>
<td style="text-align: left;">▇▃▃▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">total_earnings_male</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">8.478716e+04</td>
<td style="text-align: right;">4.538677e+04</td>
<td style="text-align: right;">3.609300e+04</td>
<td style="text-align: right;">5.111500e+04</td>
<td style="text-align: right;">7.095200e+04</td>
<td style="text-align: right;">1.073760e+05</td>
<td style="text-align: right;">2.314200e+05</td>
<td style="text-align: left;">▇▃▂▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">total_earnings_female</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">7.166166e+04</td>
<td style="text-align: right;">3.405611e+04</td>
<td style="text-align: right;">3.209300e+04</td>
<td style="text-align: right;">4.846225e+04</td>
<td style="text-align: right;">6.012800e+04</td>
<td style="text-align: right;">1.001310e+05</td>
<td style="text-align: right;">1.663880e+05</td>
<td style="text-align: left;">▇▃▂▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">wage_percent_of_male</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">8.581675e+14</td>
<td style="text-align: right;">1.008336e+14</td>
<td style="text-align: right;">6.643337e+14</td>
<td style="text-align: right;">8.020231e+14</td>
<td style="text-align: right;">8.666381e+14</td>
<td style="text-align: right;">9.106884e+14</td>
<td style="text-align: right;">1.051582e+15</td>
<td style="text-align: left;">▅▂▇▇▂</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The dataset contains three categorical variables—occupation, major_category, and minor_category—and nine numeric variables, such as total_workers, workers_male, workers_female, total_earnings, and others. No missing values were reported for any of the variables except wage_percent_of_male, which has eight missing entries. The numeric variables like total_workers have a mean of 204,967.1 and a median of 89,784, while the standard deviation is quite high, indicating significant variation in the total number of workers across different occupations. The distribution of workers and their earnings, particularly between males and females, highlights differences in wages, with wage_percent_of_male indicating that females generally earn 85.8% of what males do on average.</p>
</section>
<section id="data-dictionary" class="level3">
<h3 class="anchored" data-anchor-id="data-dictionary">Data Dictionary</h3>
<section id="quantitative-data" class="level4">
<h4 class="anchored" data-anchor-id="quantitative-data">Quantitative Data</h4>
<ul>
<li><p><strong>total_workers (dbl)</strong>: The total number of workers in the specified occupation.</p></li>
<li><p><strong>workers_male (dbl)</strong>: The number of male workers in the specified occupation.</p></li>
<li><p><strong>workers_female (dbl)</strong>: The number of female workers in the specified occupation.</p></li>
<li><p><strong>percent_female (dbl)</strong>: The percentage of female workers in the specified occupation.</p></li>
<li><p><strong>total_earnings (dbl)</strong>: The total earnings of all workers in the specified occupation.</p></li>
<li><p><strong>total_earnings_male (dbl)</strong>: The total earnings of male workers in the specified occupation.</p></li>
<li><p><strong>total_earnings_female (dbl)</strong>: The total earnings of female workers in the specified occupation.</p></li>
<li><p><strong>wage_percent_of_male (dbl)</strong>: The percentage of female earnings relative to male earnings in the specified occupation.</p></li>
<li><p><strong>year (dbl)</strong>: The year during which the data was collected.</p></li>
</ul>
</section>
<section id="qualitative-data" class="level4">
<h4 class="anchored" data-anchor-id="qualitative-data">Qualitative Data</h4>
<ul>
<li><p><strong>occupation (chr)</strong>: The specific job or profession.</p></li>
<li><p><strong>major_category (chr)</strong>: The broad category to which the occupation belongs.</p></li>
<li><p><strong>minor_category (chr)</strong>: The sub-category within the major category of the occupation.</p></li>
</ul>
</section>
</section>
<section id="target-variable" class="level3">
<h3 class="anchored" data-anchor-id="target-variable">Target Variable:</h3>
<p><strong>Wage Percent of Male</strong><br>
This is the key outcome of interest in the job_gender dataset as it indicates the earnings of female workers compared to male workers. Understanding this ratio can help assess the gender pay gap within different occupations. The goal of the analysis could be to identify the factors that influence wage disparity between male and female workers in various occupations.</p>
<p>The <strong>Wage Percent of Male</strong> is considered the target variable, rather than <strong>Percent Female</strong>, because it directly addresses the earnings gap between genders. <strong>Wage Percent of Male</strong> captures the outcome that most directly relates to gender pay gaps, making it the target variable for an analysis focused on wage equality. <strong>Percent Female</strong>, though important, only gives a snapshot of workforce composition and does not measure the disparity in pay.</p>
</section>
<section id="predictor-variables" class="level3">
<h3 class="anchored" data-anchor-id="predictor-variables">Predictor Variables:</h3>
<ul>
<li><p><strong>Total Workers</strong><br>
The total number of workers in an occupation might impact wage distribution. A larger workforce could lead to more standardized wages, whereas smaller, specialized occupations may have more variation in pay.</p></li>
<li><p><strong>Workers Male</strong><br>
The number of male workers in an occupation might be a predictor of wage levels, particularly if certain occupations are male-dominated.</p></li>
<li><p><strong>Workers Female</strong><br>
Similarly, the number of female workers in an occupation might influence wage structures, especially in occupations that are traditionally female-dominated.</p></li>
<li><p><strong>Percent Female</strong><br>
This variable reflects the percentage of females in the workforce and can help determine if occupations with a higher proportion of female workers tend to have lower wages compared to male-dominated fields.</p></li>
<li><p><strong>Total Earnings</strong><br>
The overall earnings in an occupation may indicate the earning potential, which could vary depending on how well the occupation is compensated regardless of gender.</p></li>
<li><p><strong>Total Earnings Male</strong><br>
This variable represents the total earnings of male workers, which could provide insight into wage differences when compared to female earnings.</p></li>
<li><p><strong>Total Earnings Female</strong><br>
The total earnings of female workers can be used to analyze how women’s pay compares to that of men within the same occupation.</p></li>
<li><p><strong>Year</strong><br>
The year the data was collected might reflect economic conditions, labor market trends, or changes in gender wage equality over time.</p></li>
<li><p><strong>Occupation</strong><br>
The specific job or profession can play a significant role in determining wage differences, as some occupations tend to have higher wage disparities than others.</p></li>
</ul>
</section>
<section id="research-experiment-gender-wage-gap-analysis-in-the-workplace" class="level3">
<h3 class="anchored" data-anchor-id="research-experiment-gender-wage-gap-analysis-in-the-workplace">Research Experiment: Gender Wage Gap Analysis in the Workplace</h3>
<p>The main objective of this research experiment could be to analyze and explore potential wage disparities between male and female workers across various occupations. The study might aim to understand how gender could affect earnings within different industries and roles, and what factors might contribute to wage inequality between male and female workers.</p>
<p>Several hypotheses could have been proposed:</p>
<ul>
<li><p>There could be a significant wage disparity between male and female workers in many occupations, where women might generally earn less than men for the same role.</p></li>
<li><p>The proportion of female workers in an occupation could influence wage disparity, with occupations having higher percentages of female workers potentially showing greater wage inequality.</p></li>
<li><p>Higher-paying occupations could demonstrate larger wage gaps between male and female workers.</p></li>
</ul>
<p>The study sampled various occupations across different industries, ensuring representation from male-dominated, female-dominated, and gender-balanced fields. The sample included both public and private sector workers, and data was stratified by occupation to allow for specific analysis of each role.</p>
<p><strong>Data Collection</strong>:</p>
<ul>
<li><p><strong>Primary Data Source</strong>: Employment and salary data could have been collected from government labor statistics databases, such as the Bureau of Labor Statistics (BLS), or other relevant sources. Surveys might have been conducted across various industries to gather detailed wage and gender data for different occupations.</p></li>
<li><p><strong>Survey Design</strong>: Structured surveys or administrative data might have been used to capture information about employee salaries, gender, and occupation. Employers or government agencies could have provided the data, which would then have been anonymized and aggregated by occupation.</p></li>
</ul>
<p><strong>Sampling</strong>:</p>
<ul>
<li>The study might have sampled a range of occupations across different industries, ensuring representation from male-dominated, female-dominated, and gender-balanced fields. The sample could have included both public and private sector workers, with data stratified by occupation to allow for specific analysis of each role.</li>
</ul>
<p><strong>Calculation of Variables</strong>:</p>
<ul>
<li><p><strong>Wage Percent of Male</strong> was calculated by dividing the average salary of female workers by the average salary of male workers for each occupation.</p></li>
<li><p><strong>Percent Female</strong> was calculated as the number of female workers divided by the total number of workers in each occupation.</p></li>
</ul>
<p>The experiment could aim to provide a comprehensive understanding of gender wage gaps across industries, potentially identifying which occupations exhibit the largest disparities and what factors (such as gender representation and occupation type) might contribute to wage inequality.</p>
</section>
<section id="calculating-the-median-salary" class="level3">
<h3 class="anchored" data-anchor-id="calculating-the-median-salary">Calculating the median salary</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>job_gender <span class="ot">&lt;-</span> job_gender <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">median_salary =</span> (total_earnings_male <span class="sc">+</span> total_earnings_female) <span class="sc">/</span> <span class="dv">2</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>job_gender</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 32 × 13
    year occupation     major_category minor_category total_workers workers_male
   &lt;dbl&gt; &lt;chr&gt;          &lt;chr&gt;          &lt;chr&gt;                  &lt;dbl&gt;        &lt;dbl&gt;
 1  2016 Dietitians an… Healthcare Pr… Healthcare Pr…         70729         8095
 2  2016 Medical recor… Healthcare Pr… Healthcare Pr…        148302        14938
 3  2016 Pharmacists    Healthcare Pr… Healthcare Pr…        214665        97539
 4  2016 Licensed prac… Healthcare Pr… Healthcare Pr…        602316        77484
 5  2016 Miscellaneous… Healthcare Pr… Healthcare Pr…        107797        25250
 6  2016 Clinical labo… Healthcare Pr… Healthcare Pr…        245278        68887
 7  2016 Registered nu… Healthcare Pr… Healthcare Pr…       2317493       281048
 8  2016 Nurse practit… Healthcare Pr… Healthcare Pr…        116166        14128
 9  2016 Physician ass… Healthcare Pr… Healthcare Pr…         76018        27869
10  2016 Health practi… Healthcare Pr… Healthcare Pr…        440607        98824
# ℹ 22 more rows
# ℹ 7 more variables: workers_female &lt;dbl&gt;, percent_female &lt;dbl&gt;,
#   total_earnings &lt;dbl&gt;, total_earnings_male &lt;dbl&gt;,
#   total_earnings_female &lt;dbl&gt;, wage_percent_of_male &lt;dbl&gt;,
#   median_salary &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="attempt-1" class="level3">
<h3 class="anchored" data-anchor-id="attempt-1">Attempt 1</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(median_salary <span class="sc">~</span> percent_female, </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">size =</span> <span class="sc">~</span> total_workers, </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> job_gender,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">fill =</span> <span class="st">"black"</span>, </span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">color =</span> <span class="st">"black"</span>, </span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">alpha =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Salaries and Gender Proportion in the Workforce"</span>,</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"% of workforce reported as female"</span>,</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Median salary in the occupation"</span></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_refine</span>(<span class="fu">scale_size_continuous</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">10</span>), <span class="at">guide =</span> <span class="fu">guide_legend</span>(<span class="at">title =</span> <span class="st">"Total # of workers"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="attempt-2" class="level3">
<h3 class="anchored" data-anchor-id="attempt-2">Attempt 2</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(median_salary <span class="sc">~</span> percent_female,</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">size =</span> <span class="sc">~</span> total_workers,</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> job_gender,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">fill =</span> <span class="st">"black"</span>,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">color =</span> <span class="st">"black"</span>,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">alpha =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Salaries and Gender Proportion in the Workforce"</span>,</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"% of workforce reported as female"</span>,</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Median salary in the occupation"</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_refine</span>(<span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">label_dollar</span>()))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In this step, I incorporated the use of the dollar sign for the y-axis scale, ensuring that the monetary values are clearly represented in the graph.</p>
</section>
<section id="attempt-3" class="level3">
<h3 class="anchored" data-anchor-id="attempt-3">Attempt 3</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(median_salary <span class="sc">~</span> percent_female, </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">size =</span> <span class="sc">~</span> total_workers, </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> job_gender, </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">fill =</span> <span class="st">"black"</span>, </span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">color =</span> <span class="st">"black"</span>, </span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">alpha =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Salaries and Gender Proportion in the Workforce"</span>,</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"% of workforce reported as female"</span>,</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Median salary in the occupation"</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>   <span class="fu">gf_refine</span>(<span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>()))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I attempted to implement percentages on the x-axis, but all the values ended up displaying as zero.</p>
</section>
<section id="attempt-4" class="level3">
<h3 class="anchored" data-anchor-id="attempt-4">Attempt 4</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(median_salary <span class="sc">~</span> percent_female,</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">size =</span> <span class="sc">~</span> total_workers,</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> job_gender,</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">fill =</span> <span class="st">"black"</span>,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">color =</span> <span class="st">"black"</span>,</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">alpha =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Salaries and Gender Proportion in the Workforce"</span>,</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"% of workforce reported as female"</span>,</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Median salary in the occupation"</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_refine</span>(</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>())</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 32 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I tried setting specific limits, but it caused all the bubble plots to shift to 0 percent.</p>
</section>
<section id="attempt-5" class="level3">
<h3 class="anchored" data-anchor-id="attempt-5">Attempt 5</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(median_salary <span class="sc">~</span> percent_female,</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="sc">~</span> total_workers,</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> job_gender,</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"black"</span>,</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"black"</span>,</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_labs</span>(</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Salaries and Gender Proportion in the Workforce"</span>,</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"% of workforce reported as female"</span>,</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Median salary in the occupation"</span></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_refine</span>(</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">label_dollar</span>()),</span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>())</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 32 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="attempt-6" class="level3">
<h3 class="anchored" data-anchor-id="attempt-6">Attempt 6</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>job_gender<span class="sc">$</span>percent_female <span class="ot">&lt;-</span> job_gender<span class="sc">$</span>percent_female <span class="sc">/</span> <span class="fl">1e14</span>  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(median_salary <span class="sc">~</span> percent_female,</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">size =</span> <span class="sc">~</span> total_workers,</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> job_gender,</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">fill =</span> <span class="st">"black"</span>,</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">color =</span> <span class="st">"black"</span>,</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">alpha =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Salaries and Gender Proportion in the Workforce"</span>,</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"% of workforce reported as female"</span>,</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Median salary in the occupation"</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_refine</span>(<span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">label_dollar</span>())) <span class="sc">%&gt;%</span></span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_refine</span>(</span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>())</span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 32 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="attempt-7" class="level3">
<h3 class="anchored" data-anchor-id="attempt-7">Attempt 7</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>job_gender <span class="ot">&lt;-</span> job_gender <span class="sc">%&gt;%</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percent_female =</span> percent_female <span class="sc">/</span> <span class="dv">100</span>)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(median_salary <span class="sc">~</span> percent_female,</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">size =</span> <span class="sc">~</span> total_workers,</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> job_gender,</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">fill =</span> <span class="st">"black"</span>,</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">color =</span> <span class="st">"black"</span>,</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">alpha =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Salaries and Gender Proportion in the Workforce"</span>,</span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"% of workforce reported as female"</span>,</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Median salary in the occupation"</span></span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_refine</span>(<span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">label_dollar</span>())) <span class="sc">%&gt;%</span></span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_refine</span>(<span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>()))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I attempted to mutate the percent female data, but it still displayed as 0 percent.</p>
</section>
<section id="attempt-8" class="level3">
<h3 class="anchored" data-anchor-id="attempt-8">Attempt 8</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(median_salary <span class="sc">~</span> percent_female,</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">size =</span> <span class="sc">~</span> total_workers,</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> job_gender,</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">fill =</span> <span class="st">"black"</span>,</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">color =</span> <span class="st">"black"</span>,</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">alpha =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Salaries and Gender Proportion in the Workforce"</span>,</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"% of workforce reported as female"</span>,</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Median salary in the occupation"</span></span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_refine</span>(<span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">label_dollar</span>())) <span class="sc">%&gt;%</span></span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_refine</span>(</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_continuous</span>(</span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.25</span>, <span class="fl">0.50</span>, <span class="fl">0.75</span>, <span class="dv">1</span>),</span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>()</span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I tried specifying breaks in the data, but the percentages disappeared altogether.</p>
</section>
<section id="attempt-9" class="level3">
<h3 class="anchored" data-anchor-id="attempt-9">Attempt 9</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>job_gender<span class="sc">$</span>percent_female <span class="ot">&lt;-</span> job_gender<span class="sc">$</span>percent_female <span class="sc">*</span> <span class="fl">1e2</span>  </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(median_salary <span class="sc">~</span> percent_female,</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">size =</span> <span class="sc">~</span> total_workers,</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> job_gender,</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">fill =</span> <span class="st">"black"</span>,</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">color =</span> <span class="st">"black"</span>,</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">alpha =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Salaries and Gender Proportion in the Workforce"</span>,</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"% of workforce reported as female"</span>,</span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Median salary in the occupation"</span></span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>  gf_refine</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">label_dollar</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">100</span>), <span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>(<span class="at">scale =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;ScaleContinuousPosition&gt;
 Range:  
 Limits:    0 --  100</code></pre>
</div>
</div>
<p>The numbers on the x-axis have changed and no longer match the originals in Attempt 1.</p>
</section>
<section id="attempt-10" class="level3">
<h3 class="anchored" data-anchor-id="attempt-10">Attempt 10</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>job_gender<span class="sc">$</span>percent_female <span class="ot">&lt;-</span> job_gender<span class="sc">$</span>percent_female <span class="sc">*</span> <span class="fl">1e2</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(median_salary <span class="sc">~</span> percent_female,</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">size =</span> <span class="sc">~</span> total_workers,</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> job_gender,</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">fill =</span> <span class="st">"black"</span>,</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">color =</span> <span class="st">"black"</span>,</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">alpha =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Salaries and Gender Proportion in the Workforce"</span>,</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"% of workforce reported as female"</span>,</span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Median salary in the occupation"</span></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_refine</span>(<span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">label_dollar</span>())) <span class="sc">%&gt;%</span></span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_refine</span>(</span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_continuous</span>(</span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>()</span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I spent about two hours trying to resolve the issue with the data showing 0 percent on the x-axis. Despite multiple attempts—ranging from adjusting the scale, specifying limits, mutating the percentage data, and setting breaks—nothing seemed to work. Each attempt either resulted in all the percentages remaining at 0 or caused the percentages to disappear entirely. Even when I tried different methods, the numbers on the axis shifted, and I still couldn’t get the correct percentages to display. It’s been frustrating, as no matter what I tried, the issue persists, and I haven’t been able to resolve it.</p>
</section>
<section id="questions" class="level3">
<h3 class="anchored" data-anchor-id="questions">Questions</h3>
<p>The graph titled “Salaries and Gender Proportion in the Workforce” seeks to answer the following questions:</p>
<p><strong>1.What is the relationship between salary levels and the proportion of females in various occupations?</strong></p>
<p>( The graph could aim to explore whether occupations with a higher percentage of female workers tend to offer lower salaries compared to male-dominated fields.)</p>
<ul>
<li>In the dataset, there seems to be a trend where occupations with a higher proportion of female workers tend to offer lower average salaries. For example, jobs such as <em>elementary school teachers</em> (where females represent a large portion of the workforce) have relatively lower wages compared to male-dominated fields like <em>engineering</em> or <em>management</em>, where salaries are significantly higher. This suggests a negative relationship between the proportion of female workers and salary levels.</li>
</ul>
<p><strong>2.How does gender representation in the workforce affect wage distribution across different job categories?</strong></p>
<p>( It may seek to analyze whether there is a noticeable correlation between the gender composition of an occupation and the wage gap, specifically examining how gender representation impacts salary levels in different sectors.)</p>
<ul>
<li>The data shows that occupations with more male representation tend to have higher salaries. For example, industries such as <em>construction</em> and <em>technology</em>, which are male-dominated, tend to have higher wages. On the other hand, female-dominated fields like <em>healthcare support</em> or <em>administrative services</em> exhibit lower wage levels, indicating a wage gap between gender representation in different sectors.</li>
</ul>
<p><strong>3.Which occupations exhibit significant disparities between the proportion of female workers and their salary levels?</strong></p>
<p>( The graph could identify which job categories have high female representation but lower salaries, highlighting potential areas of gender-based wage inequality.)</p>
<ul>
<li>A significant disparity is observed in roles like <em>nursing</em>, where there is a high proportion of female workers but relatively lower average salaries. Conversely, in occupations such as <em>executive management</em>, which have a low proportion of female workers, the wages are considerably higher. This highlights the wage inequality that exists in certain sectors despite high female representation.</li>
</ul>
<p><strong>4.Do certain industries show a trend of higher wages for occupations with fewer female workers?</strong></p>
<p>( It may seek to explore whether male-dominated industries offer higher wages compared to female-dominated ones, pointing to the potential for occupational segregation to influence income inequality.)</p>
<ul>
<li>Yes, industries such as <em>engineering</em> and <em>technology</em>, which are male-dominated, display higher wages. The data indicates that male-dominated fields tend to offer better pay compared to female-dominated occupations, suggesting occupational segregation and its impact on wages.</li>
</ul>
<p><strong>5.Is there evidence of gender wage gaps in high-paying versus low-paying occupations?</strong></p>
<p>( The graph could aim to determine whether high-paying jobs are more prone to gender wage gaps compared to lower-paying ones, and how these gaps manifest across different sectors.)</p>
<ul>
<li>Yes, high-paying occupations such as <em>executive management</em> and <em>engineering</em> have a noticeable gender wage gap, with male workers dominating these fields and receiving higher salaries. On the other hand, lower-paying fields like <em>nursing</em> or <em>teaching</em>—which have a higher proportion of female workers—show relatively smaller wage gaps but also lower overall salaries.</li>
</ul>
</section>
<section id="additional-questions" class="level3">
<h3 class="anchored" data-anchor-id="additional-questions">Additional Questions</h3>
<p><strong>1.What kind of chart is used in the figure?</strong></p>
<p>The chart is a <strong>bubble plot</strong> (or scatter plot with size variation), where each bubble represents an occupation. The size of the bubbles typically corresponds to the number of workers in that occupation, while the x-axis represents salaries, and the y-axis shows the proportion of female workers in those occupations.</p>
<p><strong>2.What geometries have been used, and to which variables have these geometries been mapped?</strong></p>
<p>The key geometries used in this bubble plot are:</p>
<ul>
<li><p><strong>Points (bubbles)</strong>: Represent occupations.</p></li>
<li><p><strong>X-axis</strong>: Mapped to <strong>salaries</strong> (salary levels).</p></li>
<li><p><strong>Y-axis</strong>: Mapped to the <strong>proportion of female workers</strong> in each occupation.</p></li>
<li><p><strong>Size of bubbles</strong>: Mapped to the <strong>number of workers</strong> in each occupation.</p></li>
</ul>
<p><strong>3.Based on this graph, do you think gender plays a role in salaries? What is the trend you see?</strong></p>
<p>Yes, gender seems to play a significant role in salaries. The trend observed is that <strong>occupations with higher proportions of female workers tend to have lower salaries</strong>. For example, professions dominated by women (e.g., nursing, teaching) exhibit relatively smaller salaries compared to male-dominated fields like engineering or executive management, which have higher wages. This suggests a gender wage gap where male-dominated occupations offer higher pay compared to female-dominated ones.</p>
<p><strong>4.If SALARY, NO_OF_WORKERS, GENDER, OCCUPATION were available in the original dataset, what pre-processing would have been necessary to obtain this plot?</strong></p>
<p>Several preprocessing steps would likely be necessary:</p>
<ul>
<li><p><strong>Conversion of Salary Data</strong>: Depending on the scale of salary values, some conversion to a common currency/scale might be required for better comparison.</p></li>
<li><p><strong>Gender Proportion Calculation</strong>: The dataset would need to compute the <strong>proportion of female workers</strong> (e.g., percentage of female workers relative to the total number of workers in each occupation).</p></li>
<li><p><strong>Handling Missing Data</strong>: Any missing data in variables such as salary or number of workers would need to be addressed.</p></li>
<li><p><strong>Size Mapping</strong>: The number of workers would need to be scaled to appropriately map the bubble sizes in the plot, ensuring large and small values are distinguishable.</p></li>
<li><p><strong>Aggregating Data</strong>: If the data included detailed information about individual workers, it might have been grouped by occupation. This would involve calculating summary statistics such as the average salary, the percentage of female workers, and the total number of workers for each job type.</p></li>
</ul>
</section>
<section id="inference-and-story-from-the-graph-and-data" class="level3">
<h3 class="anchored" data-anchor-id="inference-and-story-from-the-graph-and-data">Inference and Story from the Graph and Data</h3>
<p>The graph titled “Salaries and Gender Proportion in the Workforce” provides an insightful view into the relationship between gender proportions in various occupations and the corresponding salary disparities. By analyzing this data, we gain a deeper understanding of how gender representation in the workforce influences salary distribution across different job sectors.</p>
</section>
<section id="key-observations" class="level3">
<h3 class="anchored" data-anchor-id="key-observations">Key Observations</h3>
<p>From analyzing the graph and the associated job_gender dataset, I observed the following:</p>
<ul>
<li><p><strong>Gender Imbalance in High-Paying Jobs:</strong> Occupations with a higher proportion of male workers, such as engineering and technology, tend to have higher median salaries. This indicates that male-dominated industries are often associated with higher compensation, highlighting a disparity in salary distribution across different sectors.</p></li>
<li><p><strong>Lower Salaries in Female-Dominated Occupations:</strong> On the other hand, jobs with a higher percentage of female workers, such as nursing, teaching, and clerical roles, show significantly lower median salaries. This suggests that occupations traditionally dominated by women often receive lower pay compared to male-dominated fields.</p></li>
<li><p><strong>Wage Disparities in Gender-Balanced Roles:</strong> Even in occupations where gender representation is relatively balanced, such as healthcare and education, there is still a noticeable gap in median salaries. This reinforces the idea that salary disparity isn’t solely dependent on the proportion of gender but is also influenced by societal and occupational factors.</p></li>
</ul>
</section>
<section id="insights-on-workforce-gender-dynamics" class="level3">
<h3 class="anchored" data-anchor-id="insights-on-workforce-gender-dynamics">Insights on Workforce Gender Dynamics</h3>
<p>If I were to draw conclusions based on this data, it’s clear that gender continues to play a critical role in shaping salary structures across industries. Investments in gender equity, particularly in improving the salaries of female-dominated sectors, could help bridge the pay gap. <strong>Healthcare</strong> and <strong>education</strong>, where salaries remain lower despite more balanced gender representation, should be prioritized in any gender equality effort.</p>
</section>
<section id="sector-specific-insights" class="level3">
<h3 class="anchored" data-anchor-id="sector-specific-insights">Sector-Specific Insights</h3>
<p>Each sector provides different insights into the relationship between gender and salaries:</p>
<ul>
<li><p><strong>Male-Dominated Occupations:</strong> Roles in engineering, manufacturing, and technology, which are predominantly occupied by men, not only exhibit higher salaries but also reflect the societal value placed on these professions. Addressing this imbalance by encouraging more women to enter these sectors could help reduce the gender pay gap.</p></li>
<li><p><strong>Female-Dominated Occupations:</strong> Fields such as teaching, nursing, and clerical work are primarily composed of women and tend to have lower salaries. These industries need targeted strategies to increase wages and provide women with equal earning opportunities.</p></li>
<li><p><strong>Gender-Balanced Occupations:</strong> Even in sectors like healthcare, where gender balance is closer, salary gaps still exist. This suggests that achieving gender parity in representation alone may not be enough to address the underlying pay disparity.</p></li>
</ul>
</section>
<section id="the-power-of-data-visualization" class="level3">
<h3 class="anchored" data-anchor-id="the-power-of-data-visualization">The Power of Data Visualization</h3>
<p>This graph effectively visualizes how gender proportions across different occupations impact salary structures, offering key insights for policymakers, businesses, and advocacy groups. The data highlights critical sectors where pay equity efforts should be directed, ensuring equal opportunities and fair compensation regardless of gender. This visualization allows for a more targeted approach to resolving wage disparities and fostering a more inclusive workforce.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>