{
  "hash": "8094ac51db5bef8a3965e8d42bb6cf76",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 3 - Part 2\"\nauthor: \"Khushi\"\ncategories: [\"Assignments\"]\n---\n\n\n### Introduction\n\nWe are investigating the influence of Dietary Preference and Gender on Tipping Behaviour.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.1     ✔ tibble    3.2.1\n✔ lubridate 1.9.3     ✔ tidyr     1.3.1\n✔ purrr     1.0.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(mosaic)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRegistered S3 method overwritten by 'mosaic':\n  method                           from   \n  fortify.SpatialPolygonsDataFrame ggplot2\n\nThe 'mosaic' package masks several functions from core packages in order to add \nadditional features.  The original behavior of these functions should not be affected by this.\n\nAttaching package: 'mosaic'\n\nThe following object is masked from 'package:Matrix':\n\n    mean\n\nThe following objects are masked from 'package:dplyr':\n\n    count, do, tally\n\nThe following object is masked from 'package:purrr':\n\n    cross\n\nThe following object is masked from 'package:ggplot2':\n\n    stat\n\nThe following objects are masked from 'package:stats':\n\n    binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,\n    quantile, sd, t.test, var\n\nThe following objects are masked from 'package:base':\n\n    max, mean, min, prod, range, sample, sum\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggformula)\nlibrary(crosstable)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'crosstable'\n\nThe following object is masked from 'package:purrr':\n\n    compact\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(skimr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'skimr'\n\nThe following object is masked from 'package:mosaic':\n\n    n_missing\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(broom)\n```\n:::\n\n\n### Research Experiment to Investigate the Influence of Dietary Preference and Gender on Tipping Behaviour\n\n**Objective**:\\\nThe purpose of this research experiment is to investigate whether there is a significant difference in the amount of tips given by vegetarians and non-vegetarians. Additionally, the study aims to test whether one gender tends to tip more than the other. By collecting and analyzing tipping data, we aim to explore both dietary and gender-based differences in tipping behaviour.\n\n**Hypotheses**:\n\n-   *Primary Hypothesis:*\\\n    Non-vegetarians tend to give higher tips on average compared to vegetarians.\n\n-   *Additional Hypothesis:\\\n    *One gender (e.g., males) tends to give higher tips on average compared to the other gender (e.g., females).\n\n#### **Experiment Design:** **Data Collection:**\n\n-   *Sample:* The dataset consists of tipping data from 60 students at MAHE Bengaluru. There are 30 males and 30 females, with each gender group containing 15 vegetarians and 15 non-vegetarians. The participants were randomly selected through coin tosses and asked to record the amount they tipped during a meal on October 24th, 2024.\n\n-   *Data Sources:* The data was recorded in an Excel sheet by the people conducting the experiment. Each participant reported the tip amount they gave, along with their dietary preference (vegetarian or non-vegetarian) and gender.\n\n**Variables Measured**:\n\n-   *Target Variable:* The amount of tip given by each participant during the experiment period.\n\n-   *Predictor Variables:*\n\n    -   Dietary Preference (Vegetarian vs. Non-Vegetarian)\n\n    -   Gender (Male vs. Female)\n\n**Sampling**:\n\n-   *Time Period:* The experiment was conducted on October 24th, 2024, over a period of 1.5 hours.\n\n-   *Participant Selection Criteria:* 30 males and 30 females were randomly selected by tossing a coin. Within each gender group, 15 participants were vegetarians and 15 were non-vegetarians. Their dietary preferences and tipping behaviour were recorded accordingly.\n\n**Analysis Plan:**\n\n-   *Data Cleaning and Transformation:* The data was checked for accuracy in the Excel sheet, ensuring that each participant's tipping amount, dietary preference, and gender were properly recorded, with no missing or erroneous entries.\n\n-   *Exploratory Data Analysis (EDA):* Visualizations such as histograms, box plots, and scatter plots will be used to compare tipping distributions between vegetarians and non-vegetarians, as well as between males and females. This will help identify patterns or discrepancies in tipping behaviour.\n\n#### Statistical Tests:\n\n-   *Two-Sample t-Test (Dietary Preference):* A two-independent sample test for means will be conducted to compare the average tip amount given by vegetarians and non-vegetarians. This will help determine if there is a statistically significant difference in tipping behaviour between the two dietary groups.\n\n-   *Two-Sample t-Test (Gender):* A separate two-sample t-test will be conducted to compare the average tip amount given by males and females. This will help determine if there is a statistically significant difference in tipping behaviour between the two genders.\n\n-   *Permutation Test (Dietary Preference & Gender):* A permutation test will be conducted to assess the likelihood of the observed differences in tipping amounts (for both dietary preference and gender) occurring by chance, providing a non-parametric alternative to the two-sample t-tests.\n\n-   *Descriptive Statistics:* Measures like mean, median, and standard deviation will be calculated for both groups (vegetarians vs. non-vegetarians and males vs. females) to summarize tipping behaviour.\n\n-   *Wilcoxon Rank-Sum Test:* If the normality assumption is not met, a Wilcoxon rank-sum test (a non-parametric test) will be conducted to compare the tipping behaviour between vegetarians and non-vegetarians, as well as between males and females.\n\n**Limitations**:\n\n-   *Sample Size:* With 30 participants per group (15 vegetarians and 15 non-vegetarians for each gender), the results may not be generalizable to a larger population. A more extensive sample would provide greater reliability.\n\n-   *Contextual Factors:* The study did not account for external factors that might influence tipping behaviour, such as the quality of service, the total bill amount, or personal tipping habits, which could have an effect on the tip amount.\n\n### Outcome:\n\nThe analysis will reveal whether significant differences in tipping behaviour exist between vegetarians and non-vegetarians and between males and females at MAHE Bengaluru. If the hypotheses hold, it would suggest that non-vegetarians, on average, tend to give higher tips than vegetarians, and one gender may tend to tip more than the other. These findings will provide insights into whether dietary preferences and gender influence tipping behaviour within this student population.\n\n### Dataset - Tipping\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntip <- read_csv(\"../../data/tip.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 60 Columns: 4\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (3): Name, Gender, Preference\ndbl (1): Tip\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\ntip\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 60 × 4\n   Name     Gender Preference   Tip\n   <chr>    <chr>  <chr>      <dbl>\n 1 Aanya    Female Veg            0\n 2 Adit     Male   Veg            0\n 3 Aditi    Female Veg           20\n 4 Akash    Male   Non-veg        0\n 5 Akshita  Female Non-veg        0\n 6 Anandita Female Non-veg        0\n 7 Ananya   Female Non-veg       20\n 8 Anaya    Female Veg           35\n 9 Anhuya   Female Veg           40\n10 Ankit    Male   Non-veg        0\n# ℹ 50 more rows\n```\n\n\n:::\n:::\n\n\nThe dataset shown contains tipping data for 60 students at MAHE Bengaluru. The data includes four variables: Name, Gender, Dietary Preference (Vegetarian or Non-Vegetarian), and Tip Amount. Each row represents one participant’s recorded tip amount. The participants are evenly split between males and females, as well as between vegetarians and non-vegetarians. There are variations in tipping amounts, with some participants tipping as high as 40 units, while others tipped nothing.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntip_modified <- tip %>% \n  dplyr::mutate( Gender = as_factor(Gender))\n```\n:::\n\n\n### Glimpse - Tipping\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(tip_modified)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 60\nColumns: 4\n$ Name       <chr> \"Aanya\", \"Adit\", \"Aditi\", \"Akash\", \"Akshita\", \"Anandita\", \"…\n$ Gender     <fct> Female, Male, Female, Male, Female, Female, Female, Female,…\n$ Preference <chr> \"Veg\", \"Veg\", \"Veg\", \"Non-veg\", \"Non-veg\", \"Non-veg\", \"Non-…\n$ Tip        <dbl> 0, 0, 20, 0, 0, 0, 20, 35, 40, 0, 0, 0, 0, 0, 0, 0, 20, 0, …\n```\n\n\n:::\n:::\n\n\nThe Gender variable is stored as a factor, with participants divided evenly between males and females. The Tip amounts vary, with a range from 0 to 100 units. Some participants did not tip, while others left substantial tips, suggesting variability in tipping behaviour.\n\n### Inspect - Tipping\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninspect(tip_modified)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\ncategorical variables:  \n        name     class levels  n missing\n1       Name character     60 60       0\n2     Gender    factor      2 60       0\n3 Preference character      2 60       0\n                                   distribution\n1 Aanya (1.7%), Adit (1.7%) ...                \n2 Female (50%), Male (50%)                     \n3 Non-veg (50%), Veg (50%)                     \n\nquantitative variables:  \n  name   class min Q1 median Q3 max     mean       sd  n missing\n1  Tip numeric   0  0      0 20 100 11.16667 17.83556 60       0\n```\n\n\n:::\n:::\n\n\nThe tip amounts range from 0 to 100, with the median tip amount being 0, and the first and third quartiles (Q1 and Q3) being 0 and 20, respectively. The mean tip amount is approximately 11.1, with a standard deviation of 17.8.\n\n### Skim - Tipping\n\n\n::: {.cell}\n\n```{.r .cell-code}\nskim(tip_modified)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |             |\n|:------------------------|:------------|\n|Name                     |tip_modified |\n|Number of rows           |60           |\n|Number of columns        |4            |\n|_______________________  |             |\n|Column type frequency:   |             |\n|character                |2            |\n|factor                   |1            |\n|numeric                  |1            |\n|________________________ |             |\n|Group variables          |None         |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|Name          |         0|             1|   4|   9|     0|       60|          0|\n|Preference    |         0|             1|   3|   7|     0|        2|          0|\n\n\n**Variable type: factor**\n\n|skim_variable | n_missing| complete_rate|ordered | n_unique|top_counts       |\n|:-------------|---------:|-------------:|:-------|--------:|:----------------|\n|Gender        |         0|             1|FALSE   |        2|Fem: 30, Mal: 30 |\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|  mean|    sd| p0| p25| p50| p75| p100|hist  |\n|:-------------|---------:|-------------:|-----:|-----:|--:|---:|---:|---:|----:|:-----|\n|Tip           |         0|             1| 11.17| 17.84|  0|   0|   0|  20|  100|▇▁▁▁▁ |\n\n\n:::\n:::\n\n\nThe tips range from 0 to 100, with an average (mean) tip of approximately 11.17 rupees and a standard deviation of 17.84 rupees. Most participants did not give any tips, as indicated by the median and lower quartile values being 0. The data shows variability in tipping behaviour across individuals, with some participants giving significantly higher tips (as shown by the maximum value of 100).\n\n### **Data Dictionary**\n\n**Quantitative Data:**\n\n-   **Tip (dbl):** The total tip amount given by each participant, recorded in Indian rupees.\n\n**Qualitative Data:**\n\n-   **Name (chr):** The name of the participant.\n\n-   **Gender (fct):** The gender of the participant, categorized as either Male or Female.\n\n-   **Preference (chr):** The dietary preference of the participant, categorized as either Vegetarian (Veg) or Non-Vegetarian (Non-veg).\n\n### Histogram - Distribution of Tips by Dietary Preference\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_histogram( ~ Tip | Preference, \n              data = tip_modified, \n              binwidth = 10, \n              fill = \"skyblue\", \n              color = \"black\" \n) %>%\ngf_labs(\n    title = \"Distribution of Tips by Dietary Preference\",\n    x = \"Tip Amount (in Rupees)\",\n    y = \"Count\"\n)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nThe histogram visualizes the distribution of tips given by vegetarians and non-vegetarians. Both groups show a significant number of participants who gave no tips at all, with vegetarians showing a higher concentration of zero tips compared to non-vegetarians. Among those who did tip, non-vegetarians gave a larger number of tips in the range of ₹0 to ₹25, with fewer participants tipping above ₹50. In contrast, a few vegetarians tipped more substantial amounts, with one participant tipping ₹100, while most tips were clustered between ₹0 and ₹25. Overall, non-vegetarians tend to provide more tips within the lower ranges, while vegetarians exhibit a broader spread, with some giving higher tips. However, the majority of both groups tend to tip small amounts or none at all.\n\n### Histogram - Distribution of Tips by Gender\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_histogram( ~ Tip | Gender, \n              data = tip_modified, \n              binwidth = 10, \n              fill = \"lightgreen\", \n              color = \"black\" \n) %>%\ngf_labs(\n    title = \"Distribution of Tips by Gender\",\n    x = \"Tip Amount (in Rupees)\",\n    y = \"Count\"\n)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nThe histogram displays the distribution of tips given by gender. Both males and females show a significant number of participants who did not give any tips at all, with males having a slightly higher concentration of zero tips. Among those who did tip, most females provided tips in the ₹0 to ₹25 range, with a few tipping up to ₹50. In contrast, males also predominantly tipped in the ₹0 to ₹25 range, but there is a notable outlier where one male tipped ₹100, which is higher than any tip given by females. Overall, both genders tend to give small tips, though males show a broader range of tipping amounts, with the maximum tip coming from a male participant.\n\n### Box plot - Distribution of Tips by Dietary Preference\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_boxplot(Tip ~ Preference,\n  data = tip_modified,\n  fill = ~Preference) %>%\n  gf_labs(\n    title = \"Distribution of Tips by Dietary Preference\",\n    x = \"Dietary Preference\",\n    y = \"Tip Amount (in Rupees)\"\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nThe box plot comparing the distribution of tips between vegetarians and non-vegetarians reveals that both groups have similar ranges of tip amounts, but there is an outlier in the vegetarian group with a higher tip of 100 rupees. The median tip for both vegetarians and non-vegetarians is around the same value. However, the spread (interquartile range) of tips is slightly broader for non-vegetarians. The presence of an outlier in the vegetarian group suggests that one individual tipped significantly more than the majority of participants in both groups, while most participants tipped relatively low amounts. Overall, the box plot indicates that tipping behaviour is fairly similar between the two dietary preference groups, with no major differences in the central tendency.\n\n### Box Plot - Distribution of Tips by Gender\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_boxplot(Tip ~ Gender,\n  data = tip_modified,\n  fill = ~Gender) %>%\n  gf_labs(\n    title = \"Distribution of Tips by Gender\",\n    x = \"Gender\",\n    y = \"Tip Amount (in Rupees)\"\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nThe box plot comparing the distribution of tips between males and females shows that both genders have similar tipping patterns in terms of median and spread. The median tip amount is nearly the same for both groups, with the interquartile range (IQR) for females slightly broader than for males. However, there is an outlier in the male group, where one individual tipped a significantly higher amount (100 rupees) compared to the rest. Despite this outlier, the central tendency and overall distribution appear quite similar between males and females, suggesting no major gender-based differences in tipping behaviour.\n\n### Scatter Plot - Individual Tipping Behaviour by Gender and Dietary Preference\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_point(Tip ~ Gender | Preference, \n         data = tip_modified,\n         color = ~ Gender,\n         shape = ~ Preference) %>%\n  gf_labs(\n    title = \"Individual Tipping Behaviour by Gender and Dietary Preference\",\n    x = \"Gender and Dietary Preference\",\n    y = \"Tip Amount (in Rupees)\"\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nThe scatter plot visually represents individual tipping behaviour, comparing tips based on both gender and dietary preference. In the plot, female and male participants are shown with different colours, while vegetarian and non-vegetarian participants are distinguished by different shapes. The data reveals that the majority of participants across all categories (female/male, veg/non-veg) tend to give lower tips (below 50 rupees), but there are a few outliers, especially in the vegetarian category, where some participants gave tips as high as 100 rupees. Non-vegetarians, on the other hand, generally tip in smaller amounts.\n\n### Density Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntip_modified %>%\n  gf_density(~ Tip, fill = ~ Preference, alpha = 0.5) %>%\n  gf_fitdistr(~ Tip, dist = \"dnorm\") %>%\n  gf_labs(\n    title = \"Density Plot of Tip Amount by Dietary Preference\",\n    subtitle = \"Compared with Normal Distribution\",\n    x = \"Tip Amount (in Rupees)\",\n    y = \"Density\"\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n\n```{.r .cell-code}\ntip_modified %>%\n  gf_density(~ Tip, fill = ~ Gender, alpha = 0.5) %>%\n  gf_fitdistr(~ Tip, dist = \"dnorm\") %>%\n  gf_labs(\n    title = \"Density Plot of Tip Amount by Gender\",\n    subtitle = \"Compared with Normal Distribution\",\n    x = \"Tip Amount (in Rupees)\",\n    y = \"Density\"\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-2.png){width=672}\n:::\n:::\n\n\nThe density plots provide a visual comparison of the tipping behaviour across dietary preferences (vegetarians vs. non-vegetarians) and gender (males vs. females). In both cases, the tipping behaviour is skewed towards lower tip amounts, with the highest density of tips being in the range of 0 to 25 rupees. The comparison against the normal distribution suggests that the tip data does not follow a normal distribution, especially for the lower tip amounts.\n\nFor dietary preferences, non-vegetarians tend to tip slightly higher than vegetarians, as indicated by the density curve extending further towards higher tip amounts. However, the difference is not substantial, and both groups show a similar overall distribution of low tips.\n\nIn terms of gender, the male participants appear to give slightly higher tips compared to female participants, as seen by the male density curve being more spread towards the higher tip amounts. Nonetheless, both genders also demonstrate a strong tendency towards giving lower tips, with a majority of tips clustered in the lower ranges. Overall, while there are slight differences, tipping behaviour across both dietary preference and gender is heavily skewed towards lower amounts.\n\n### Crosstable\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrosstable(\n  tip_modified, \n  c(Gender, Preference), \n  showNA = \"ifany\"\n) %>%\n  crosstable::as_flextable()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-c66a3e48{table-layout:auto;}.cl-c65b86be{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-c65b86d2{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-c65f0a64{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-c65f0a6e{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-c65f320a{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c65f3214{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c65f321e{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c65f321f{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c65f3228{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c65f3229{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-c66a3e48'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-c65f320a\"><p class=\"cl-c65f0a64\"><span class=\"cl-c65b86be\">label</span></p></th><th class=\"cl-c65f320a\"><p class=\"cl-c65f0a64\"><span class=\"cl-c65b86be\">variable</span></p></th><th class=\"cl-c65f320a\"><p class=\"cl-c65f0a64\"><span class=\"cl-c65b86be\">value</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td  rowspan=\"2\"class=\"cl-c65f3214\"><p class=\"cl-c65f0a6e\"><span class=\"cl-c65b86d2\">Gender</span></p></td><td class=\"cl-c65f321e\"><p class=\"cl-c65f0a6e\"><span class=\"cl-c65b86d2\">Female</span></p></td><td class=\"cl-c65f321e\"><p class=\"cl-c65f0a6e\"><span class=\"cl-c65b86d2\">30 (50.00%)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-c65f3214\"><p class=\"cl-c65f0a6e\"><span class=\"cl-c65b86d2\">Male</span></p></td><td class=\"cl-c65f3214\"><p class=\"cl-c65f0a6e\"><span class=\"cl-c65b86d2\">30 (50.00%)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td  rowspan=\"2\"class=\"cl-c65f321f\"><p class=\"cl-c65f0a6e\"><span class=\"cl-c65b86d2\">Preference</span></p></td><td class=\"cl-c65f3228\"><p class=\"cl-c65f0a6e\"><span class=\"cl-c65b86d2\">Non-veg</span></p></td><td class=\"cl-c65f3228\"><p class=\"cl-c65f0a6e\"><span class=\"cl-c65b86d2\">30 (50.00%)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-c65f3229\"><p class=\"cl-c65f0a6e\"><span class=\"cl-c65b86d2\">Veg</span></p></td><td class=\"cl-c65f3229\"><p class=\"cl-c65f0a6e\"><span class=\"cl-c65b86d2\">30 (50.00%)</span></p></td></tr></tbody></table></div>\n```\n\n:::\n\n```{.r .cell-code}\ntip_modified %>%\n  group_by(Gender, Preference) %>%\n  summarize(\n    Mean_Tip = mean(Tip, na.rm = TRUE),\n    Median_Tip = median(Tip, na.rm = TRUE),\n    Count = n()\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`summarise()` has grouped output by 'Gender'. You can override using the\n`.groups` argument.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n# Groups:   Gender [2]\n  Gender Preference Mean_Tip Median_Tip Count\n  <fct>  <chr>         <dbl>      <dbl> <int>\n1 Female Non-veg       11.3           0    15\n2 Female Veg           13             0    15\n3 Male   Non-veg        8.67          0    15\n4 Male   Veg           11.7           0    15\n```\n\n\n:::\n:::\n\n\nThe cross table shows that the tipping dataset contains an equal number of males and females, with 30 participants in each group. Similarly, there are equal numbers of participants with dietary preferences, 30 for vegetarians and 30 for non-vegetarians. When breaking down by gender and dietary preference, the average tip given by females who are non-vegetarians is ₹11.33, while females who are vegetarians tip an average of ₹13. For males, non-vegetarians give an average of ₹8.67, while vegetarians tip an average of ₹11.67. The median tip for all groups remains ₹0, indicating that many participants may not have tipped, skewing the distribution. These results suggest some differences in tipping behaviour based on dietary preferences and gender, though the prevalence of non-tipping behaviour is noticeable across all groups.\n\n### T-test for Vegetarians vs. Non-Vegetarians\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_test_veg_nonveg <- t.test(\n  Tip ~ Preference,\n  data = tip_modified,\n  var.equal = FALSE \n) %>% \nbroom::tidy()\n\nt_test_veg_nonveg\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 10\n  estimate estimate1 estimate2 statistic p.value parameter conf.low conf.high\n     <dbl>     <dbl>     <dbl>     <dbl>   <dbl>     <dbl>    <dbl>     <dbl>\n1    -2.33        10      12.3    -0.503   0.617      46.9    -11.7      6.99\n# ℹ 2 more variables: method <chr>, alternative <chr>\n```\n\n\n:::\n:::\n\n\nThe t-test conducted to compare the average tip amounts between vegetarians and non-vegetarians shows a p-value of 0.617. This high p-value indicates that there is no statistically significant difference between the two groups. The estimated mean tip for vegetarians is ₹12.33, while for non-vegetarians, it is ₹10, resulting in a mean difference of approximately ₹2.33. The 95% confidence interval for this difference is from -11.66 to 6.99, which includes zero, further suggesting that there is no significant difference in tipping behaviour based on dietary preference. Therefore, the data does not support the hypothesis that non-vegetarians tip more than vegetarians.\n\n### T-test for Males vs. Females\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_test_gender <- t.test(\n  Tip ~ Gender,\n  data = tip_modified,\n  var.equal = FALSE \n) %>% \nbroom::tidy()\n\nt_test_gender\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 10\n  estimate estimate1 estimate2 statistic p.value parameter conf.low conf.high\n     <dbl>     <dbl>     <dbl>     <dbl>   <dbl>     <dbl>    <dbl>     <dbl>\n1        2      12.2      10.2     0.431   0.668      55.8    -7.29      11.3\n# ℹ 2 more variables: method <chr>, alternative <chr>\n```\n\n\n:::\n:::\n\n\nThe t-test comparing the average tip amounts between males and females reveals no significant difference in tipping behaviour. The mean tip for males was ₹10.17, and for females, it was ₹12.17. The test produced a t-statistic of 0.431 and a p-value of 0.668, which is much higher than the standard significance level of 0.05. Additionally, the 95% confidence interval ranges from -7.29 to 11.29, suggesting that the true difference in means could be anywhere within this range, including zero.\n\n### Wilcoxon Rank-Sum Test for Vegetarians vs. Non-Vegetarians\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox_test_veg_nonveg <- wilcox.test(\n  Tip ~ Preference,\n  data = tip_modified,\n  alternative = \"two.sided\",\n  conf.int = TRUE\n) %>%\n  broom::tidy()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in wilcox.test.default(x = DATA[[1L]], y = DATA[[2L]], ...): cannot\ncompute exact p-value with ties\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in wilcox.test.default(x = DATA[[1L]], y = DATA[[2L]], ...): cannot\ncompute exact confidence intervals with ties\n```\n\n\n:::\n\n```{.r .cell-code}\nwilcox_test_veg_nonveg\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 7\n   estimate statistic p.value   conf.low   conf.high method          alternative\n      <dbl>     <dbl>   <dbl>      <dbl>       <dbl> <chr>           <chr>      \n1 0.0000372       463   0.833 -0.0000335 0.000000989 Wilcoxon rank … two.sided  \n```\n\n\n:::\n:::\n\n\nThe Wilcoxon Rank-Sum Test conducted to compare the tipping behaviour between vegetarians and non-vegetarians resulted in a p-value of 0.83. This high p-value suggests that there is no statistically significant difference in the tipping amounts between the two groups. The confidence interval also crosses zero, reinforcing the conclusion that the median tip amounts for vegetarians and non-vegetarians are not significantly different. This non-parametric test confirms that dietary preference does not appear to influence tipping behaviour within this dataset.\n\n### Wilcoxon Rank-Sum Test for Males vs. Females\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox_test_gender <- wilcox.test(\n  Tip ~ Gender,\n  data = tip_modified,\n  alternative = \"two.sided\",\n  conf.int = TRUE\n) %>%\n  broom::tidy()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in wilcox.test.default(x = DATA[[1L]], y = DATA[[2L]], ...): cannot\ncompute exact p-value with ties\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in wilcox.test.default(x = DATA[[1L]], y = DATA[[2L]], ...): cannot\ncompute exact confidence intervals with ties\n```\n\n\n:::\n\n```{.r .cell-code}\nwilcox_test_gender\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 7\n   estimate statistic p.value   conf.low  conf.high method           alternative\n      <dbl>     <dbl>   <dbl>      <dbl>      <dbl> <chr>            <chr>      \n1 0.0000445       498   0.422 -0.0000134 0.00000497 Wilcoxon rank s… two.sided  \n```\n\n\n:::\n:::\n\n\nThe results of the Wilcoxon Rank-Sum Test comparing tipping behaviour between males and females show no significant difference in tipping amounts between the two genders. The p-value is 0.42, which is much higher than the conventional threshold of 0.05, indicating that any observed differences in tipping amounts between males and females are not statistically significant. Both the confidence interval values are very close to zero, further supporting the conclusion that there is no significant difference between male and female tipping behaviour. Thus, tipping behaviour seems similar across both genders in this dataset.\n\n### Permutation Test for Vegetarians vs Non-Vegetarians\n\n\n::: {.cell}\n\n```{.r .cell-code}\nperm_test_veg_nonveg <- do(1000) * diffmean(Tip ~ shuffle(Preference), data = tip_modified)\nperm_test_veg_nonveg\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        diffmean\n1     -3.6666667\n2      4.6666667\n3      3.0000000\n4      1.6666667\n5      1.3333333\n6      3.6666667\n7      1.6666667\n8     -3.0000000\n9      2.0000000\n10     0.6666667\n11     4.0000000\n12    -4.6666667\n13    -3.3333333\n14     3.6666667\n15     0.6666667\n16     5.3333333\n17   -10.0000000\n18    -1.3333333\n19    -0.6666667\n20    -2.0000000\n21    -0.3333333\n22     2.0000000\n23     3.6666667\n24    -3.0000000\n25     1.6666667\n26    -9.0000000\n27     0.6666667\n28     0.3333333\n29    -2.6666667\n30     5.3333333\n31    -5.6666667\n32     6.0000000\n33    -7.6666667\n34     1.3333333\n35     0.3333333\n36    -5.0000000\n37    -1.3333333\n38    -3.0000000\n39     0.3333333\n40     6.3333333\n41    -5.0000000\n42     2.6666667\n43     7.3333333\n44    -3.0000000\n45     6.0000000\n46     3.6666667\n47     1.6666667\n48     3.0000000\n49    -2.3333333\n50    -1.0000000\n51    -8.3333333\n52    -0.3333333\n53     7.6666667\n54     1.6666667\n55    -4.3333333\n56    -7.6666667\n57     5.6666667\n58     1.0000000\n59     2.0000000\n60    -4.3333333\n61    -3.3333333\n62    -5.6666667\n63    -1.6666667\n64    -1.3333333\n65    -2.0000000\n66     2.6666667\n67     7.0000000\n68    -0.6666667\n69    -3.6666667\n70    -3.0000000\n71    -6.3333333\n72    -5.3333333\n73    -1.6666667\n74     4.0000000\n75    -1.6666667\n76     4.0000000\n77    -1.3333333\n78     4.0000000\n79    -4.3333333\n80     2.0000000\n81    -4.6666667\n82    -2.6666667\n83     8.6666667\n84    10.0000000\n85     3.6666667\n86     5.6666667\n87     1.0000000\n88     9.6666667\n89     7.3333333\n90    -5.6666667\n91     3.3333333\n92     2.0000000\n93     4.0000000\n94     1.3333333\n95    -7.3333333\n96   -11.0000000\n97     2.6666667\n98     0.0000000\n99     0.3333333\n100   -9.6666667\n101   -2.3333333\n102   -5.0000000\n103   -1.3333333\n104   -6.0000000\n105   -2.3333333\n106    5.6666667\n107    8.6666667\n108   -1.6666667\n109    3.0000000\n110   -1.6666667\n111    0.6666667\n112   -2.0000000\n113    3.6666667\n114   -8.6666667\n115    0.6666667\n116   -1.0000000\n117    3.0000000\n118    8.3333333\n119    3.3333333\n120    3.6666667\n121   -4.0000000\n122   -7.0000000\n123    3.0000000\n124    3.0000000\n125    1.6666667\n126    2.0000000\n127   -4.0000000\n128   -2.6666667\n129    4.6666667\n130    3.6666667\n131    4.3333333\n132   -6.6666667\n133   -3.0000000\n134   -1.3333333\n135   -6.6666667\n136   -6.6666667\n137   -5.3333333\n138    5.6666667\n139   -1.0000000\n140    2.3333333\n141  -12.3333333\n142   -8.0000000\n143    2.3333333\n144    0.3333333\n145    3.0000000\n146    2.6666667\n147    6.3333333\n148   -3.3333333\n149   -0.3333333\n150   -2.0000000\n151    7.6666667\n152    3.0000000\n153    0.6666667\n154    2.0000000\n155   -1.3333333\n156    3.0000000\n157    2.3333333\n158   -5.3333333\n159    5.0000000\n160    1.6666667\n161    4.3333333\n162   -4.0000000\n163    0.3333333\n164   -5.3333333\n165    0.3333333\n166    0.3333333\n167   -1.3333333\n168    5.6666667\n169    0.3333333\n170   -5.0000000\n171   -4.3333333\n172    0.6666667\n173    5.6666667\n174   -1.6666667\n175    1.0000000\n176    7.3333333\n177   -6.6666667\n178    1.3333333\n179    5.3333333\n180    1.6666667\n181    6.3333333\n182    5.3333333\n183    2.0000000\n184   -5.0000000\n185   -8.0000000\n186    3.0000000\n187   -6.6666667\n188    0.6666667\n189   -1.6666667\n190   -6.6666667\n191   -7.3333333\n192    5.6666667\n193   -5.3333333\n194   -4.6666667\n195   -4.0000000\n196    5.3333333\n197   -4.0000000\n198   -3.6666667\n199    3.0000000\n200    0.3333333\n201   -6.0000000\n202    2.0000000\n203    8.6666667\n204    0.0000000\n205    0.3333333\n206   -1.6666667\n207    1.6666667\n208   -3.0000000\n209   -3.6666667\n210   -3.6666667\n211    5.3333333\n212    4.0000000\n213   -0.3333333\n214    2.3333333\n215   -4.3333333\n216   -0.3333333\n217    3.0000000\n218   -7.6666667\n219    4.0000000\n220   -2.3333333\n221   -4.3333333\n222   -4.3333333\n223   -9.6666667\n224   -3.3333333\n225    0.3333333\n226    8.0000000\n227    2.3333333\n228   -2.0000000\n229    3.3333333\n230    2.6666667\n231   -1.6666667\n232   -3.6666667\n233    7.0000000\n234   -2.3333333\n235    1.3333333\n236   -2.3333333\n237    3.6666667\n238    5.3333333\n239   -2.6666667\n240    0.3333333\n241    0.0000000\n242    5.0000000\n243    4.6666667\n244    3.3333333\n245    1.6666667\n246    0.3333333\n247    3.3333333\n248   -1.3333333\n249  -10.3333333\n250    4.3333333\n251    0.0000000\n252   -6.0000000\n253    5.6666667\n254   -5.6666667\n255   -0.3333333\n256    6.3333333\n257   -0.6666667\n258    0.6666667\n259   -0.3333333\n260    4.0000000\n261    5.6666667\n262    3.3333333\n263   -0.6666667\n264    4.6666667\n265   -2.6666667\n266   -2.0000000\n267   -3.6666667\n268   -3.0000000\n269   -2.0000000\n270    1.0000000\n271    0.3333333\n272    2.0000000\n273   -2.0000000\n274   -0.6666667\n275    5.6666667\n276    1.3333333\n277    2.0000000\n278    6.6666667\n279   -5.0000000\n280   -0.6666667\n281   -4.6666667\n282   -4.6666667\n283   -0.6666667\n284    5.6666667\n285   -5.0000000\n286   -6.0000000\n287    0.6666667\n288    5.6666667\n289    5.3333333\n290    2.3333333\n291   -2.6666667\n292    9.3333333\n293   -1.3333333\n294    1.0000000\n295    2.0000000\n296   -3.0000000\n297   -1.6666667\n298    3.6666667\n299   -9.0000000\n300   10.3333333\n301   -5.3333333\n302   -0.6666667\n303   -0.3333333\n304   -5.0000000\n305   -8.6666667\n306    6.0000000\n307    6.0000000\n308    6.6666667\n309    3.6666667\n310    0.0000000\n311    2.6666667\n312    6.6666667\n313    0.3333333\n314    7.3333333\n315    2.3333333\n316    2.6666667\n317   -3.0000000\n318    4.0000000\n319   -2.6666667\n320   -5.3333333\n321   -3.0000000\n322    4.0000000\n323    2.0000000\n324    3.6666667\n325   -3.3333333\n326    3.3333333\n327   10.0000000\n328   -5.3333333\n329    1.0000000\n330    2.0000000\n331    6.6666667\n332    6.0000000\n333   -7.0000000\n334    5.3333333\n335    1.0000000\n336  -10.6666667\n337   -1.0000000\n338    7.3333333\n339    0.3333333\n340   -1.3333333\n341    2.0000000\n342    9.3333333\n343   -6.6666667\n344   -1.6666667\n345    3.3333333\n346    3.0000000\n347    1.0000000\n348    5.3333333\n349    8.6666667\n350   -1.3333333\n351   -5.3333333\n352    1.3333333\n353    7.3333333\n354   -1.0000000\n355   -4.0000000\n356    0.3333333\n357   -3.3333333\n358    0.6666667\n359   -3.6666667\n360   -1.0000000\n361    1.3333333\n362    0.0000000\n363    2.0000000\n364   -3.6666667\n365    0.0000000\n366   -2.0000000\n367    5.0000000\n368   -5.0000000\n369   -5.3333333\n370  -10.0000000\n371    3.0000000\n372    1.3333333\n373   -9.3333333\n374   -2.3333333\n375   -7.6666667\n376    4.6666667\n377    2.0000000\n378   10.0000000\n379    0.3333333\n380    4.3333333\n381   -1.3333333\n382    4.3333333\n383    1.0000000\n384   -6.3333333\n385   -4.0000000\n386    8.3333333\n387    5.6666667\n388    8.6666667\n389    8.0000000\n390    5.6666667\n391    2.0000000\n392   -4.0000000\n393    1.6666667\n394    2.3333333\n395    5.0000000\n396    5.3333333\n397   -6.6666667\n398    3.0000000\n399    4.3333333\n400    0.6666667\n401  -13.3333333\n402    5.6666667\n403   -1.6666667\n404   -2.3333333\n405    7.3333333\n406    2.0000000\n407    6.3333333\n408   -0.6666667\n409    3.3333333\n410   -0.6666667\n411   -4.3333333\n412    0.3333333\n413   -6.6666667\n414   -3.6666667\n415   -5.0000000\n416   -9.6666667\n417    3.0000000\n418    0.6666667\n419   -1.3333333\n420   -5.6666667\n421    1.6666667\n422   -0.3333333\n423  -11.3333333\n424   -1.0000000\n425    1.0000000\n426    3.0000000\n427    0.6666667\n428    4.6666667\n429    1.0000000\n430   -2.0000000\n431  -11.0000000\n432    1.3333333\n433    2.0000000\n434    1.0000000\n435   -4.0000000\n436   -6.0000000\n437    0.6666667\n438   -2.3333333\n439   -7.3333333\n440   -1.6666667\n441    3.3333333\n442   -3.6666667\n443   -5.6666667\n444    7.3333333\n445    2.6666667\n446    6.3333333\n447    2.3333333\n448   -4.6666667\n449   -2.0000000\n450   -0.3333333\n451    0.3333333\n452    0.0000000\n453   -5.0000000\n454   -1.6666667\n455   -5.0000000\n456   -1.0000000\n457   -0.6666667\n458   -2.0000000\n459   -4.6666667\n460   -2.6666667\n461   -2.0000000\n462   -8.0000000\n463    1.6666667\n464   -1.6666667\n465    1.6666667\n466   -8.0000000\n467    0.6666667\n468   -8.0000000\n469    1.6666667\n470    1.6666667\n471   -4.3333333\n472   -5.6666667\n473   -3.3333333\n474   -7.0000000\n475   -0.6666667\n476    4.3333333\n477    3.6666667\n478   -4.0000000\n479    6.6666667\n480    3.0000000\n481    5.3333333\n482   -4.0000000\n483   -0.6666667\n484    8.0000000\n485    1.0000000\n486   -5.3333333\n487   -1.6666667\n488   -2.3333333\n489   -1.6666667\n490   -3.0000000\n491   -2.0000000\n492   -7.6666667\n493   -5.3333333\n494    3.3333333\n495    2.0000000\n496    6.0000000\n497   -1.3333333\n498   -0.6666667\n499   -8.0000000\n500    7.0000000\n501   -0.6666667\n502    2.3333333\n503    8.0000000\n504    2.0000000\n505   10.0000000\n506   -3.0000000\n507    1.0000000\n508    6.6666667\n509    0.3333333\n510   -6.0000000\n511   -3.0000000\n512   -1.0000000\n513    5.3333333\n514   -3.0000000\n515    2.0000000\n516   -2.6666667\n517    5.0000000\n518   11.3333333\n519    5.0000000\n520    1.0000000\n521   -3.0000000\n522    4.6666667\n523    0.0000000\n524   -3.0000000\n525    0.0000000\n526    1.3333333\n527   -4.0000000\n528    0.3333333\n529   -1.3333333\n530   -4.6666667\n531   -1.0000000\n532    5.3333333\n533    8.0000000\n534    7.0000000\n535   -3.6666667\n536   -6.0000000\n537   -1.6666667\n538    8.0000000\n539    5.3333333\n540   -4.0000000\n541    0.0000000\n542   -1.3333333\n543   -5.3333333\n544   -1.6666667\n545    0.3333333\n546   -4.0000000\n547   -4.6666667\n548    4.3333333\n549   -0.3333333\n550    0.6666667\n551   -2.6666667\n552    2.0000000\n553    4.0000000\n554   -1.0000000\n555    6.3333333\n556   -1.0000000\n557   -0.6666667\n558   -4.0000000\n559   -6.6666667\n560   -4.0000000\n561    5.3333333\n562   -3.3333333\n563    3.6666667\n564    3.3333333\n565    0.6666667\n566   -6.0000000\n567   -4.0000000\n568   -4.0000000\n569    1.0000000\n570   -4.6666667\n571   -2.3333333\n572    1.6666667\n573   -1.6666667\n574    1.6666667\n575   -6.6666667\n576    0.3333333\n577    5.3333333\n578   -5.3333333\n579   -1.6666667\n580    6.6666667\n581    5.3333333\n582   -8.0000000\n583    1.6666667\n584   -5.3333333\n585   -4.6666667\n586   -2.0000000\n587    7.0000000\n588    4.0000000\n589   -1.3333333\n590   -5.0000000\n591   -1.6666667\n592    0.3333333\n593   -4.6666667\n594   -2.6666667\n595   -1.3333333\n596   -6.3333333\n597   -8.0000000\n598   -5.0000000\n599   -3.0000000\n600   -5.3333333\n601    8.6666667\n602   -3.6666667\n603    6.6666667\n604    1.3333333\n605    4.3333333\n606   -1.3333333\n607   -0.3333333\n608   -0.6666667\n609    3.6666667\n610    9.3333333\n611    1.6666667\n612   -2.6666667\n613    9.3333333\n614    3.6666667\n615    0.6666667\n616   -1.0000000\n617   -7.0000000\n618    1.3333333\n619   -5.6666667\n620   -6.0000000\n621    7.6666667\n622   -1.3333333\n623   -5.3333333\n624    5.3333333\n625    2.6666667\n626    1.3333333\n627    1.6666667\n628    2.6666667\n629   -6.6666667\n630   -0.6666667\n631   -0.6666667\n632   -6.6666667\n633    6.3333333\n634   -0.3333333\n635    0.0000000\n636    2.0000000\n637    2.0000000\n638   -7.6666667\n639    7.6666667\n640    4.0000000\n641    6.6666667\n642    6.3333333\n643   -4.0000000\n644    4.0000000\n645    2.6666667\n646   -2.0000000\n647   -0.3333333\n648    0.0000000\n649   -1.6666667\n650   -2.6666667\n651    0.6666667\n652    4.6666667\n653    5.6666667\n654   -5.3333333\n655   -2.6666667\n656   -1.0000000\n657    1.6666667\n658   -1.6666667\n659    3.0000000\n660    0.3333333\n661   -2.3333333\n662    6.0000000\n663    2.3333333\n664    5.3333333\n665   -8.3333333\n666    0.0000000\n667   -6.3333333\n668   -7.6666667\n669   -6.3333333\n670    2.6666667\n671   -5.6666667\n672   -4.3333333\n673   -3.3333333\n674   -7.0000000\n675   -1.0000000\n676   -8.0000000\n677    1.3333333\n678    2.0000000\n679    0.0000000\n680    1.6666667\n681    1.3333333\n682   -4.6666667\n683    5.3333333\n684   -5.3333333\n685   -5.0000000\n686    0.0000000\n687   -8.6666667\n688    1.0000000\n689    3.0000000\n690    6.6666667\n691    6.6666667\n692    3.6666667\n693    4.6666667\n694   -2.6666667\n695   -0.3333333\n696    1.0000000\n697    2.3333333\n698    5.3333333\n699    0.0000000\n700   -0.3333333\n701    8.6666667\n702    1.6666667\n703    9.3333333\n704    1.6666667\n705   -5.3333333\n706   -7.6666667\n707   -2.3333333\n708    1.0000000\n709    2.6666667\n710    6.6666667\n711    1.0000000\n712   -1.3333333\n713    8.6666667\n714   -3.6666667\n715   -1.0000000\n716   -2.6666667\n717    0.0000000\n718    0.0000000\n719    3.6666667\n720    0.0000000\n721   -4.6666667\n722   -1.0000000\n723   -1.3333333\n724    4.3333333\n725   -4.6666667\n726    6.6666667\n727   -1.0000000\n728    3.3333333\n729    0.6666667\n730   -3.0000000\n731    0.3333333\n732    6.0000000\n733    4.6666667\n734   -2.6666667\n735    1.3333333\n736   -7.3333333\n737    0.0000000\n738    3.0000000\n739   -6.0000000\n740    0.0000000\n741   -3.0000000\n742   -1.6666667\n743    0.0000000\n744   -1.0000000\n745   -0.3333333\n746   -5.6666667\n747    0.6666667\n748   -4.6666667\n749   -5.6666667\n750    4.0000000\n751    3.0000000\n752    2.6666667\n753    1.3333333\n754   -7.0000000\n755   -3.3333333\n756    2.3333333\n757    8.3333333\n758   -2.3333333\n759    7.3333333\n760   -2.6666667\n761    8.0000000\n762    4.6666667\n763    5.3333333\n764   -3.0000000\n765    6.6666667\n766   -0.6666667\n767    0.0000000\n768    4.3333333\n769    1.0000000\n770   -2.6666667\n771   -1.3333333\n772   -1.0000000\n773   -2.0000000\n774   -7.0000000\n775    5.0000000\n776    2.6666667\n777   -1.6666667\n778   -5.3333333\n779   -2.3333333\n780    3.0000000\n781   -1.6666667\n782    1.6666667\n783    1.6666667\n784    4.3333333\n785    6.0000000\n786    7.0000000\n787    8.0000000\n788   -3.6666667\n789    8.0000000\n790   -3.0000000\n791    6.0000000\n792   -1.6666667\n793   -3.3333333\n794   -2.3333333\n795    9.6666667\n796   -8.6666667\n797   -4.0000000\n798  -11.6666667\n799    3.6666667\n800   -2.6666667\n801    3.0000000\n802   -3.3333333\n803    5.0000000\n804    7.0000000\n805    0.6666667\n806   -8.6666667\n807   10.6666667\n808   -1.6666667\n809    4.0000000\n810   -1.3333333\n811   -6.0000000\n812    5.0000000\n813    2.6666667\n814    1.3333333\n815    0.0000000\n816   -5.0000000\n817    8.0000000\n818    1.6666667\n819    3.6666667\n820    5.6666667\n821   -1.6666667\n822   -1.6666667\n823    7.0000000\n824   -3.3333333\n825   -5.6666667\n826    4.0000000\n827    2.3333333\n828   -0.6666667\n829   -3.0000000\n830    2.3333333\n831   -3.0000000\n832    2.6666667\n833    2.3333333\n834   -9.6666667\n835   -3.3333333\n836    1.3333333\n837    7.0000000\n838   -3.0000000\n839    5.6666667\n840   -3.0000000\n841   -5.6666667\n842    1.3333333\n843    5.3333333\n844   -2.6666667\n845   -2.0000000\n846    0.6666667\n847    3.3333333\n848   -0.3333333\n849    5.0000000\n850   -3.3333333\n851   -1.3333333\n852    6.0000000\n853   -5.3333333\n854   -6.0000000\n855   -7.3333333\n856   -4.6666667\n857    2.0000000\n858   -5.0000000\n859    5.6666667\n860    6.6666667\n861    0.0000000\n862    1.6666667\n863    8.3333333\n864   -5.0000000\n865    6.3333333\n866   -1.0000000\n867    7.0000000\n868   -6.3333333\n869    3.0000000\n870   -5.3333333\n871    5.6666667\n872   -0.6666667\n873    7.3333333\n874    0.3333333\n875   -7.6666667\n876    3.6666667\n877    2.0000000\n878   -4.0000000\n879    9.0000000\n880   -1.3333333\n881    2.6666667\n882   -5.6666667\n883   -3.6666667\n884    5.6666667\n885    4.0000000\n886   -4.3333333\n887    6.0000000\n888    6.3333333\n889   -5.3333333\n890   -2.0000000\n891    0.6666667\n892    3.3333333\n893   -3.0000000\n894    1.3333333\n895    1.0000000\n896   -4.3333333\n897   11.3333333\n898   -4.3333333\n899   -1.0000000\n900    0.0000000\n901    2.0000000\n902    1.0000000\n903  -10.3333333\n904    1.6666667\n905    1.6666667\n906    4.6666667\n907  -13.0000000\n908   -1.6666667\n909    1.3333333\n910   -2.0000000\n911    2.0000000\n912   -5.6666667\n913    2.0000000\n914   -3.0000000\n915   -6.0000000\n916   -8.6666667\n917    1.6666667\n918   -4.6666667\n919   -2.3333333\n920   -0.6666667\n921  -10.0000000\n922    2.0000000\n923    4.6666667\n924    2.0000000\n925   -2.0000000\n926   -6.0000000\n927    1.3333333\n928   -6.3333333\n929  -10.0000000\n930   -3.6666667\n931   -0.3333333\n932   -7.3333333\n933    4.6666667\n934    0.6666667\n935   -5.0000000\n936   -4.0000000\n937    0.3333333\n938    4.0000000\n939   -5.0000000\n940    2.6666667\n941   -3.0000000\n942    9.0000000\n943   -3.6666667\n944   -5.3333333\n945    3.0000000\n946   -1.3333333\n947    8.3333333\n948    3.0000000\n949    5.3333333\n950   -2.6666667\n951   -5.6666667\n952   -5.3333333\n953   -0.3333333\n954    2.0000000\n955    1.3333333\n956   -2.3333333\n957    3.6666667\n958    6.6666667\n959   -2.6666667\n960    0.3333333\n961   -4.6666667\n962    0.0000000\n963   -8.6666667\n964   -5.0000000\n965   -2.6666667\n966   -1.6666667\n967   -1.6666667\n968   -7.6666667\n969   -3.3333333\n970   -1.3333333\n971   -3.0000000\n972    1.0000000\n973   -2.0000000\n974   -2.3333333\n975    2.3333333\n976   -8.0000000\n977   -0.6666667\n978    9.0000000\n979    0.6666667\n980    2.0000000\n981    2.6666667\n982    0.6666667\n983    0.3333333\n984    0.3333333\n985    1.6666667\n986    1.0000000\n987    1.0000000\n988    0.0000000\n989   -3.6666667\n990   -0.6666667\n991    5.3333333\n992   -1.3333333\n993   -6.6666667\n994    2.6666667\n995    0.0000000\n996   -5.3333333\n997   -6.0000000\n998   -2.0000000\n999    6.6666667\n1000   1.6666667\n```\n\n\n:::\n:::\n\n\nThe permutation test for comparing tipping behaviour between vegetarians and non-vegetarians was conducted with 1000 iterations. The distribution of the difference in mean tips (diffmean) under the null hypothesis, where dietary preferences are randomly shuffled, suggests that the observed differences are small. The diffmean values range from negative to positive, indicating that differences in mean tip amounts vary slightly between vegetarians and non-vegetarians in the randomized samples. These differences appear to center around 0, with most of the values being close to it, implying that the observed differences between the two groups might not be statistically significant, and any difference in tipping behaviour could largely be due to chance.\n\n### Plotting the results of the Permutation Test\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_histogram(~ diffmean, data = perm_test_veg_nonveg, bins = 30) %>%\n  gf_labs(\n    title = \"Permutation Test for Tipping Differences: Vegetarians vs. Non-Vegetarians\",\n    x = \"Difference in Mean Tip Amount\",\n    y = \"Count\"\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nThe histogram from the permutation test comparing tipping differences between vegetarians and non-vegetarians shows that the distribution of differences in mean tip amounts is approximately centered around zero. This suggests that, under random shuffling of dietary preferences, the observed differences in mean tips could occur by chance.\n\n### Observed difference for Vegetarians vs Non-Vegetarians\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobserved_diff_veg_nonveg <- diffmean(Tip ~ Preference, data = tip_modified)\nobserved_diff_veg_nonveg\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndiffmean \n2.333333 \n```\n\n\n:::\n:::\n\n\nThe observed difference in the mean tip amount between vegetarians and non-vegetarians is approximately 2.33 rupees, with non-vegetarians giving a slightly higher average tip compared to vegetarians.\n\n### Calculating the p-value\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_value_veg_nonveg <- prop(~ (abs(diffmean) >= abs(observed_diff_veg_nonveg)), data = perm_test_veg_nonveg)\np_value_veg_nonveg\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nprop_TRUE \n    0.634 \n```\n\n\n:::\n:::\n\n\nThe p-value calculated for the permutation test comparing the tipping behavior between vegetarians and non-vegetarians is 0.675. This high p-value suggests that there is no statistically significant difference in the mean tip amounts between the two dietary preference groups. The observed difference of 2.33 rupees could have likely occurred by random chance, indicating that the dietary preference (vegetarian vs. non-vegetarian) does not have a strong influence on tipping behaviour in this sample. Therefore, we fail to reject the null hypothesis.\n\n### Permutation test for Males vs Females\n\n\n::: {.cell}\n\n```{.r .cell-code}\nperm_test_gender <- do(1000) * diffmean(Tip ~ shuffle(Gender), data = tip_modified)\nperm_test_gender\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        diffmean\n1      0.0000000\n2      4.0000000\n3     -2.6666667\n4      5.3333333\n5      6.6666667\n6     -4.6666667\n7      4.3333333\n8      4.3333333\n9     -5.3333333\n10     0.0000000\n11     0.6666667\n12    -1.3333333\n13     2.3333333\n14    -5.3333333\n15     3.3333333\n16    -2.3333333\n17   -10.3333333\n18    -4.0000000\n19    -3.3333333\n20    -0.6666667\n21     0.0000000\n22     0.3333333\n23     1.6666667\n24    -2.0000000\n25    -8.0000000\n26    -5.0000000\n27    -3.0000000\n28    -2.6666667\n29    -2.3333333\n30     0.6666667\n31    -6.0000000\n32    -1.0000000\n33    -1.6666667\n34    -2.3333333\n35    -6.0000000\n36    -1.6666667\n37     8.0000000\n38     0.6666667\n39     6.3333333\n40    -9.3333333\n41    -4.6666667\n42    -1.6666667\n43     1.3333333\n44     8.3333333\n45     0.3333333\n46     5.6666667\n47     1.6666667\n48     7.6666667\n49    -0.6666667\n50    -1.6666667\n51     4.6666667\n52    -6.3333333\n53    -0.3333333\n54   -11.6666667\n55     2.0000000\n56     2.6666667\n57     8.3333333\n58     2.3333333\n59    -4.0000000\n60    -5.0000000\n61     0.6666667\n62    -9.6666667\n63     3.3333333\n64    -1.0000000\n65     3.3333333\n66    -1.6666667\n67     0.3333333\n68     1.0000000\n69    -0.6666667\n70     6.0000000\n71    -1.6666667\n72    -2.6666667\n73     2.0000000\n74    -6.3333333\n75   -11.3333333\n76    -3.3333333\n77    -2.3333333\n78    -3.0000000\n79    -0.3333333\n80    -3.3333333\n81     2.6666667\n82    -5.3333333\n83    -4.6666667\n84    -1.3333333\n85     2.0000000\n86    -2.6666667\n87     1.3333333\n88    -2.3333333\n89    -3.3333333\n90     2.6666667\n91    -1.3333333\n92    -7.0000000\n93     4.6666667\n94    -3.0000000\n95    -7.3333333\n96    -8.0000000\n97    -6.0000000\n98    -8.3333333\n99     0.3333333\n100    1.3333333\n101    1.3333333\n102    1.0000000\n103   -2.6666667\n104   -4.6666667\n105   -1.6666667\n106    1.0000000\n107    1.6666667\n108    1.3333333\n109    5.3333333\n110   -6.3333333\n111    3.0000000\n112    0.3333333\n113   -3.6666667\n114    1.0000000\n115   -0.6666667\n116   -1.3333333\n117    5.3333333\n118    0.3333333\n119   -4.0000000\n120   -3.0000000\n121    0.0000000\n122    4.6666667\n123    1.6666667\n124   -8.0000000\n125    9.0000000\n126   -4.3333333\n127   -4.3333333\n128    1.0000000\n129    6.3333333\n130    1.6666667\n131    0.3333333\n132   -1.3333333\n133    0.3333333\n134   -6.0000000\n135   -1.3333333\n136   -0.6666667\n137    3.0000000\n138   -2.0000000\n139   -1.0000000\n140    4.6666667\n141    6.6666667\n142  -10.0000000\n143    4.3333333\n144    2.3333333\n145    2.0000000\n146  -11.0000000\n147   -4.3333333\n148    0.3333333\n149   -2.3333333\n150   -2.3333333\n151   -4.6666667\n152    2.6666667\n153    3.3333333\n154   -3.0000000\n155    1.3333333\n156    4.3333333\n157    1.0000000\n158   -3.3333333\n159   -2.0000000\n160    4.3333333\n161    5.6666667\n162    4.3333333\n163   -6.3333333\n164    2.0000000\n165   -2.6666667\n166    0.0000000\n167   -3.3333333\n168   -2.3333333\n169    0.3333333\n170    8.0000000\n171   -2.3333333\n172    2.6666667\n173   -3.6666667\n174   -2.0000000\n175    1.6666667\n176   -0.3333333\n177   -2.0000000\n178    4.6666667\n179   -7.6666667\n180   -3.3333333\n181   -2.3333333\n182    9.0000000\n183    0.6666667\n184    0.3333333\n185   -2.6666667\n186    1.0000000\n187   -1.6666667\n188    4.0000000\n189    1.0000000\n190   -0.6666667\n191   -3.6666667\n192    7.3333333\n193    6.0000000\n194    6.6666667\n195   -6.6666667\n196   -0.3333333\n197  -10.0000000\n198   -5.0000000\n199   -5.3333333\n200    4.3333333\n201   -7.3333333\n202    2.0000000\n203    1.6666667\n204    5.3333333\n205    6.0000000\n206    3.0000000\n207    4.0000000\n208   -1.3333333\n209   -2.0000000\n210    2.6666667\n211   -2.6666667\n212  -14.3333333\n213   -0.6666667\n214    6.6666667\n215   -2.0000000\n216   -3.3333333\n217   -6.0000000\n218    8.6666667\n219   -4.0000000\n220   -1.6666667\n221    2.0000000\n222   -1.6666667\n223    0.6666667\n224   -8.3333333\n225    7.6666667\n226    2.0000000\n227   -0.6666667\n228    4.3333333\n229   11.6666667\n230    1.6666667\n231    0.3333333\n232    0.0000000\n233    4.6666667\n234   -3.3333333\n235   -3.6666667\n236   -3.6666667\n237    2.0000000\n238   11.3333333\n239   -3.6666667\n240    1.3333333\n241   -6.3333333\n242   -2.0000000\n243    0.6666667\n244    0.6666667\n245    0.0000000\n246   -6.6666667\n247   -3.0000000\n248    7.3333333\n249   -1.6666667\n250   -1.3333333\n251    1.3333333\n252   -1.0000000\n253    0.6666667\n254   -2.3333333\n255    5.6666667\n256    5.3333333\n257   -2.3333333\n258   -7.0000000\n259    5.3333333\n260    1.6666667\n261    3.0000000\n262   -5.3333333\n263    8.0000000\n264   -2.0000000\n265   -1.0000000\n266   -3.6666667\n267   12.6666667\n268   -1.3333333\n269    2.3333333\n270   -1.0000000\n271    2.6666667\n272   -2.6666667\n273   -3.3333333\n274   -1.6666667\n275    0.6666667\n276    0.0000000\n277   -1.6666667\n278    3.6666667\n279    1.6666667\n280    4.0000000\n281   -2.6666667\n282   -1.3333333\n283    7.6666667\n284    1.3333333\n285    7.3333333\n286    1.6666667\n287    1.6666667\n288    2.0000000\n289    1.6666667\n290    9.0000000\n291    2.6666667\n292   -1.3333333\n293    6.0000000\n294    1.6666667\n295   -5.0000000\n296    6.6666667\n297   -7.3333333\n298    2.0000000\n299   -0.3333333\n300   -7.3333333\n301    1.3333333\n302    4.6666667\n303    0.0000000\n304   -7.6666667\n305   -5.3333333\n306    1.6666667\n307    0.3333333\n308   -0.6666667\n309    0.3333333\n310   -1.0000000\n311    0.3333333\n312    5.0000000\n313    0.6666667\n314    1.0000000\n315    1.3333333\n316    1.3333333\n317   -2.0000000\n318    0.6666667\n319    2.0000000\n320    7.6666667\n321    3.0000000\n322    1.0000000\n323    2.3333333\n324    3.6666667\n325    4.0000000\n326    4.0000000\n327    5.0000000\n328   -3.0000000\n329    4.0000000\n330   -2.6666667\n331    0.6666667\n332    3.0000000\n333    0.3333333\n334   -0.6666667\n335   -7.3333333\n336   -1.6666667\n337    7.6666667\n338   -3.3333333\n339    0.3333333\n340    4.0000000\n341    6.0000000\n342   -6.6666667\n343   -6.3333333\n344   -4.0000000\n345   -9.3333333\n346   -3.3333333\n347    2.6666667\n348    3.0000000\n349   -8.0000000\n350    0.6666667\n351   -4.0000000\n352    3.3333333\n353    2.6666667\n354   -2.0000000\n355    7.6666667\n356    0.0000000\n357   -3.0000000\n358    2.3333333\n359    1.3333333\n360    1.6666667\n361    3.0000000\n362   -3.6666667\n363   -0.3333333\n364   -2.3333333\n365   -2.3333333\n366    1.0000000\n367   -5.3333333\n368    6.6666667\n369    6.6666667\n370    4.6666667\n371    2.6666667\n372   -5.3333333\n373   -3.6666667\n374    5.6666667\n375    1.3333333\n376   -0.3333333\n377   10.3333333\n378   -5.3333333\n379    5.0000000\n380   -3.3333333\n381    0.0000000\n382   -6.3333333\n383   -2.3333333\n384   -5.6666667\n385    0.0000000\n386   -1.0000000\n387    6.6666667\n388    4.3333333\n389    2.6666667\n390    0.0000000\n391    9.3333333\n392   -4.6666667\n393   10.0000000\n394   -7.6666667\n395    4.3333333\n396  -10.3333333\n397   -2.6666667\n398    7.6666667\n399   -4.0000000\n400   -4.6666667\n401    2.6666667\n402   -3.0000000\n403    0.3333333\n404    0.6666667\n405    1.3333333\n406   -4.6666667\n407    3.0000000\n408   -0.6666667\n409    3.3333333\n410    3.3333333\n411    9.3333333\n412   -1.6666667\n413    3.6666667\n414   -7.0000000\n415   -3.0000000\n416    4.0000000\n417   -0.3333333\n418   -1.6666667\n419    3.3333333\n420   -1.6666667\n421    1.3333333\n422   -3.3333333\n423   10.3333333\n424   -8.0000000\n425   -3.0000000\n426    1.6666667\n427    9.6666667\n428   -4.0000000\n429    1.3333333\n430    5.3333333\n431    1.0000000\n432    7.0000000\n433   -9.0000000\n434   -0.3333333\n435    3.3333333\n436    6.6666667\n437   -2.6666667\n438    2.3333333\n439   -3.6666667\n440   -4.3333333\n441   -6.3333333\n442    2.6666667\n443    0.3333333\n444    6.0000000\n445    1.0000000\n446   -6.0000000\n447    4.0000000\n448    9.6666667\n449    4.0000000\n450    2.0000000\n451   -0.3333333\n452   -5.6666667\n453    4.3333333\n454    1.3333333\n455   -1.3333333\n456    5.0000000\n457   -4.3333333\n458    1.6666667\n459   -4.6666667\n460   -2.6666667\n461    0.6666667\n462   -1.0000000\n463    5.6666667\n464   -0.3333333\n465  -10.3333333\n466   -8.6666667\n467   -5.0000000\n468   -0.6666667\n469   -5.3333333\n470   -5.6666667\n471   -5.0000000\n472   -5.0000000\n473    1.0000000\n474   -4.6666667\n475    2.6666667\n476   -6.0000000\n477    0.0000000\n478    7.6666667\n479    7.3333333\n480    9.3333333\n481    0.3333333\n482   -2.0000000\n483   -6.0000000\n484    4.0000000\n485    3.6666667\n486   -4.0000000\n487    1.0000000\n488    4.6666667\n489   -8.3333333\n490    1.6666667\n491   -2.6666667\n492   -1.6666667\n493   -2.0000000\n494  -10.0000000\n495   -0.6666667\n496    2.3333333\n497    3.0000000\n498    2.0000000\n499   -5.6666667\n500   -2.3333333\n501    4.0000000\n502    4.6666667\n503    3.6666667\n504   -4.3333333\n505    4.6666667\n506   -7.6666667\n507    9.0000000\n508   -1.0000000\n509    1.0000000\n510    1.3333333\n511    5.6666667\n512    0.3333333\n513   -3.0000000\n514   -0.6666667\n515    6.0000000\n516    4.3333333\n517    0.3333333\n518   -2.0000000\n519   -1.6666667\n520    1.6666667\n521   -1.3333333\n522    0.3333333\n523    1.3333333\n524   -3.0000000\n525    6.6666667\n526    6.6666667\n527   -3.6666667\n528    1.6666667\n529    7.6666667\n530    3.0000000\n531    9.0000000\n532   -2.6666667\n533    5.0000000\n534   -5.0000000\n535   -8.3333333\n536    8.6666667\n537    7.0000000\n538    4.6666667\n539   10.6666667\n540    0.3333333\n541   -3.6666667\n542    3.3333333\n543    3.6666667\n544   -0.6666667\n545   -6.0000000\n546    5.0000000\n547   -4.0000000\n548    6.3333333\n549   -0.3333333\n550    0.3333333\n551   -2.0000000\n552   -3.3333333\n553   -1.0000000\n554    2.6666667\n555    7.3333333\n556    5.3333333\n557   -5.3333333\n558    0.6666667\n559    4.3333333\n560   -8.6666667\n561   -2.0000000\n562   -7.6666667\n563   -1.6666667\n564    2.6666667\n565   -3.6666667\n566   -0.6666667\n567    2.6666667\n568   -8.6666667\n569   -2.6666667\n570    2.3333333\n571   -5.6666667\n572   -8.0000000\n573    5.6666667\n574   -1.6666667\n575   -4.6666667\n576    0.3333333\n577   -6.6666667\n578    5.3333333\n579    6.3333333\n580    4.6666667\n581   -3.3333333\n582   -0.6666667\n583    0.6666667\n584    3.3333333\n585    5.6666667\n586    8.3333333\n587   -7.6666667\n588   -2.0000000\n589   -4.0000000\n590    1.6666667\n591    0.6666667\n592   -7.6666667\n593    8.0000000\n594    9.6666667\n595    2.3333333\n596   -8.0000000\n597   -1.3333333\n598   -0.3333333\n599    2.0000000\n600   -3.0000000\n601    2.6666667\n602    8.0000000\n603    4.6666667\n604   -4.6666667\n605    1.0000000\n606   -2.6666667\n607    1.0000000\n608    4.3333333\n609   -8.0000000\n610    1.3333333\n611   -5.0000000\n612   -0.6666667\n613    6.0000000\n614    0.3333333\n615   -7.6666667\n616   -3.6666667\n617   -7.0000000\n618   -3.6666667\n619  -11.3333333\n620    7.6666667\n621   -9.3333333\n622   -6.6666667\n623   -4.3333333\n624   -2.3333333\n625    0.3333333\n626    7.3333333\n627   -2.0000000\n628   -1.3333333\n629    1.0000000\n630    2.3333333\n631   -2.0000000\n632    4.0000000\n633    0.3333333\n634   -3.6666667\n635    3.6666667\n636   -0.6666667\n637   -3.6666667\n638    6.0000000\n639    2.0000000\n640   -3.6666667\n641    3.6666667\n642   -5.6666667\n643    1.0000000\n644   -4.3333333\n645  -12.0000000\n646    1.3333333\n647    2.0000000\n648   -3.0000000\n649   -4.0000000\n650    4.6666667\n651   -1.0000000\n652   -1.0000000\n653    1.6666667\n654   -0.3333333\n655    8.6666667\n656   -5.6666667\n657   -8.3333333\n658   -3.3333333\n659   -1.0000000\n660   -4.0000000\n661   -2.3333333\n662    2.0000000\n663    5.6666667\n664   -5.3333333\n665   -5.6666667\n666    0.3333333\n667    8.3333333\n668   -5.6666667\n669   -5.0000000\n670   -1.3333333\n671    6.0000000\n672   -2.0000000\n673    5.0000000\n674    1.3333333\n675    8.6666667\n676   -3.0000000\n677    8.3333333\n678   -3.3333333\n679    2.0000000\n680    4.0000000\n681    6.3333333\n682    1.0000000\n683    8.6666667\n684   -1.0000000\n685    4.3333333\n686   -5.6666667\n687   -1.0000000\n688    5.0000000\n689    7.3333333\n690    3.3333333\n691   -2.0000000\n692   -4.6666667\n693    2.0000000\n694    6.0000000\n695   -1.0000000\n696    2.0000000\n697    5.3333333\n698   -9.6666667\n699   -6.0000000\n700   -2.0000000\n701    4.6666667\n702   -4.0000000\n703    3.0000000\n704    1.6666667\n705   -7.6666667\n706   -1.0000000\n707   -4.3333333\n708   10.6666667\n709   -0.3333333\n710    0.6666667\n711    8.3333333\n712   -4.0000000\n713    6.3333333\n714    5.6666667\n715   -8.3333333\n716    3.6666667\n717    2.0000000\n718    2.6666667\n719  -10.3333333\n720    2.0000000\n721   -4.3333333\n722    2.6666667\n723    9.0000000\n724   -8.0000000\n725    6.0000000\n726   -7.6666667\n727    3.0000000\n728   -3.6666667\n729    2.0000000\n730    5.3333333\n731    1.3333333\n732   -2.3333333\n733   -6.6666667\n734    7.6666667\n735   -5.3333333\n736   -3.6666667\n737   -8.3333333\n738    0.0000000\n739   -6.0000000\n740    9.3333333\n741    1.3333333\n742   -5.6666667\n743   -3.6666667\n744   -6.6666667\n745   -6.0000000\n746   -4.6666667\n747   -4.3333333\n748   -3.3333333\n749    2.3333333\n750   -1.0000000\n751   -1.3333333\n752   -3.3333333\n753   -0.6666667\n754    1.3333333\n755    2.0000000\n756   -6.6666667\n757    1.3333333\n758   -0.3333333\n759    6.0000000\n760   -6.0000000\n761    2.0000000\n762    0.3333333\n763   -4.0000000\n764   -2.6666667\n765    0.6666667\n766    5.6666667\n767   -7.0000000\n768    2.0000000\n769   -0.3333333\n770    5.0000000\n771    1.0000000\n772   -1.0000000\n773    2.3333333\n774    2.0000000\n775    7.0000000\n776    4.0000000\n777   -3.0000000\n778   -0.6666667\n779   -8.6666667\n780    2.6666667\n781    2.6666667\n782    3.3333333\n783    5.6666667\n784   -6.0000000\n785    7.6666667\n786    1.3333333\n787  -12.3333333\n788   -1.3333333\n789    2.0000000\n790   -2.3333333\n791    5.0000000\n792    2.3333333\n793   -2.6666667\n794    0.6666667\n795    6.3333333\n796    5.6666667\n797    2.6666667\n798   -5.6666667\n799   -6.0000000\n800   -1.6666667\n801   -7.0000000\n802   -4.0000000\n803   -8.0000000\n804   -2.0000000\n805   -4.0000000\n806    2.0000000\n807    2.0000000\n808   -3.6666667\n809    3.6666667\n810    1.0000000\n811   -5.3333333\n812   -2.6666667\n813    2.3333333\n814    4.0000000\n815    6.6666667\n816   -2.6666667\n817   -1.6666667\n818   -3.6666667\n819    0.6666667\n820    0.0000000\n821   -7.3333333\n822    3.0000000\n823    2.6666667\n824    2.3333333\n825   -4.6666667\n826    5.3333333\n827    5.3333333\n828   -6.0000000\n829   10.3333333\n830   -8.3333333\n831   -2.3333333\n832   -2.3333333\n833   -2.3333333\n834   15.3333333\n835   -9.3333333\n836   -7.0000000\n837    0.3333333\n838    1.0000000\n839   -7.3333333\n840   -7.3333333\n841    1.3333333\n842    0.6666667\n843   -5.3333333\n844   -0.6666667\n845   -1.6666667\n846    3.6666667\n847   -4.0000000\n848    0.6666667\n849   -0.3333333\n850    0.6666667\n851   -0.6666667\n852    5.0000000\n853    3.6666667\n854    1.6666667\n855    4.3333333\n856   -1.0000000\n857   -2.0000000\n858    0.6666667\n859    1.3333333\n860    0.6666667\n861    6.6666667\n862    3.6666667\n863    2.3333333\n864    3.3333333\n865    8.6666667\n866    8.3333333\n867   -1.6666667\n868   -2.6666667\n869    3.3333333\n870   -4.0000000\n871    1.3333333\n872    0.0000000\n873   -2.0000000\n874    3.0000000\n875    6.6666667\n876   -1.0000000\n877   -0.6666667\n878    4.0000000\n879    0.0000000\n880    4.6666667\n881   -1.0000000\n882    1.6666667\n883   -4.6666667\n884    0.3333333\n885   -2.0000000\n886    1.3333333\n887    1.0000000\n888   -1.6666667\n889    0.6666667\n890    0.0000000\n891   -2.3333333\n892    3.0000000\n893   -3.6666667\n894   -5.6666667\n895   -9.0000000\n896    3.0000000\n897   -2.3333333\n898    4.3333333\n899    3.6666667\n900    3.3333333\n901    5.3333333\n902    0.0000000\n903    5.6666667\n904   -4.3333333\n905   -1.0000000\n906    4.3333333\n907   -4.6666667\n908   -1.3333333\n909    3.0000000\n910   10.0000000\n911  -11.0000000\n912    5.0000000\n913    3.0000000\n914    4.6666667\n915   -7.3333333\n916    3.3333333\n917   -1.6666667\n918    2.6666667\n919    2.3333333\n920   -2.3333333\n921    8.6666667\n922   -0.3333333\n923   -0.6666667\n924    2.6666667\n925   -0.6666667\n926   10.6666667\n927    4.6666667\n928    2.0000000\n929    8.6666667\n930    5.0000000\n931    2.0000000\n932    1.3333333\n933    4.0000000\n934   -0.3333333\n935   -6.0000000\n936   -1.3333333\n937   -3.6666667\n938   -5.6666667\n939    2.3333333\n940    0.3333333\n941   -2.3333333\n942   -0.3333333\n943   -7.6666667\n944   -2.0000000\n945   -6.3333333\n946   -4.3333333\n947   -6.0000000\n948    8.0000000\n949   -2.0000000\n950   -5.3333333\n951   -6.3333333\n952    0.0000000\n953    5.0000000\n954   -4.3333333\n955    0.0000000\n956   -0.3333333\n957    3.0000000\n958    2.3333333\n959    3.0000000\n960   -8.0000000\n961    3.0000000\n962   -4.0000000\n963    1.6666667\n964    0.6666667\n965    1.3333333\n966   -4.0000000\n967    1.6666667\n968   -4.0000000\n969    7.0000000\n970   -7.3333333\n971   -6.6666667\n972   -2.6666667\n973   -4.0000000\n974   -2.6666667\n975    7.0000000\n976    6.3333333\n977   -3.0000000\n978    6.6666667\n979   -4.0000000\n980   -3.0000000\n981    1.3333333\n982   -4.6666667\n983   -1.0000000\n984    0.6666667\n985    4.3333333\n986   -6.6666667\n987   -1.3333333\n988   -9.0000000\n989   -6.3333333\n990    4.6666667\n991    8.3333333\n992   -1.6666667\n993    0.0000000\n994   -1.6666667\n995    0.0000000\n996    7.3333333\n997   -1.0000000\n998  -13.6666667\n999    4.0000000\n1000  -2.6666667\n```\n\n\n:::\n:::\n\n\nThe permutation test comparing the tipping behaviour between males and females was conducted by randomly shuffling the gender labels 1,000 times and calculating the difference in mean tip amounts for each shuffle. The resulting distribution of differences varied around zero, with values like -7.33, 1.00, -2.00, and 3.66 observed. This distribution suggests that any observed difference in tipping behaviour between males and females could largely be attributed to random variation, rather than a true underlying difference in tipping habits based on gender.\n\n### Plotting the results of the Permutation Test\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_histogram(~ diffmean, data = perm_test_gender, bins = 30) %>%\n  gf_labs(\n    title = \"Permutation Test for Tipping Differences: Males vs. Females\",\n    x = \"Difference in Mean Tip Amount\",\n    y = \"Count\"\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\nThe permutation test for tipping differences between males and females shows a symmetric distribution centered around zero. The differences in mean tipping amounts vary from approximately -10 to 10 rupees. This indicates that, based on the resampled data, the observed differences in tipping between males and females are likely due to random chance. The distribution does not suggest a strong or consistent difference in tipping behaviour between the two genders.\n\n### Observed difference for Males vs Females\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobserved_diff_gender <- diffmean(Tip ~ Gender, data = tip_modified)\nobserved_diff_gender\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndiffmean \n      -2 \n```\n\n\n:::\n:::\n\n\nThe observed difference in mean tips between males and females is -2 rupees. This indicates that, on average, males tend to tip 2 rupees less than females in the dataset.\n\n### Calculating the p-value\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_value_gender <- prop(~ (abs(diffmean) >= abs(observed_diff_gender)), data = perm_test_gender)\np_value_gender\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nprop_TRUE \n    0.699 \n```\n\n\n:::\n:::\n\n\nThe permutation test conducted to assess the difference in tipping behaviour between males and females resulted in a p-value of 0.697. This p-value is quite high, indicating that the observed difference in mean tips between males and females (-2 rupees) is not statistically significant. In other words, there is a 69.7% probability that the observed difference could have occurred by random chance. Therefore, we do not have enough evidence to conclude that there is a significant difference in tipping behaviour between males and females based on this dataset.\n\n### Summary of Results for the Tipping Behaviour Research Experiment\n\nThe research experiment aimed to determine if there was a significant difference in tipping behaviour between vegetarians and non-vegetarians, and between male and female students at MAHE Bengaluru. The following statistical tests were conducted:\n\n**Two-Sample t-Test (Welch’s t-test):**\n\n1.  **Vegetarians vs. Non-Vegetarians**: The two-sample t-test comparing the mean tip amounts between vegetarians and non-vegetarians resulted in a p-value of 0.6169. This indicates no statistically significant difference in the average tip amount between the two dietary groups, as the p-value is much higher than the typical threshold of 0.05.\n\n2.  **Males vs. Females**: The t-test comparing the mean tip amounts between males and females resulted in a p-value of 0.6679. This also suggests no significant difference in tipping behaviour based on gender.\n\n**Wilcoxon Rank-Sum Test:**\n\n1.  **Vegetarians vs. Non-Vegetarians**: The Wilcoxon test, a non-parametric alternative to the t-test, resulted in a p-value of 0.8327. This further supports the t-test results, indicating no significant difference between vegetarians and non-vegetarians in terms of tipping behaviour.\n\n2.  **Males vs. Females**: The Wilcoxon test comparing males and females resulted in a p-value of 0.4221, which also suggests no statistically significant difference between the two genders.\n\n**Permutation Test:**\n\n1.  **Vegetarians vs. Non-Vegetarians**: The permutation test comparing tipping behaviour between vegetarians and non-vegetarians resulted in a p-value of 0.675, confirming that the observed difference in mean tip amounts of approximately 2.33 rupees is likely due to random variation and not a significant underlying difference.\n\n2.  **Males vs. Females**: The permutation test for tipping differences between males and females resulted in a p-value of 0.697. The observed difference in mean tip amounts (-2 rupees, with females tipping slightly more on average) is also likely due to random variation.\n\n### Conclusion:\n\nBased on the results of these tests, there is no evidence to suggest that either dietary preference (vegetarian vs. non-vegetarian) or gender (male vs. female) significantly impacts tipping behaviour in this dataset. The high p-values across all tests indicate that the observed differences in tipping amounts are likely due to chance. Therefore, the initial hypotheses that non-vegetarians might tip more than vegetarians, or that one gender tips more than the other, are not supported by the data.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}